### ISSUE TITLE
validate_uniqueness_of seems to be messing with Rails serialized attributes

### ISSUE THREAD

**Issue by jeroenj** [thoughtbot/shoulda-matchers#1000]
Since this is not so easy to describe I've created a repository which reproduces the issue: https://github.com/jeroenj/rspec-or-shoulda-matchers-issue

Basically this is the issue:

Let's say you have a model `Project` which has a serialized array attribute:

```ruby
class Project < ActiveRecord::Base
  serialize :groups, Array

  validates :name, presence: true, uniqueness: true
end
```

and you have it defined with a default value and a null constraint for `groups`:

```ruby
  create_table "projects", force: :cascade do |t|
    t.string   "name"
    t.string   "groups",     default: "--- []\n", null: false
    t.datetime "created_at",                      null: false
    t.datetime "updated_at",                      null: false
    t.string   "category",   default: "none",     null: false
  end
```

In a test uniqueness is validated for the `name` field:

`it { is_expected.to validate_uniqueness_of(:name) }`

As soon as that test is ran all following instances of creating a `Project` resource without passing `groups` explicitly will fail because of a null constraint in the database. It looks like something is messing with the default value for `groups` causing it to generate `NULL` in the SQL query: `SQLite3::ConstraintException: NOT NULL constraint failed:projects\.groups: INSERT INTO "projects" \("groups", "name", "created_at","updated_at"\) VALUES \(?, ?, ?, ?\)'`

Check this test to see what I mean: https://github.com/jeroenj/rspec-or-shoulda-matchers-issue/blob/master/spec/models/project_spec.rb.

**Comment by aaronmallen** [comment]
I am actually seeing a failure for `should serialize`more akin to #639 

```ruby
# app/models/foo.rb
class Foo < ApplicationRecord
  serialize :names, Array # this is a text not null column
  validates :names, presence: true
end
```

```ruby
# spec/models/foo.rb
RSpec.describe Foo, type: :model do
  it { should serialize :names }
  it { should validate_presence_of :names }
end
```

```bash
Foo should serialize :names
Failure/Error: it { should serialize :names }

NoMethodError:
 undefined method `cast_type' for #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0x00007fe7b20c3928>
# /Users/<redacted>/.rvm/gems/ruby-2.4.2@my-app/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/rails_shim.rb:58:in `block in serialized_attributes_for'
# /Users/<redacted>/.rvm/gems/ruby-2.4.2@my-app/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/rails_shim.rb:57:in `select'
# /Users/<redacted>/.rvm/gems/ruby-2.4.2@my-app/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/rails_shim.rb:57:in `serialized_attributes_for'
# /Users/<redacted>/.rvm/gems/ruby-2.4.2@my-app/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_record/serialize_matcher.rb:196:in `serialized_attributes'
# /Users/<redacted>/.rvm/gems/ruby-2.4.2@my-app/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_record/serialize_matcher.rb:188:in `attribute_is_serialized?'
# /Users/<redacted>/.rvm/gems/ruby-2.4.2@my-app/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_record/serialize_matcher.rb:133:in `serialization_valid?'
# /Users/<redacted>/.rvm/gems/ruby-2.4.2@my-app/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_record/serialize_matcher.rb:111:in `matches?'
# ./spec/models/foo.rb:3:in `block (2 levels) in <top (required)>'
```

```ruby
# Gemfile.lock
rspec-core (3.7.0)
  rspec-support (~> 3.7.0)
rspec-expectations (3.7.0)
  diff-lcs (>= 1.2.0, < 2.0)
  rspec-support (~> 3.7.0)
rspec-mocks (3.7.0)
  diff-lcs (>= 1.2.0, < 2.0)
  rspec-support (~> 3.7.0)
rspec-rails (3.7.1)
  actionpack (>= 3.0)
  activesupport (>= 3.0)
  railties (>= 3.0)
  rspec-core (~> 3.7.0)
  rspec-expectations (~> 3.7.0)
  rspec-mocks (~> 3.7.0)
  rspec-support (~> 3.7.0)
rspec-support (3.7.0)
shoulda (3.5.0)
  shoulda-context (~> 1.0, >= 1.0.1)
  shoulda-matchers (>= 1.4.1, < 3.0)
shoulda-context (1.2.2)
shoulda-matchers (2.8.0)
```

**Comment by mcmire** [comment]
@aaronmallen That looks like it's the same issue as #913. We've fixed this, but haven't put out a new release yet. You may wish to modify your Gemfile to point to the `master` branch.

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
