### ISSUE TITLE
undefined method   'respond_with' for RSpec

### ISSUE THREAD

**Issue by Dreamseeker92** [thoughtbot/shoulda-matchers#1002]
i have ths error message 

>  undefined method `respond_with' for #<RSpec::ExampleGroups::IntegearionTestForPages::CheckingRootOme::GetHomePage:0x0055873ec478e8>
>        Did you mean?  respond_to
> 
> i configured shoulda matchers  in rails_helper as it written in docs
> rails_helper.rb:

```
require 'spec_helper'
require 'rspec/rails'
require 'shoulda/matchers'
require 'capybara/rspec'
require 'devise'


require 'shoulda/matchers'

Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :rails
  end
end
```

my test_spec

```
 describe "get home page" do
      before { get pages_home_path }
      it { should respond_with(200)}
      
      end
```

my gemfile

> group :development, :test do
>   gem 'byebug', platform: :mri
>   gem 'faker'
> gem 'spring'
>   gem 'spring-watcher-listen'
>  end

> group :test do
>   gem 'rspec-rails'
>   gem 'shoulda-matchers', '~> 3.1', '>= 3.1.1'
>   gem 'capybara'
>   gem 'factory_girl_rails'
>   gem 'rails-controller-testing', :git => 'git://github.com/rails/rails-controller-testing.git'
>   gem 'database_cleaner'
> > end

> group :development do
>   gem 'web-console', '>= 3.3.0'
>   gem 'listen', '~> 3.0.5'
> end

i prefer bitbucket  to github., so here is
[my repo](https://bitbucket.org/gravity_slave/pro-ror-5-slim/src)

**Comment by mcmire** [comment]
It looks like you're using `respond_with` in a feature spec. `respond_with` is a controller matcher, so it can only be used in controller specs. (Same for `have_http_status`.)

**Comment by Dreamseeker92** [comment]
it helped! Thnaks

**Comment by mcmire** [comment]
Glad I could help! Cheers 😎
