### ISSUE TITLE
validate_uniqueness_of fails when using before_save callback

### ISSUE THREAD

**Issue by rorykoehler** [thoughtbot/shoulda-matchers#1003]
Running into an issue where it seems the before_save callback is not being passed an object. Removing before_save callback makes the test pass. Other spec to ensure the callback is working is passing.

Model file:

     #Validations
     validates :name, presence: true, uniqueness: true

     #Callbacks
     before_save { self.name = self.name.titleize

Spec file:

      it {should validate_presence_of(:name)}
      it {should validate_uniqueness_of(:name)}

Rspec Output:

    1) Category should validate that :name is case-sensitively unique
         Failure/Error: before_save { self.name = self.name.titleize}
     
         NoMethodError:
           undefined method `titleize' for nil:NilClass

**Comment by mcmire** [comment]
@rorykoehler shoulda-matchers does not actually save the record, it only runs the validation. Therefore, `before_save` will not be called. You'll need to use `before_validation` instead.

**Comment by rorykoehler** [comment]
@mcmire ah ok. Thanks for the tip
