### ISSUE TITLE
ensure_length_of problem

### ISSUE THREAD

**Issue by nicovalencia** [thoughtbot/shoulda-matchers#102]
Not sure if this is a newer Rails problem (I'm on 3.2.2), or if I'm using this improperly, but the ensure_length_of matcher seems to be failing a correct match due to ActiveRecord error hash format. (Possibly strict comparison in errors array?)

user_spec.rb

```
...
describe User do
  it { should ensure_length_of(:card_number).is_equal_to(14) }
end
```

test output

``` Failures:

  1) User 
     Failure/Error: it { should ensure_length_of(:card_number).is_equal_to(14) }

       Expected errors to include "is the wrong length (should be 14 characters)" 
       when card_number is set to "xxxxxxxxxxxxxx", got errors:
       ["card_number is the wrong length (should be 14 characters) (0)"]
```

**Comment by serixscorpio** [comment]
+1

**Comment by mcmire** [comment]
This feature will never be implemented, sorry about that. If you care about the length of a numeric field, then your field shouldn't be an integer, it should be a string.
