### ISSUE TITLE
should serialize not found

### ISSUE THREAD

**Issue by chrishough** [thoughtbot/shoulda-matchers#1023]
I am getting a very odd issue when trying to validate a user model serialize method in rspec 3.6.
Thoughts on this bug?

```ruby
  describe 'serialize methods' do
    it { should serialize(:thing) }
  end
```
Error
```
1) User serialize methods should serialize :thing
     Failure/Error: it { should serialize(:thing) }
       Expected User to serialize the attribute called :thing (no serialized attribute called :social_media)
     # ./spec/models/user_spec.rb:131:in `block (3 levels) in <top (required)>'
```

**Comment by mcmire** [comment]
That is a very odd issue indeed. Are you sure that's the error you're getting? It seems strange that the two attributes in your message don't match.

**Comment by chrishough** [comment]
Yes, I copied and pasted it. Very odd.

**Comment by mcmire** [comment]
Okay. Where is `social_media` coming from? Is that another attribute of your model?

**Comment by chrishough** [comment]
It's very odd, but it must be coming from a gem.  I am going to close this for now until it can be researched further.  Also, the issue is no longer occurring as originally posted.

**Comment by mcmire** [comment]
Okay, sounds good @chrishough, thanks for the follow-up.
