### ISSUE TITLE
Deprecation warning for deprecated Fixnum in Ruby 2.4.0

### ISSUE THREAD

**Issue by bryszard** [thoughtbot/shoulda-matchers#1035]
As we switched to Ruby 2.4.0 we're getting now quite a lot of deprecation warnings, including from should-matchers:

![image](https://user-images.githubusercontent.com/12682792/28315504-0381579c-6bbf-11e7-88ca-5452900711db.png)

Fixnum is deprecated, Integer should be used instead.

**Comment by aaronmcadam** [comment]
It's been fixed by #1009

**Comment by bryszard** [comment]
Thanks :).
