### ISSUE TITLE
Bug in the delegate_method matcher

### ISSUE THREAD

**Issue by fxn** [thoughtbot/shoulda-matchers#1053]
## Description

I seem to have founded a bug in the `delegate_method` matcher (v3.1.1) that can be reproduced with this example (the name of things comes from a reduction to minimal example of the original situation):

```ruby
class FooRegion
  def country
    Object.new
  end
end

class Foo
  extend Forwardable

  def_delegators :region, :country
  def_delegators :country, :to_s

  def self.instance
    @i ||= new
  end

  def region
    FooRegion.new
  end
end

describe Foo do
  subject { Foo.instance }

  it { is_expected.to delegate_method(:to_s).to(:country) }
  it { is_expected.to delegate_method(:country).to(:region) }
end
```

When RSpec executes first the spec for `:country`, and then the one for `:to_s`, the suite passes. But when it takes first `:to_s`, and then `:country`, it fails:

```
$ bin/rspec --order defined spec/foo_spec.rb
1) Foo should delegate #country to #region object
   Failure/Error: it { is_expected.to delegate_method(:country).to(:region) }
     
     Expected Foo to delegate #country to #region object
     Method calls sent to Foo#region: (none)
```

## Conjecture

I have not debugged down to the last spot that proves my hunch, but I suspect it could be related to [this hash by singleton class](https://github.com/thoughtbot/shoulda-matchers/blob/2a5c312bcebf561d16577e3db57fbe111dae65df/lib/shoulda/matchers/independent/delegate_method_matcher.rb#L347). As you see, the subject is always the same object, and therefore the singleton class used as hash key the same one in both specs.

I have inspected `doubles_by_method_name` [when activating](https://github.com/thoughtbot/shoulda-matchers/blob/2a5c312bcebf561d16577e3db57fbe111dae65df/lib/shoulda/matchers/doublespeak/double_collection.rb#L21) and it grows. In the first spec it prints

```
{:country=>
  #<Shoulda::Matchers::Doublespeak::Double:0x000000133a0e68
   @activated=false,
   @calls=[],
   @implementation=
    #<Shoulda::Matchers::Doublespeak::StubImplementation:0x000000133a0ee0
     @implementation=
      #<Proc:0x000000133a0df0@/home/vagrant/.rvm/gems/ruby-2.2.5/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/doublespeak/stub_implementation.rb:20>>,
   @klass=#<Class:#<Foo:0x000000133a14d0>>,
   @method_name=:country,
   @world=
    #<Shoulda::Matchers::Doublespeak::World:0x000000133a1098
     @_double_collections_by_class=
      {#<Class:#<Foo:0x000000133a14d0>>=>
        #<Shoulda::Matchers::Doublespeak::DoubleCollection:0x000000133a0fd0
         @doubles_by_method_name={...},
         @klass=#<Class:#<Foo:0x000000133a14d0>>,
         @world=
          #<Shoulda::Matchers::Doublespeak::World:0x000000133a1098 ...>>},
     @doubles_activated=true>>}
```

and in the second spec you get

```
{:country=>
  #<Shoulda::Matchers::Doublespeak::Double:0x000000133a0e68
   @activated=false,
   @calls=
    [#<Shoulda::Matchers::Doublespeak::MethodCall {:method_name=>:country, :args=>[]}>],
   @implementation=
    #<Shoulda::Matchers::Doublespeak::StubImplementation:0x000000133a0ee0
     @implementation=
      #<Proc:0x000000133a0df0@/home/vagrant/.rvm/gems/ruby-2.2.5/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/doublespeak/stub_implementation.rb:20>>,
   @klass=#<Class:#<Foo:0x000000133a14d0>>,
   @method_name=:country,
   @world=
    #<Shoulda::Matchers::Doublespeak::World:0x000000133a1098
     @_double_collections_by_class=
      {#<Class:#<Foo:0x000000133a14d0>>=>
        #<Shoulda::Matchers::Doublespeak::DoubleCollection:0x000000133a0fd0
         @doubles_by_method_name={...},
         @klass=#<Class:#<Foo:0x000000133a14d0>>,
         @world=
          #<Shoulda::Matchers::Doublespeak::World:0x000000133a1098 ...>>},
     @_original_methods_by_class=
      {#<Class:#<Foo:0x000000133a14d0>>=>
        {:country=>#<UnboundMethod: Foo#country>}},
     @doubles_activated=true>>,
 :region=>
  #<Shoulda::Matchers::Doublespeak::Double:0x00000013204398
   @activated=false,
   @calls=[],
   @implementation=
    #<Shoulda::Matchers::Doublespeak::StubImplementation:0x00000013204410
     @implementation=
      #<Proc:0x000000132042f8@/home/vagrant/.rvm/gems/ruby-2.2.5/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/doublespeak/stub_implementation.rb:20>>,
   @klass=#<Class:#<Foo:0x000000133a14d0>>,
   @method_name=:region,
   @world=
    #<Shoulda::Matchers::Doublespeak::World:0x000000133a1098
     @_double_collections_by_class=
      {#<Class:#<Foo:0x000000133a14d0>>=>
        #<Shoulda::Matchers::Doublespeak::DoubleCollection:0x000000133a0fd0
         @doubles_by_method_name={...},
         @klass=#<Class:#<Foo:0x000000133a14d0>>,
         @world=
          #<Shoulda::Matchers::Doublespeak::World:0x000000133a1098 ...>>},
     @_original_methods_by_class=
      {#<Class:#<Foo:0x000000133a14d0>>=>
        {:country=>#<UnboundMethod: Foo#country>}},
     @doubles_activated=true>>}
```

This is just an intuition, don't know all the details and maybe that is fine, but I don't quite see why we have `:country` in the latter trace. If I understant how this works correctly, in a clean state `:country` should have no double associated in that second spec.

## Workaround

It squares with that conjecture that if the subject dups the object the failure cannot be reproduced.

**Comment by mcmire** [comment]
Hey @fxn,

Thanks for the bug report! That's super helpful. I can see how that would cause a problem, and I agree that the matcher should be getting rid of those doubles once it is finished. I will take a closer look at it when I get a chance.

**Comment by fxn** [comment]
After sleeping on it, I guessed that if the intuition is correct there must be a simpler way to reproduce the problem. Yes, this example has less stuff going on:

```ruby
class Dog
  extend Forwardable

  def_delegator :name, :length
  def_delegator :length, :abs

  def name
    "Jake"
  end
end

describe Dog do
  subject(:dog) { Dog.new }

  example do
    # To reproduce the bug, order matters.
    expect(dog).to delegate_method(:abs).to(:length)
    expect(dog).to delegate_method(:length).to(:name)
  end
end
```

And it is stronger because the expectations go together. As you said, the matcher seems to be the one having to do some cleanup.

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
