### ISSUE TITLE
rails-5 branch got rebased?

### ISSUE THREAD

**Issue by aripollak** [thoughtbot/shoulda-matchers#1056]
It looks like the rails-5 branch got rebased and force-pushed in the last few days. Could you please avoid doing that? The README recommends using the rails-5 branch, but projects' Gemfile.lock contains a specific commit hash, and rebasing invalidated a bunch of the previous commits on that branch, so `bundle install` no longer works on a fresh Ruby install without `bundle update shoulda-matchers` first.
Thanks for maintaining shoulda-matchers!

**Comment by cainlevy** [comment]
This also seems to have stripped out the merge commits that connect changes back to pull requests.

**Comment by guialbuk** [comment]
Related #1055

**Comment by mcmire** [comment]
Again, sorry for this -- that was bad judgment on my part.

I've merged `rails-5` into the master branch, so going forward we won't have a long-running branch (which I'm not a fan of anyway). That should make creating new PRs easier for folks too. I won't delete the branch, but if you switch to `master` then you should be able to stay on that.
