### ISSUE TITLE
NoMethodError: undefined method `optional'

### ISSUE THREAD

**Issue by dgorodnichy** [thoughtbot/shoulda-matchers#1069]
```
minitest (5.10.3, 5.10.1)
shoulda-matchers (3.1.2)
```

```
require "test_helper"

describe Event do
  subject { Event.new }
  it { must belong_to(:visit).optional }
end
```
=> 
```
NoMethodError: undefined method `optional' for #<Shoulda::Matchers::ActiveRecord::AssociationMatcher:0x00007f96daad39f0>
Did you mean?  options
```

How to use optional matcher in my case?

**Comment by mcmire** [comment]
@dgorodnichy Hmm, that's definitely very strange. Are you sure you're using 3.1.2? Where is `describe` coming from if you're using Minitest -- are you using Minitest::Spec?

**Comment by dgorodnichy** [comment]
@mcmire, Yes, I use Minitest::Spec. I'm sure that shoulda-matchers  version is 3.1.2

**Comment by Maychell** [comment]
Same thing here.
My class:
```Ruby
class User
  belongs_to :address, optional: true
end
```
Test:
```Ruby
RSpec.describe User, type: :model do
  context 'associations' do
    it { is_expected.to belong_to(:address).optional }
  end
end
```
Result:
```Ruby
1) User associations when it is failed
     Failure/Error: it { is_expected.to belong_to(:address).optional }

     NoMethodError:
       undefined method `optional' for #<Shoulda::Matchers::ActiveRecord::AssociationMatcher:0x007fa266945fd8>
       Did you mean?  options
```

**Comment by mcmire** [comment]
@dgorodnichy @Maychell Oh, derp -- this is only available on the master branch, this isn't in a release just yet.

**Comment by mkalygin** [comment]
@mcmire so do you suggest to use `master` branch instead of stable `3.1.2` release? I also experience this issue.

**Comment by jasonperrone** [comment]
Upvote this too.

**Comment by mcmire** [comment]
@mkalygin @jasonperrone Yes, I'd advise using the `master` branch if you really need this.

**Comment by rafaelbiriba** [comment]
Upvote!

**Comment by don-kakashi** [comment]
Upvote, waiting for the stable release :) :+1:

**Comment by vatsan28** [comment]
When do you expect to release a stable version with the optional method? 🙏

**Comment by shartep** [comment]
also waiting for this

**Comment by guialbuk** [comment]
Hi!
The `master` branch is pretty stable. Just point the Gemfile to it :)
Cheers!

**Comment by kleinjm** [comment]
is there an estimated release date for 4.0.0?

**Comment by guialbuk** [comment]
Hi @kleinjm 

We still have some open issues for `4.0.0`.

You can follow the progress and find issues to contribute for the next verion at:
https://github.com/thoughtbot/shoulda-matchers/milestone/13
