### ISSUE TITLE
Primary key/primary key association options not validated?

### ISSUE THREAD

**Issue by iainbeeston** [thoughtbot/shoulda-matchers#1071]
I think I've found a scenario where shoulda matchers' association matchers pass when they should actually be failing.

BACKGROUND
-----------

I have a passing activerecord spec like this:

```ruby
RSpec.describe Romeo do
  it { is_expected.to have_many(:sierras).with_primary_key(:external_id).with_foreign_key(:sierra_external_id) }
end
```

Here's my model:

```ruby
class Romeo < ApplicationRecord
  has_many :sierras, primary_key: :external_id, foreign_key: :sierra_external_id
end
```

And here is a snippet from my schema.rb:

```ruby
  create_table "romeos" do |t|
    t.integer "sierra_external_id"
  end

  create_table "sierras" do |t|
    t.integer "external_id"
  end
```

So the idea here is that my association will give me all the `Sierra` models whose `external_id` matches the `sierra_external_id` on my `Romeo`.

ISSUE
-----

**However**, my assocation is defined incorrectly, as I've gotten the primary key and foreign key the wrong way around, and if I actually call `Romeo#sierras` I get an error:

```
irb(main):003:0> r = Romeo.create(sierra_external_id: 1)
=> #<Romeo id: 1, sierra_external_id: 1, created_at: "2018-01-15 11:21:26", updated_at: "2018-01-15 11:21:26">
irb(main):004:0> r.sierras
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: sierras.sierra_external_id: SELECT  "sierras".* FROM "sierras" WHERE "sierras"."sierra_external_id" IS NULL LIMIT ?
```

But despite this the shoulda spec passes.

What's more, if I simplify my spec a little to this:

```ruby
RSpec.describe Romeo do
  it { is_expected.to have_many(:sierras)
end
```

Then it does fail (as I'd have expected):

```
Failures:

  1) Romeo should have many sierras
     Failure/Error: it { is_expected.to have_many(:sierras) }
       Expected Romeo to have a has_many association called sierras (Sierra does not have a sierra_external_id foreign key.)
     # ./spec/models/romeo_spec.rb:5:in `block (2 levels) in <top (required)>'

Finished in 0.02076 seconds (files took 1.73 seconds to load)
```

CONCLUSION
------

This _seems_ like a bug? The interesting parts for me are that:

1. It seems like shoulda doesn't validate the columns passed to `with_primary_key` and `with_foreign_key` exist on the appropriate models?
2. It seems that some checks are being skipped when those extra options are passed?

To make it easier to diagnose, I've reproduced in a test app:

https://github.com/iainbeeston/shoulda-test-app

I've reproduced the spec errors on circleci here:

https://circleci.com/gh/iainbeeston/shoulda-test-app

**Comment by mcmire** [comment]
Hey @iainbeeston. Yeah, the `have_many` matcher doesn't do a whole lot when it comes to testing the primary and foreign key options. All it does it check the options that the association was defined with. It's a little hard to tell, but you can kinda see that here:

https://github.com/thoughtbot/shoulda-matchers/blob/2a61824ef941fe50cc50cec602f4a48797ca55ab/lib/shoulda/matchers/active_record/association_matcher.rb#L1295-L1319

To make this a better matcher, I agree that it would be great if it actually checked that those columns existed on the model. Going further than that, however, may be a little harder. How do you test whether an association is valid when defined with a particular primary key or foreign key? So I wonder if it would be easier for the matcher just to call the association and check for an ActiveRecord::StatementInvalid error and then report that to the user with some kind of generic error message like, "Your association :sierras produced an invalid query. You may want to double check its definition in Romeo." or something like that. What do you think about that?

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
