### ISSUE TITLE
validates_uniqueness_of doesn't work correctly on integer columns

### ISSUE THREAD

**Issue by edwardmp** [thoughtbot/shoulda-matchers#1081]
Hi,

I love this gem and recently needed something that isn't released yet, so I felt a bit adventurous and tried out what's in the master branch.

I encounter one specific issue. If you have a `validates_uniqueness_of` matcher on an Integer-backed column I receive an `undefined method length for 0:Integer` error. 

Diving into the code a bit, I notice that in the [`arbitrary_non_blank_value`](https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb#L520) method the value of `non_blank value` would equal `0` for a Integer column. An integer column typically has a limit of 4 (bytes), but this code somehow assumes that if there is a limit, `non_blank_value` responds to the `length` method as well, which of course is not the case for an Integer value like `0`.

I believe this issue may have been introduced by this commit: https://github.com/thoughtbot/shoulda-matchers/commit/9103ead2147b012dabf7fdf9c68b9995d24697ae. Before this change `non_blank value` always defaulted to a hardcoded string, but after the change it can be other types than a string.

A fix could check if `non_blank` responds to `length`, but that probably isn't an proper fix.
I guess that basically the code in the if statement is only relevant for `String` type columns, thus we should probably check if `non_blank_value` is a string or not. If someone can confirm if that is what's intended then I can submit a PR fixing this.

Example fix:
```ruby
if non_blank_value.is_a?(String) && limit && limit < non_blank_value.length
    'x' * limit
else
    non_blank_value
end
```

**Comment by mcmire** [comment]
Hey @edwardmp. Yes, it looks like that was an oversight on my part -- I didn't think about numeric columns having lengths, too. Good work tracking this down! Your fix makes sense. It looks like we're missing a test, too -- otherwise this wouldn't have slipped through! If you could try your hand at that when you submit the PR, it would be much appreciated. :)

**Comment by edwardmp** [comment]
Hi @mcmire, thanks for the quick reply. I'll try to create a PR for the fix and a test in the comings days.

**Comment by edwardmp** [comment]
Hey @mcmire, I submitted a PR fixing this. Please let me know if you have any feedback!

**Comment by edwardmp** [comment]
Hi @mcmire, did you have any chance to review my PR? Thanks!
