### ISSUE TITLE
validate_numericality_of on a derived value gives AttributeDoesNotExistError

### ISSUE THREAD

**Issue by michaelvasallo** [thoughtbot/shoulda-matchers#1086]
I have a many-to-many relationship with Cards and Decks and a quantity column on the CardsDecks join table. I have a validation set up on my Deck model to validate the card_count to equal 40.
```ruby
class Deck < ApplicationRecord
  has_many :cards_decks, dependent: :destroy
  has_many :cards, through: :cards_decks

  validates :card_count, numericality: { equal_to: 40 }

  def card_count
    cards_decks.sum(&:quantity)
  end
end
```
I would expect `it { should validate_numericality_of(:card_count).is_equal_to(40) }` to pass but I get this error:
```
1) Deck validations should validate that :card_count looks like a number equal to 40
     Failure/Error: it { should validate_numericality_of(:card_count).is_equal_to(40) }

     Shoulda::Matchers::ActiveModel::AllowValueMatcher::AttributeDoesNotExistError:
       The matcher attempted to set :card_count on the Deck to "39", but that
       attribute does not exist.
```
Is there a way to make this matcher work with derived values?

**Comment by mcmire** [comment]
@michaelvasallo The matcher is giving you this error because it needs some way of setting the attribute that's been given to it (in order to check different test cases). In your case, you just have a reader, so there's no way to change the return value of `card_count`. You may need to simply write this test manually.

**Comment by michaelvasallo** [comment]
@mcmire Thanks for the response! I can close this issue.

It doesn't apply in this case, but theoretically if I did set up a writer method for a derived value, this matcher would work?
