### ISSUE TITLE
Overriding text of description "should"

### ISSUE THREAD

**Issue by marcioJesus** [thoughtbot/shoulda-matchers#1088]
Hi, 

I be using the 'validate_presence_of' as below:
`` 
it { is_expected.to validate_presence_of(:program) }
``

and when runed test  the return is:

> should validate that :program cannot be empty/falsy

I whould like modify the term 'should' to 'expect'

How do it?

Thanks,

**Comment by mcmire** [comment]
This is built into RSpec and as such we have no way of changing this, sorry :)

**Comment by marcioJesus** [comment]
Ok, that's why I closed this question.

But, thanks for answer =]
