### ISSUE TITLE
Undefined method `with_values' for #<Shoulda::Matchers::ActiveRecord::DefineEnumForMatcher:xxxxx>

### ISSUE THREAD

**Issue by thesubr00t** [thoughtbot/shoulda-matchers#1093]
Rails 5.1.6

Gemfile :
```ruby
group :test do
  gem 'shoulda-matchers'
end
```
spec/rails_helper :
```ruby
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :rails
  end
end
```

spec file :
```ruby
require 'rails_helper'

RSpec.describe Thing, type: :model do
  it do
    should define_enum_for(:status)
      .with_values(%i[up down])
  end
end
```
Running `rspec` fails with the following message :
```
Failure/Error:
       should define_enum_for(:status)
         .with_values(%i[up down])
     
     NoMethodError:
       undefined method `with_values' for #<Shoulda::Matchers::ActiveRecord::DefineEnumForMatcher:0x000000047b6408>
```

Thanks

**Comment by santiagodoldan** [comment]
@thesubr00t I had the same issue, looks like they changed the API of the enum matcher, I'm using `3.1.2`, here you have the implementation https://github.com/thoughtbot/shoulda-matchers/blob/v3.1.2/lib/shoulda/matchers/active_record/define_enum_for_matcher.rb, there's no `with_values`, you should use `with`.

**Comment by mcmire** [comment]
Correct -- `with_values` is new in `master`, but as of 3.1.2 it's still `with`.

**Comment by mcmire** [comment]
I'm going to close this since we'll be releasing 4.0.0 soon.
