### ISSUE TITLE
Proper release versions

### ISSUE THREAD

**Issue by aliuk2012** [thoughtbot/shoulda-matchers#1105]
Please could someone update the releases for this project? 
Rubygems and github releases are still only reporting 3.1.2 (https://github.com/thoughtbot/shoulda-matchers/releases) as of 12 July 2017 and master has 113 commits since that release.

I realise that you are working on v.4 but could you perhaps do a v.4 alpha/beta release?

**Comment by guialbuk** [comment]
Hi @aliuk2012 .
Nice to know that you are are actively using the gem. Version 4.0 will be released very soon.
I kindly suggest you point your Gemfile to the master branch in order to benefit from the new features and improvements.
Cheers!

**Comment by aliuk2012** [comment]
Hi @guialbuk,

Thanks for the quick response and for the update. I have for the time being pointed my Gemfile to the master branch. 

👍
