### ISSUE TITLE
Gem "normalizr" cause CouldNotSetAttributeError on downcased email attribute 

### ISSUE THREAD

**Issue by aya-soft** [thoughtbot/shoulda-matchers#1107]
Hi, guys!

Given: [https://github.com/dimko/normalizr](https://github.com/dimko/normalizr)
```
class User
  normalize :email, with: :strip_downcase
end
```
Spec:
`it { is_expected.to validate_uniqueness_of(:email).with_message('an account with this email address already exists').case_insensitive }`
Error:
```
  1) User Validations Email validations should require unique value for email
     Failure/Error: it { is_expected.to validate_uniqueness_of(:email).with_message('an account with this email address already exists').case_insensitive }
     
     Shoulda::Matchers::ActiveModel::AllowValueMatcher::CouldNotSetAttributeError:
       The allow_value matcher attempted to set :email on User to "A", but
       when the attribute was read back, it had stored "a" instead.
```
Guys, what is the right way to test attributes which values can be changed on the fly?
With this line commented all works fine (allow_value_matcher.rb):
\# ensure_that_attribute_was_set!(value)

**Comment by mcmire** [comment]
@aya-soft Try tacking `.ignoring_case_insensitivity` onto the end of the matcher instead of `.case_insensitive`. See: http://matchers.shoulda.io/docs/v3.1.1/Shoulda/Matchers/ActiveRecord.html#validate_uniqueness_of-instance_method (you might have to scroll down a bit).

**Comment by aya-soft** [comment]
Works with .ignoring_case_sensitivity, thank you! Please correct the typo.

**Comment by mcmire** [comment]
@aya-soft Oops, that's what I meant :)
