### ISSUE TITLE
Slow specs when using validates_presence_of

### ISSUE THREAD

**Issue by joshuasager** [thoughtbot/shoulda-matchers#1112]
Class:
```
class Thing < ApplicationRecord
      validates :stuff, presence: true
end
```

Spec: 
```
require 'rails_helper'

RSpec.describe Thing, type: :model do
      it { should validate_presence_of :stuff }
end
```

rails_helper:
```
require 'spec_helper'
require 'shoulda/matchers'

Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :active_model
    with.library :active_record
  end
end
```

Spec is taking ~600ms to run.

Has anyone experienced an issue similar to this ?

**Comment by mcmire** [comment]
Hmm. What gems do you have in your Gemfile? Anything significant?

**Comment by joshuasager** [comment]
Nothing significant. Standard rails 5 gems that come pre-packaged when installing in API-mode.

Some additions include:

```
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Use Redis adapter to run sidekiq, as well as access global SE caches
gem 'redis', '~> 4.0'
# Password generation
gem 'pbkdf2-ruby'
# Logging
gem 'lograge'
# Mixpanel
gem 'mixpanel-ruby'
# Verify JWTs
gem 'jwt'
# Better http requests
gem 'http'
# Creates code coverage reports
gem 'simplecov'
# Creates documentation
gem 'yard', '~> 0.9.14'
```

**Comment by mcmire** [comment]
Hmm, okay. Some other questions I would ask:

* Are there are other matchers that exhibit this same problem?
* I don't see the environment loaded in your rails_helper, but did you exclude that for brevity?
* What happens if you remove all of the gems?
* The gem relies `activesupport`, and obviously this is a big library, so perhaps that's all this is?

**Comment by joshuasager** [comment]
1. Havent tried that yet. Most of these gems do not interact with rspec - I do not foresee negative impact on the speed of these tests. Ill test to confirm.
2. Excluded for brevity
3. Will try and report back.

**Comment by joshuasager** [comment]
Note: Only the first spec with:
```
should validate_presence_of ____
```

is slow. Sequential shoulda-matchers are quite fast.

**Comment by mcmire** [comment]
Hey @joshuasager -- I'm going to close this as I've never had issues with specs running slowly and I'm not really sure how to solve this problem. If you figure out a solution though I'm all ears!
