### ISSUE TITLE
Handling of ActiveRecord enum in validate_inclusion_of matcher

### ISSUE THREAD

**Issue by BuonOmo** [thoughtbot/shoulda-matchers#1121]
The next portion of code:

```ruby
class MyObject < ActiveRecord::Base
  enum light: { on: "on", off: "off" }
  validates :direction, inclusion: { in: lights.keys }
end


describe MyObject do
  it { should validate_inclusion_of(:light).in_array(%w(on off)) }
end
```

Throws this issue:

>      Failure/Error: it { should validate_inclusion_of(:light).in_array(%w(on off)) }
>     ArgumentError:
>       'shouldamatchersteststring' is not a valid light

My guess would be that the error thrown by ActiveRecord enum when string is set is not catched.

**Comment by guialbuk** [comment]
The error displays `validate_inclusion_of(:light)` but the code is ` validate_inclusion_of(:direction)`

Could you check if the code that you are running is checking for inclusion_on `:direction` or `:light`?

**Comment by BuonOmo** [comment]
It is a typo in writing, I simplified the example. There is no typo in the original 🙂

**Comment by guialbuk** [comment]
Hi @BuonOmo 

The is a specific matcher for enums: 

`it { should define_enum_for(:light).with(%w(on off)) }`

http://matchers.shoulda.io/docs/v3.1.1/Shoulda/Matchers/ActiveRecord.html#define_enum_for-instance_method

**Comment by BuonOmo** [comment]
Of course there is… Thank you!
