### ISSUE TITLE
have_secure_token matcher not working

### ISSUE THREAD

**Issue by georgecheng** [thoughtbot/shoulda-matchers#1131]
**Rspec 3.7.1
Rails 5.2.1
Ruby 2.5.1
Shoulda-matcher 3.1.2**

When using the `have_secure_token` matcher, e.g. `it { should have_secure_token }`, I'm getting the error `expected #<Model:0x0000...> to respond to 'has_secure_token?'`. I've been unable to determine the source of this error. Other matchers seem to work fine.

**Comment by mcmire** [comment]
It sounds like the ActiveRecord matchers aren't getting mixed into your example group properly. Can you provide a more complete example? Also, are you configuring the gem using `Shoulda::Matchers.configure`?

**Comment by georgecheng** [comment]
In my `rails_helper.rb`, I have

```
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :rails
  end
end
```

And in my spec I just have

```
require 'rails_helper'

RSpec.describe Account, type: :model do
  it { should have_secure_token }
  it { should belong_to(:user) }
  it { should accept_nested_attributes_for(:user) }
end
```

and getting this error

```
expected #<Account:0x00007fb8c77ac4e8> to respond to `has_secure_token?`

  0) Account should have secure token
     Failure/Error: it { should have_secure_token }
       expected #<Account:0x00007fb8c77ac4e8> to respond to `has_secure_token?`
     # ./spec/models/account_spec.rb:4:in `block (2 levels) in <top (required)>'

3 examples, 1 failure, 2 passed
```

The other specs are passing... 😕

**Comment by mcmire** [comment]
Ah. I forgot -- this doesn't exist in 3.1.2, it exists in `master` only right now. (We're working on issuing a new release very soon.)

**Comment by georgecheng** [comment]
Ah... okay, got it. That explains it then. I made the mistake of not looking at the 3.1.2 repo to see if the matcher was there. I only saw that a PR was made last year for this.

Thanks for looking into it.
