### ISSUE TITLE
with_values method is not working??

### ISSUE THREAD

**Issue by kamille-321** [thoughtbot/shoulda-matchers#1152]
hi, I'm trying to using `with_values` method for testing enum keys, but got a error that indicate `with_values` is undefined for `Shoulda::Matchers::ActiveRecord::DefineEnumForMatcher`

Let me know if my code is wrong syntax or the method is already closed.
my code is below

```
# model
class Hoge
  enum status: { waiting: 0, success: 1, error: 2 }
end

# spec test 
...
...
it { is_expected.to define_enum_for(:status).with_values([:waiting, :success, :error]) }

# error
 NoMethodError:
       undefined method `with_values' for #<Shoulda::Matchers::ActiveRecord::DefineEnumForMatcher:0x00007fa203bffe08>
```

**Comment by mcmire** [comment]
@kamille-321 You can! Try replacing this in your Gemfile:

``` ruby
gem 'shoulda-matchers'
```

with this:

``` ruby
gem 'shoulda-matchers', '4.0.0.rc.1'
```

**Comment by kamille-321** [comment]
@mcmire Thanks!! Can I close this issue??

**Comment by mcmire** [comment]
@kamille-321 Yup, go ahead :)
