### ISSUE TITLE
Support type-casted serialized attributes in validates_numericality_of

### ISSUE THREAD

**Issue by drn** [thoughtbot/shoulda-matchers#1155]
Hi there,

We were trying to get shoulda-matchers work with type-casted virtual attributes (basically use the numeric column attribute behavior for virtual attributes). Our team uses [ActiveRecord::Store](https://api.rubyonrails.org/classes/ActiveRecord/Store.html) for a couple STI models. We type-cast these virtual attributes using the `ActiveModel::Type::*.cast(...)` helpers to match the behavior of a standard db column. We add standard rails validations to these. We'd like to be able to leverage shoulda-matchers, but we run into errors that look like:

```       Program::Earn::Loyalty::Visit did not properly validate that :minimum
       looks like a number greater than 0.
         After setting :minimum to ‹"abcd"› -- which was read back as ‹0.0› --
         the matcher expected the Program::Earn::Loyalty::Visit to be invalid
         and to produce the validation error "is not a number" on :minimum. The
         record was indeed invalid, but it produced these validation errors
         instead:

         * minimum: ["must be greater than 0"]

         As indicated in the message above, :minimum seems to be changing
         certain values as they are set, and this could have something to do
         with why this test is failing. If you've overridden the writer method
         for this attribute, then you may need to change it to make this test
         pass, or do something else entirely.
```

Example:
```ruby
# create_table :examples do |t|
#   t.integer :column_value
#   t.integer :settings
#   ...
# end
class Example < ActiveRecord::Base
  store :settings, coder: JSON
  store_accessor :settings, :serialized_value

  validate :column_value, numericality: { only_integer: true, greater_than: 10 }
  validate :serialized_value, numericality: { only_integer: true, greater_than: 10 }

  def serialized_value=(value)
    super(ActiveModel::Type::Integer.cast(value))
  end
end

# Matchers:

it { should validate_numericality_of(:column_value) } # works!
it { should validate_numericality_of(:serialized_value) } # does not work
```

Is there a way to bypass the default virtual attribute behavior and use the db-backed numeric column behavior for these values?

I'm happy to contribute to this if it is not possible, but after digging into the codebase for a bit, I couldn't figure out how to do this. I tried adding various forms of `ignoring_interference_by_writer` but that didn't do me any good :)

Thanks!

**Comment by mcmire** [comment]
This is a known issue with the numericality matcher, and I thought perhaps I'd handled it already, but I haven't yet. There are numerous references to this in past issues, but all of them seem to have been closed, so I'll just leave this open. Unfortunately there's not a simple way to get around this right now; you may have to write some tests by hand.

**Comment by drn** [comment]
I see, thanks for the info @mcmire. I'm happy to help implement a solution if you point me to the right place. Cheers~

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
