### ISSUE TITLE
validate_presence_of MongoID localize field false positive.

### ISSUE THREAD

**Issue by Cakirucho** [thoughtbot/shoulda-matchers#1161]
Hello, i'm building a new Rails App with **MongoID 7.0 and Rails 5**.

Right now i'm starting to use `localize` fields, that allow model to store localized String in that field, for example:

`field :name, type: String, localize: true`, if we save this field with a default language of `english`, this will save a Hash like --> `{en: "Orc"}`. But it will use it as an String.

So when i add `validate_presence_of :name` and do a test like that:

```ruby
describe '#race' do
    it { is_expected.to validate_presence_of(:race) }
end
```

It fails with the next message:

```
Expected PlayerType to validate that :race cannot be empty/falsy, but
this could not be proved.
         After setting :race to ‹nil›, the matcher expected the PlayerType to
         be invalid and to produce the validation error "can't be blank" on
         :race. The record was indeed invalid, but it produced these validation
         errors instead:
     
         * race: ["can't be blank in en"]
         * role: ["is too short (minimum is 3 characters)"]

```

So it seems that MongoID throws another message for localize validations. I'm not sure how to solve this, just telling you guys in case you do not know this. 

Thx for the great job doing this gem.

**Comment by guialbuk** [comment]
Hi @Cakirucho 

shoulda-matchers has no support for Mongoid.

But the good news is that there is a similar gem for Mongoid: https://github.com/mongoid/mongoid-rspec

Cheers!
