### ISSUE TITLE
Asserting enum values from a hash fails in 4.0.0

### ISSUE THREAD

**Issue by Drenmi** [thoughtbot/shoulda-matchers#1178]
Just encountered this after upgrading today. Not sure if I'm missing something obvious, but the error message isn't very helpful ... 😅 

#### Model

```ruby
enum status: { pending: 0, running: 1, done: 6 }.freeze
```

#### Test

```ruby
it { is_expected.to define_enum_for(:status).with_values(%w[pending running done]) }
```

*(Note that an array of symbols also results in a failing test, but with a slightly different message.)*

### Expected Behaviour

Tests pass.

### Actual Behaviour

> Expected Job to define :status as an enum, backed by an
>       integer, with possible values ‹["pending", "running", "done"]›. However,
>       the actual enum values for :status are ‹["pending", "running", "done"]›.

### Things I've Tried

All possible combinations of string- and symbol keys.

### Additional Information

Ruby 2.6.1
Rails 5.2.0
shoulda-matchers 4.0.0

**Comment by Drenmi** [comment]
I was able to make this test pass by changing the matcher to use a hash:

```ruby
it { is_expected.to define_enum_for(:status).with_values(pending: 0, running: 1, done: 6) }
```

So perhaps this is intended behaviour? Although the new method name `#with_values` and the error output are probably a bit misleading.

**Comment by mcmire** [comment]
@Drenmi I glanced at your issue today and couldn't quite figure out why you were getting that issue, but your update makes more sense now — what you pass to `with_values` has to match how you defined the `enum`. I agree that the error is misleading. What do you think about this message instead?

> Expected Job to define :status as an enum, mapping 0 to ‹"pending"›, 1 to ‹"running"›, and 2 to ‹"done"›. However, :status actually maps 0 to ‹"pending"›, 1 to ‹"running"›, and 6 to ‹"done"›.

**Comment by Drenmi** [comment]
>What do you think about this message instead?
> > Expected Job to define :status as an enum, mapping 0 to ‹"pending"›, 1 to ‹"running"›, and 2 to 
‹"done"›. However, :status actually maps 0 to ‹"pending"›, 1 to ‹"running"›, and 6 to ‹"done"›.

With this message, I would have been able to figure it out pretty much right away. 🙂

**Comment by mcmire** [comment]
@Drenmi Haha, perfect. I will fix this shortly. I'll leave this issue open in the meantime.

**Comment by mcmire** [comment]
Fixed!

**Comment by Drenmi** [comment]
Thanks @mcmire! 🥇
