### ISSUE TITLE
gemspec problem makes boilerplate files globally executable

### ISSUE THREAD

**Issue by MadBomber** [thoughtbot/shoulda-matchers#1179]
The bin directory only contains common boilerplate files.  The gemspec file those common boilerplate files in the bin directory globally executable.  Delete the line in the gemspec that makes everything in the bin directory globally executable.

Delete this line:
 s.executables = `git ls-files -- bin/*`.split("\n").map{ |f| File.basename(f) }

**Comment by mcmire** [comment]
Hey! Thanks for bringing this to our attention. You are 100% right and I am super embarrassed by this. I just opened #1180 to fix this. As soon as the tests pass I'll merge it and issue another release.

**Comment by mcmire** [comment]
I've released 4.0.1 with a correct gemspec. I've also yanked 4.0.0 so that hopefully this doesn't happen for anyone else.
