### ISSUE TITLE
Review of PR 1180

### ISSUE THREAD

**Issue by n-rodriguez** [thoughtbot/shoulda-matchers#1181]
Hi there!

I review the https://github.com/thoughtbot/shoulda-matchers/pull/1180 : I don't know if doing a `chdir` is a good thing here. If you wanted to remove `setup` you could have removed the `executables` method call.
See Sidekiq for example : https://github.com/mperham/sidekiq/pull/4023

**Comment by mcmire** [comment]
Hey, in making those changes I took a look at what Bundler is now doing whenever it generates gems and decided to borrow from that: https://github.com/bundler/bundler/blob/master/lib/bundler/templates/newgem/newgem.gemspec.tt. Are you having issues with this now?

**Comment by mcmire** [comment]
Left a comment on your PR :)
