### ISSUE TITLE
Document how to match a multi-column index with have_db_index

### ISSUE THREAD

**Issue by connorshea** [thoughtbot/shoulda-matchers#1196]
e.g. I have a migration like this:

```ruby
class AddUniqueIndexToGamePlatforms < ActiveRecord::Migration[5.2]
  def change
    add_index :game_platforms, [:game_id, :platform_id], unique: true
  end
end
```

And I have a matcher like this:

```ruby
it { should have_db_index([:game_id, :platform_id]).unique }
```

Currently, the documentation doesn't mention the ability to pass an array to the `have_db_index` matcher. It'd be nice if it did :)

https://github.com/thoughtbot/shoulda-matchers/blob/3635df70546f58152f1dc278f4385007f9903914/lib/shoulda/matchers/active_record/have_db_index_matcher.rb#L4-L26

**Comment by rodrigovirgilio** [comment]
I created the PR, would that be it? https://github.com/thoughtbot/shoulda-matchers/pull/1197

**Comment by connorshea** [comment]
This is resolved now, thanks! :)
