### ISSUE TITLE
The association should have been defined with `optional: true`, but was not

### ISSUE THREAD

**Issue by s4kharitonov** [thoughtbot/shoulda-matchers#1206]
Hello, I get the error specified in the title, looked at similar problems and unfortunately didn't find a solution. Could you help me maybe I missed something?

**rails 5.2.1**
**shoulda-matchers 4.0.0.rc1**

Model:
```
belongs_to :list_option, optional: true
validates :list_option
```

Spec:
```
RSpec.describe SenderProfile, type: :model do
  describe '#Associations' do
    it { should belong_to(:list_option).optional }
  end
```

**Error**

> SenderProfile#Associations should belong to list_option optional: true
> 
> Failure/Error: it { should belong_to(:list_option).optional }
> 
> Expected SenderProfile to have a belongs_to association called list_option (the association should have been defined with `optional: true`, but was not)
>

**If set to** 
it { should belong_to(:list_option).without_validating_presence
> SenderProfile#Associations 
> 
> Failure/Error: it { should belong_to(:list_option).without_validating_presence }
> 
> NoMethodError:
> 
> undefined method `without_validating_presence' for #<Shoulda::Matchers::ActiveRecord::AssociationMatcher:0x000055c21f0ea3a8>

**Comment by mcmire** [comment]
Looks like you're on an old version. Try upgrading to 4.0.1 and seeing if that helps.

**Comment by s4kharitonov** [comment]
It worked, thanks for the quick reply

**Comment by mcmire** [comment]
No problem!
