### ISSUE TITLE
validate_presence_of throws ActiveRecord::SerializationTypeMismatch if attribute is serialized to an array

### ISSUE THREAD

**Issue by stefanahman** [thoughtbot/shoulda-matchers#1220]
This become a problem with https://github.com/thoughtbot/shoulda-matchers/releases/tag/v4.1.0

```ruby
class Klass < ApplicationRecord
  serialize :arrays, Array
  validates :arrays, presence: true
end

# assertion
it { is_expected.to validate_presence_of(:arrays) }
```

This throws:
```
ActiveRecord::SerializationTypeMismatch:
  can't serialize `arrays`: was supposed to be a Array, but was a String. -- ""
```

**Comment by stefanahman** [comment]
Similar to https://github.com/thoughtbot/shoulda-matchers/issues/643

**Comment by mcmire** [comment]
@stefanahman Hey! I merged in a PR that should fix this issue. Do you mind switching to master temporarily and see if it fixes your test?

**Comment by stefanahman** [comment]
> @stefanahman Hey! I merged in a PR that should fix this issue. Do you mind switching to master temporarily and see if it fixes your test?

This works fantastically!

**Comment by dannyfallon** [comment]
@mcmire I just bumped into this myself when upgrading from 3.x to 4.1 - are there any plans to cut a new release? 🤞
