### ISSUE TITLE
Updating to Rails 6 seems to changes belong_to behavior

### ISSUE THREAD

**Issue by dompham** [thoughtbot/shoulda-matchers#1246]
Using Rails 5, we had the test below *not* instantiating an instance to check the association.

`it { is_expected.to belong_to(:some_class)`

After updating to Rail 6, this spec fails because the same line tries to instantiate and run the class's validation (which at the moment will give nil errors as it's missing instantiation parameters).  The 2 solutions we came up with were:
- Use a factory to give it an instance with proper parameters to check associations.
- Use `without_validating_presence` which seems to work, but I'm confused as to why.  The docs say that this just skips validating the presence of the belongs_to class, not all validations.

Any ideas why updating Rails would cause a change in this behavior?

**Comment by mcmire** [comment]
@dompham Sorry I was on vacation! Did you figure this out? When you upgraded Rails, did you change any of the initializers? ActiveRecord has a setting, `belongs_to_required_by_default`, which governs whether `belongs_to` associations will add a presence validation automatically, and the matcher picks up on this setting as well. Did this change by chance?

**Comment by dompham** [comment]
@mcmire I did figure this out - pretty much exactly what you said :). Thanks!
