### ISSUE TITLE
Add `have_rich_text`

### ISSUE THREAD

**Issue by VSPPedro** [thoughtbot/shoulda-matchers#1252]
Hello, first of all, thank you all for maintaining and improving this gem.

So, I was wondering if there it's a possibility to add something like this:

```
it { is_expected.to have_rich_text(:body) }
```

To test ActionText with RSpec. Example:

```
class Post < ApplicationRecord
  has_rich_text :body
end
```

I would love to work on this if by chance this suggestion is accepted.

Thank you for your time.

EDIT: For now I'm using a custom matcher:

```
RSpec::Matchers.define :have_rich_text do |expected|
  match do |actual|
    actual.send(expected).class == ActionText::RichText
  end
end
```

**Comment by guialbuk** [comment]
Hi @VSPPedro 

Your contribution would be appreciated. Feel free to submit a PR, or even a draft one to receive feedback during your progress.

And feel free to ask any questions 🙂

**Comment by VSPPedro** [comment]
Hi, @guialbuk

Can I ask you a question, please? 

So I started to study this project and now I'm wondering if I should create a file named `have_rich_text.rb` or if I should  add this logic inside the `association_matcher.rb`?

**Comment by VSPPedro** [comment]
I'll close this issue because the PR with the solution was merged! :tada:

**Comment by O330oei** [comment]
🤪😎🤪

Sent Samsung S8 Droid
________________________________
