### ISSUE TITLE
Intermittent test failures

### ISSUE THREAD

**Issue by mcmire** [thoughtbot/shoulda-matchers#1262]
This issue exists to collect the intermittent failures that sometimes pop up on Travis.

* [`missing attribute: :scope1`](https://travis-ci.org/thoughtbot/shoulda-matchers/jobs/614520348)

**Comment by VSPPedro** [comment]
The link within the description of this issue shows no errors, but I think I found one that shows:

- [missing attribute: :scope1](https://travis-ci.org/thoughtbot/shoulda-matchers/jobs/622356910)

**Comment by VSPPedro** [comment]
Hi, @mcmire, would you mind if I submit a draft with only comments just to take notes.

For now I didn't found any solution for this. What I know is that one test is influencing the record of another. I managed to isolate the smallest possible scenario, but I still don't understand what is the cause of the failure.

I'll keep digging. :smile:

**Comment by mcmire** [comment]
@VSPPedro Yeah that's fine with me! Thank you so much for looking into this!

**Comment by mcmire** [comment]
Closing since this is in master now.
