### ISSUE TITLE
Test erroneously complaining about optional: true

### ISSUE THREAD

**Issue by jasonperrone** [thoughtbot/shoulda-matchers#1265]
Shoulda version: 4.0.0.rc1
Shoulda-context version: 2.0.0.rc2
Shoulda-matchers version: 4.1.2

So check this out. Here is my model:

```
class Event
  belongs_to :facility, optional: true
end
```

and my test has this:

```
should belong_to(:facility).optional
```

and yet I get this:
Failure:
EventTest#test_: Event should belong to facility optional: true.  [/home/jason/.rvm/gems/ruby-2.6.5@actioncue/gems/shoulda-context-2.0.0.rc2/lib/shoulda/context/context.rb:62]:
Expected Event to have a belongs_to association called facility (and for the record not to fail validation if :facility is unset; i.e., either the association should have been defined with `optional: true`, or there should not be a presence validation on :facility)

And this same matcher works fine in other models.

**Comment by jasonperrone** [comment]
Ok I figured it out and I learned something that might be useful to others who don't understand why they're getting this message. If you define a belongs_to as optional: true, be on the lookout for any validation callbacks which essentially make it not optional. A good example would be your callback referring to the optional relationship. In my example above, I didn't notice I had defined a validation callback which actually did check to make sure facility was present. Other times you may get an error if you refer to methods on the optional entity. In my example again, it would be like having a validation callback that contained a statement such as "facility.my_custom_method".

The solution is to add without_validating_presence to the belong_to test. In my case:

```
should belong_to(:facility).without_validating_presence
```

**Comment by mcmire** [comment]
Thanks for the tips, @jasonperrone. People seem to keep getting hung up on how this matcher works under the hood, so I wonder if we need to tweak the failure message to guide people better? WDYT?

**Comment by jasonperrone** [comment]
The message does point out "there should not be a presence validation on :facility", so maybe in parenthesis it could say "see: without_validating_presence option".
