### ISSUE TITLE
Add option to pass model manually, without RSpec.describe

### ISSUE THREAD

**Issue by EdOverride** [thoughtbot/shoulda-matchers#1280]
I think it would be a nice addition to be able to pass model manually to each validator, for example:

```ruby
should accept_nested_attributes_for(:images, model: User)
```

The reason being, that if you don't directly test models, but let's say a gem, that adds associations to different models. 

So it's possible to do:
```ruby
# spec/gem_name/mounter_spec.rb
describe 'GemName' do
  describe 'Mounter' do
  
    it 'should add nested attributes do models'

    it 'other tests'

  end
end
```

Instead of, what is forced now, to:
```ruby
# spec/gem_name/mounter_spec.rb
describe 'GemName' do
  describe 'Mounter' do
  
    it 'other tests'

  end
end

RSpec.describe User, type: :model do
  it 'should add nested attributes do User'
end

RSpec.describe Post, type: :model do
  it 'should add nested attributes do Post'
end
```

**Comment by mcmire** [comment]
`should` is a shortcut for `is_expected.to`, which is a shortcut for `expect(subject).to`. In other words, you don't pass the model through the matcher, but through the argument passed to `expect`. So you are free to pass whatever you want in that slot (just as long as it's an instance of a model, not the model itself — that's how most of these matchers work). In your case, you could say:

``` ruby
expect(User.new).to accept_nested_attributes_for(:images)
```

Hope that helps.

**Comment by mcmire** [comment]
Going to close this but let me know if you have any more questions!
