### ISSUE TITLE
have_db_column.().with_options() should raise error on misspelled argument

### ISSUE THREAD

**Issue by recurator** [thoughtbot/shoulda-matchers#1281]
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
Rails 6.0.0
RSpec 3.8
  - rspec-core 3.8.2
  - rspec-expectations 3.8.4
  - rspec-mocks 3.8.1
  - rspec-rails 3.8.2
  - rspec-support 3.8.2
shoulda-matchers (4.1.2)

spec/models/comment_spec.rb:
```
require 'rails_helper'
RSpec.describe Comment, type: :model do
  it { is_expected.to have_db_column(:created_at).of_type(:datetime).with_options(preccision: 6, null: false)
end
```

*** Note spelling error: preccision

It is expected to raise error but no error is raised.

**Comment by mcmire** [comment]
Closing this since #1358 was merged.
