### ISSUE TITLE
User Uniqueness Test Failing: "undefined method `downcase' for nil:NilClass"

### ISSUE THREAD

**Issue by redline-gh** [thoughtbot/shoulda-matchers#1283]
In my `user_spec.rb` I have the following uniqueness test:
`it { should validate_uniqueness_of(:email).ignoring_case_sensitivity }`
On running `rspec`, I get an error:
```
1) User is expected to validate that :email is unique
  Failure/Error: self.email = email.downcase
     
NoMethodError:
  undefined method `downcase' for nil:NilClass
```
My user model is validating the email like this:

```
class User < ApplicationRecord

  before_save   :downcase_email

  validates :email,  uniqueness: { case_sensitive: false }

  private

  def downcase_email
    self.email = email.downcase
  end
end
```

I am setting up my user factory like this:
```
FactoryBot.define do
  factory :user do
    name { Faker::Name.name }
    email { Faker::Internet.email }z
    password { 'foobar' }
    password_confirmation { 'foobar' }
  end
end
```

Removing:

```
  before_save   :downcase_email
  def downcase_email
    self.email = email.downcase
  end
```
From my user model causes the test to pass. Shouldn't `ignoring_case_sensitivity` account for the for the downcasing of the email?

**Comment by mcmire** [comment]
@Git-Ibraheem Thanks for the report. So usually the uniqueness matcher will test that the validation you have on the model is configured to be either case-sensitive or case-insensitive. There are specific tests around this — for instance, if testing that it's case-insensitive, the matcher will test that if you have two records with the same value for the attribute under test, but the cases are different, then the validation still fails:

``` ruby
existing_user = User.create!(email: 'john@smith.com')
new_user = User.new(email: 'jOhN@smith.com')
new_user.valid?   # should be false
```

Inversely if testing that it's case-sensitive then it will test that in this setup, the second record passes validation:

``` ruby
existing_user = User.create!(email: 'john@smith.com')
new_user = User.new(email: 'jOhN@smith.com')
new_user.valid?   # should be true
```

Tacking `ignoring_case_insensitivity` onto the end of the matcher tells the matcher to skip this check. That's all it does — it does not affect how your model is going to run its validation. In your case, your `downcase_email` method will get run regardless of what you put on the matcher.

It looks like you are using a User object that does not have an email address at all. The matcher itself should not be setting `email` to nil so there must be something in how you set up your test. I see that you have a factory defined — are you using this factory in your test? Typically for validation tests you would override `subject` like:

``` ruby
subject { FactoryBot.build(:user) }
```

**Comment by Git-Ibraheem** [comment]
Thanks that fixed it. I thought factories were loaded in automatically, as I was running many other tests on the factory generated user object, and altering the factory would cause some to fail?

**Comment by mcmire** [comment]
Factories aren't loaded automatically, no. Do you have a `factory_spec.rb` that iterates through all of the factories and checks if they're valid by chance? I've seen that in some projects.

**Comment by mcmire** [comment]
Closing this since the issue seems to be resolved, but feel free to comment otherwise.
