### ISSUE TITLE
/.rvm/gems/ruby-2.6.5/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:251: warning: BigDecimal.new is deprecated; use BigDecimal() method instead

### ISSUE THREAD

**Issue by ptarud** [thoughtbot/shoulda-matchers#1306]
shoulda-matchers version 2.8.0 use BigDecimal.new and in ruby 2.7 BigDecimal does not have new class method. Should be use BigDecimal() instead.

There is a way to use the last version in MiniTest ?

**Comment by mcmire** [comment]
Yes there is! I have a prerelease version for shoulda / shoulda-matchers that removes this warning. Try upgrading `shoulda` to 4.0.0.rc2, then add the following to the bottom of your `test_helper`:

``` ruby
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :minitest
    with.library :rails
  end
end
```

**Comment by ptarud** [comment]
It works !! Thank you !
