### ISSUE TITLE
Remove webpakcer from CI

### ISSUE THREAD

**Issue by guialbuk** [thoughtbot/shoulda-matchers#1311]
`webpacker` is included by default in Rails 6.0+ which doubles our build time for this Rails version.
As `webpacker` is out of the scope of `shoulda-matchers`, it can be removed in favour of fewer dependencies and faster CI 
times.

Some related code that can help your contribution:

- Remove webpacker from Appraisals
https://github.com/thoughtbot/shoulda-matchers/blob/0b23942feb1166678c85c015f875faa2edf6627c/Appraisals#L119

- Remove nvm installation before running CI tests
https://github.com/thoughtbot/shoulda-matchers/blob/d97bdd6cab8dcb4e344f18d44db7a73fc906e58f/.travis.yml#L28

- On acceptance tests, generate apps without webpacker when possible (Rails 6+)
https://github.com/thoughtbot/shoulda-matchers/blob/0e6db542bec3dda40047ef1534001f6875f18b15/spec/support/acceptance/helpers/step_helpers.rb#L62

**Comment by adamhannadev** [comment]
May I give this issue a try? I think it's a perfect practice for a proper contribution.

**Comment by mcmire** [comment]
@adamhannadev Yes, go for it!

**Comment by adamhannadev** [comment]
> @adamhannadev Yes, go for it!

Thanks a lot. Can you recommend a location to store tests to make sure these files have had the right text added to/removed from them?

**Comment by mcmire** [comment]
@adamhannadev Just took a look at your PR!

**Comment by mcmire** [comment]
This is merged so I'll close this PR.
