### ISSUE TITLE
Use autoloading instead of requiring all files up front

### ISSUE THREAD

**Issue by mcmire** [thoughtbot/shoulda-matchers#1317]
We have a lot of files which are like [active_record.rb](https://github.com/thoughtbot/shoulda-matchers/blob/f50f70e9c8679b4e3625f445478743df875616c9/lib/shoulda/matchers/active_record.rb) where there are a bunch of `require`s at the top of the file. I've never liked this because there are different files at different levels being required. This is not as organized as it could be, and if you add a new file, it's confusing where to add the require. I've started using `autoload` in other projects and I find it easier to manage. We should do the same thing here.

For instance, for `active_record.rb`, we might change this to something like:

``` ruby
module Shoulda
  module Matchers
    module ActiveRecord
      autoload :AssociationMatcher, "shoulda/matchers/active_record/association_matcher"
      autoload :AssociationMatchers, "shoulda/matchers/active_record/association_matchers"
      autoload :HaveDbColumnMatcher, "shoulda/matchers/active_record/have_db_column_matcher"
      # ...
    end
  end
end
```

**Comment by VSPPedro** [comment]
Hi, @mcmire, I would love to work on this!

**Comment by mcmire** [comment]
@VSPPedro Okay, that would be awesome! I will assign this to you :)

**Comment by VSPPedro** [comment]
Thanks!

**Comment by n-rodriguez** [comment]
@mcmire why not using [Zeitwerk](https://github.com/fxn/zeitwerk)?

**Comment by mcmire** [comment]
@n-rodriguez I'm not sure that Zeitwerk would be a good choice here. It seems like it's really well suited for applications, but it seems overkill for gems IMO. It would have to be added as a runtime dependency and I don't feel like people should have to bring in Zeitwerk to use shoulda-matchers.

**Comment by n-rodriguez** [comment]
> but it seems overkill for gems IMO.

IMO this PR is the perfect use case for Zeitwerk since you do exactly what it does.

**Comment by VSPPedro** [comment]
@mcmire First, sorry for the problems with the PR and thank you for releasing the fix so fast.

For now, I will focus on adding the tests first, as described by you here: https://github.com/thoughtbot/shoulda-matchers/issues/1333#issuecomment-680980460. After adding these tests I will continue with this PR - if that's okay with you.

**Comment by mcmire** [comment]
@VSPPedro Yeah, that's fine with me!

**Comment by mcmire** [comment]
I'm going to close this issue. It seems like this is a relatively minor pain point and is actually more complicated than I thought it would be.
