### ISSUE TITLE
has_and_belongs_to_many .join_table not working with symbolized table name

### ISSUE THREAD

**Issue by allisonphillips** [thoughtbot/shoulda-matchers#1321]
I am experiencing errors when trying to add shoulda matcher specs for `has_and_belongs_to_many` relationships for classes that are not dependent on any gem. At first I thought I had forgotten to configure something, but then I reproduced by writing the same example for similar classes that has long been functioning in a production environment without issue. All this syntax works:

```ruby
# class
has_and_belongs_to_many :association_name,
  class_name:              '::AssociationClass',
  join_table:              :join_table_name_that_definitely_exists,
  foreign_key:             foreign_key_id,
  association_foreign_key: association_foreign_key_id

# spec
it do
  should have_and_belong_to_many(:association_name)
    .class_name('::AssociationClass')
    .with_foreign_key(:foreign_key_id)
    .with_foreign_key(:association_foreign_key_id)
end
```

But as soon as I add `.join_table(:join_table_name_that_definitely_exists)` to the example block in the spec, I get the equivalent of this message: 
```ruby
"Expected #{described_class} to have a has_and_belongs_to_many association " \
"called #{association_name} (join table #{join_table_name} doesn't exist)"
```
I eventually figured out that **the matcher works if you pass the join table name as a _string_**. It appears that the matcher doesn't support table names as a symbol. 

_Originally posted by @allisonphillips in https://github.com/thoughtbot/shoulda-matchers/issues/625#issuecomment-589408515_

**Comment by mcmire** [comment]
Thanks for submitting this separately! I've got a fix for this in #1323.
