### ISSUE TITLE
have_and_belong_to_many matcher doesn't seem to find join table

### ISSUE THREAD

**Issue by JorgeLeites** [thoughtbot/shoulda-matchers#1325]
I was adding user groups to my app and I'm having the following issue:

## Spec
```rb
require 'rails_helper'

RSpec.describe Group, type: :model do
  describe 'associations' do
    it { should have_and_belong_to_many(:users) }
  end
end
```

## Model
```rb
class Group < ApplicationRecord
  has_and_belongs_to_many :users
end

class User < ApplicationRecord
  has_and_belongs_to_many :groups
end
```

## Schema
```rb
  create_table "groups_users", id: false, force: :cascade do |t|
    t.bigint "user_id", null: false
    t.bigint "group_id", null: false
  end
```

And the test fails with the message: `Expected Group to have a has_and_belongs_to_many association called users (join table groups_users doesn't exist)`

Am I missing something?

**Comment by mcmire** [comment]
I'm not certain. Is the table in your test database? What happens if you run `rails db:test:prepare`?

**Comment by JorgeLeites** [comment]
I'm astonished. It didn't seem to do anything, but the problem went away. Do you think that was the problem?

**Comment by JorgeLeites** [comment]
I'm closing the issue since it seems like it was a problem on my behalf.
