### ISSUE TITLE
validate_associated

### ISSUE THREAD

**Issue by calebhearth** [thoughtbot/shoulda-matchers#133]
It would be nice to have a `validate_associated` matcher for AR::Resources.

The options for `validates_associated` are:
- **:message** - A custom error message (default is: "is invalid")
- **:on** - Specifies when this validation is active. Runs in all
  validation contexts by default (+nil+), other options are `:create`
  and `:update`.
- **:if** - Specifies a method, proc or string to call to determine if the validation should
  occur (e.g. `:if => :allow_validation**, or **:if => Proc.new { |user| user.signup_step > 2 }`). The
  method, proc or string should return or evaluate to a true or false value.
- **:unless** - Specifies a method, proc or string to call to determine if the validation should
  not occur (e.g. `:unless => :skip_validation`, or `:unless => Proc.new { |user| user.signup_step <= 2 }`). The
  method, proc or string should return or evaluate to a true or false value.

...so it would be cool if there were methods on the matcher to accomodate those.

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/validations/associated.rb

**Comment by san983** [comment]
:+1: +1

**Comment by vfonic** [comment]
:+1: 

I think it's pretty common to keep the issue open until it's resolved. Also, someone searching for an answer, can see that this issue is still open. It saves time.

**Comment by wjdhamilton** [comment]
:+1: Agreed

**Comment by lifeiscontent** [comment]
@mcmire any updates here?

**Comment by Fedcomp** [comment]
:+1:

**Comment by ajalvarez89** [comment]
Hello team, this issue still open, i'd like to help.
