### ISSUE TITLE
Does shoulda-matchers not support alias_attribute?

### ISSUE THREAD

**Issue by marcelolx** [thoughtbot/shoulda-matchers#1330]
I'm working on a project where the database fields are in pt-BR, but in our rails project which uses this database our convention is to use `alias_attribute` to use this fields all in english, but shoulda-matcher seems to not be able to get the field type when it validates numericality based on his alias.

I've created a sample simulating this here https://github.com/marcelolx/shoulda-matchers-test-apps

```
Failure/Error: it { is_expected.to validate_numericality_of(:exchange).is_less_than_or_equal_to(1000) }
     
       Expected Example to validate that :exchange looks like a number less
       than or equal to 1000, but this could not be proved.
         After setting :exchange to ‹"abcd"› -- which was read back as ‹0.0› --
         the matcher expected the Example to be invalid, but it was valid
         instead.
     
         As indicated in the message above, :exchange seems to be changing
         certain values as they are set, and this could have something to do
         with why this test is failing. If you've overridden the writer method
         for this attribute, then you may need to change it to make this test
         pass, or do something else entirely.
```

I can "handle" this by setting the validation to the field based on his name on database, but then we will be mixing pt-BR code with en 😢 

If possible, I'll be happy to help you guys to handle it.

**Comment by mcmire** [comment]
So this is less that your attribute is an alias of another attribute and more to do with the fact that your attribute is a numeric column. This is a common problem with `validate_numericality_of` that I swear we fixed but I guess we haven't. The matcher works fine with string columns, but numeric columns typecast incoming strings to numbers, so it throws the matcher off. This is not a problem with the numericality validation itself because it makes use of the `*_before_type_cast` version of the attribute in its underlying logic. So to properly fix this, the matcher needs to do this as well, somehow. Unfortunately, I am not immediately sure if there is a way to solve this in the meantime aside from writing a test yourself, which could look something like:

``` ruby
it "validates numericality of :exchange is less than or equal to 1000" do
  subject = described_class.new
  subject.exchange = 1001
  subject.validate
  expect(subject.errors[:exchange]).to include("must be less than or equal to 1000")
  subject.exchange = 1000
  subject.validate
  expect(subject.errors[:exchange]).not_to include("must be less than or equal to 1000")
  subject.exchange = 999
  subject.validate
  expect(subject.errors[:exchange]).not_to include("must be less than or equal to 1000")
end
```

**Comment by marcelolx** [comment]
> So this is less that your attribute is an alias of another attribute and more to do with the fact that your attribute is a numeric column. This is a common problem with `validate_numericality_of` that I swear we fixed but I guess we haven't. The matcher works fine with string columns, but numeric columns typecast incoming strings to numbers, so it throws the matcher off. This is not a problem with the numericality validation itself because it makes use of the `*_before_type_cast` version of the attribute in its underlying logic. So to properly fix this, the matcher needs to do this as well, somehow. Unfortunately, I am not immediately sure if there is a way to solve this in the meantime aside from writing a test yourself, which could look something like:
> 
> ```ruby
> it "validates numericality of :exchange is less than or equal to 1000" do
>   subject = described_class.new
>   subject.exchange = 1001
>   subject.validate
>   expect(subject.errors[:exchange]).to include("must be less than or equal to 1000")
>   subject.exchange = 1000
>   subject.validate
>   expect(subject.errors[:exchange]).not_to include("must be less than or equal to 1000")
>   subject.exchange = 999
>   subject.validate
>   expect(subject.errors[:exchange]).not_to include("must be less than or equal to 1000")
> end
> ```


But in the sample who i provided, i've two numeric fields [value](https://github.com/marcelolx/shoulda-matchers-test-apps/commit/03559d8a181a70b8453f29cc5534452c8047119a#diff-05c7192a2cc6883f7f5338acad624461R19) and [cambio](https://github.com/marcelolx/shoulda-matchers-test-apps/commit/03559d8a181a70b8453f29cc5534452c8047119a#diff-05c7192a2cc6883f7f5338acad624461R20), the [tests referring `value`](https://github.com/marcelolx/shoulda-matchers-test-apps/commit/03559d8a181a70b8453f29cc5534452c8047119a#diff-974edf886e19a9138424f6cb68703fc7R5) pass without problems, but the [tests with the field `cambio`](https://github.com/marcelolx/shoulda-matchers-test-apps/commit/03559d8a181a70b8453f29cc5534452c8047119a#diff-974edf886e19a9138424f6cb68703fc7R7) who has an alias `exchange` doesn't pass.

At the begining i was not able to understand why in our project these tests was failing and on  the sample not, so I  see that the only difference between them was the alias_attribute. Then I created another column and aliased it, the tests for this aliased field started failing  and for the field who isn't aliased they don't fail, because of this I supose that this has something to do with the alias.

Maybe it has nothing todo with the alias, but it is a bit curious that this problem only happens when the numeric field is aliased.

Anyway,  for now I'll write manual tests as you suggested.

Thanks @mcmire

**Comment by mcmire** [comment]
@marcelolx Oh I see... right. Thanks for reproducing this in the example repo! I think you must be right about the alias attribute then. I have no clue why that wouldn't work, there's nothing special that we do in regard to aliases. But I will look further into this. Maybe it is something small.

**Comment by marcelolx** [comment]
@mcmire Great! Maybe is something with rails 🤔 Tonight I'll look a little bit more deeper to see why that is happening, maybe I will be able to discover something who can help you on this.

**Comment by marcelolx** [comment]
@mcmire I was looking on this and found the root cause of this, don't seem to be entirely related to shoulda-matchers.

First change I've made was on these methods [attribute_is_active_record_column?](https://github.com/rails/rails/blob/6-0-stable/activemodel/lib/active_model/validations/numericality.rb#L32) and [column_type](https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb#L519) to get the type of the column based on alias_attribute.

Now it looks like this
```ruby
def attribute_is_alias_for_active_record_column?
  @subject.class.attribute_aliases.key?(@attribute.to_s)
end

def attribute_is_active_record_column?
  attr_name = @attribute.to_s
  if attribute_is_alias_for_active_record_column?
    attr_name = attribute_non_aliased_name
  end

  columns_hash.key?(attr_name)
end

def column_type
  attr_name = @attribute.to_s
  if attribute_is_a_alias_for_active_record_column?
    attr_name = attribute_non_aliased_name
  end
          
  columns_hash[attr_name].type
end
```

I thinked that this would be enough to solve the problem, but it keeps happening, so I debuged the entire process and noticed that the problem is when rails read the value of the attribute, it reads the value before type casting https://github.com/rails/rails/blob/6-0-stable/activemodel/lib/active_model/validations/numericality.rb#L32 so if the function returns nil, it assigns the value type casted to be validated https://github.com/rails/rails/blob/6-0-stable/activemodel/lib/active_model/validations/numericality.rb#L42 and here lives the problem with `alias_attribute`, because when rails try to `read_attribute_before_type_cast` it is returning nil because he is trying to read the value from the [attribute](https://github.com/rails/rails/blob/6-0-stable/activerecord/lib/active_record/attribute_methods/before_type_cast.rb#L50) with the alias name instead of the original attribute name, so the value validated is `0.0` instead of `abcd`.

Tomorrow I'll make more tests and see if this happens in tests without shoulda-matchers, but I think that probably happens, but no one has noticed it.

**Comment by mcmire** [comment]
Thanks for the detailed investigation! It doesn't surprise me to hear about `_before_type_cast` — this is something that the numericality matcher in shoulda-matchers does not account for, so if the error truly is in shoulda-matchers then that would make sense. I'm curious to hear what else you find, however.

**Comment by marcelolx** [comment]
@mcmire Sorry the delay, I've made a fix on rails https://github.com/rails/rails/compare/master...marcelolx:fix_read_attribute_before_type_cast_for_aliased_attributes?expand=1 and soon (maybe tomorrow 😅) I'll open a PR explaining the problem. If the PR will be merged I think than we can make new tests and see if we need fix something on shoulda-matchers.

**Comment by marcelolx** [comment]
@mcmire I think we can close this issue, I've sent a PR https://github.com/rails/rails/pull/40395 to rails and now the described problem in this issue doesn't happens anymore.

My only concern is that shoulda-matchers is not able to get the column type here https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb#L520 when the attribute is an alias_attribute and this can cause another kinds of bugs in the future 🤔

**Comment by mcmire** [comment]
Nice work on merging that into Rails! You're right about `column_type`, I can see that not working with an aliased attribute. You're free to take a crack at solving that problem or not — if everything works for you then feel free to close this and maybe someone else can pick that up. Or whatever you want to do :)

**Comment by marcelolx** [comment]
@mcmire I'll take a look on the codebase to see if there is a way to simulate a problem because `column_type`, if there isn't I'll close this issue.

Thanks!

**Comment by marcelolx** [comment]
@mcmire I'll close this issue, since we haven't seen any other problem related aliased attribute in our project. If such problem happens in the future then we take a better look and see what could be the causes.

**Comment by mcmire** [comment]
@marcelolx Great! Thanks for the update!
