### ISSUE TITLE
Generating documentation no longer works

### ISSUE THREAD

**Issue by mcmire** [thoughtbot/shoulda-matchers#1336]
We use Pygments along with YARD to highlight source code in documentation. Unfortunately this seems to have stopped working and upon running `yard doc` (which happens automatically when creating new releases) we are getting:

```
MentosError: No header received back
```

This seems to have been a [problem](https://github.com/tmm1/pygments.rb/issues/45) for a very long time and there is no known solution.

Perhaps instead of Pygments we should switch to [Rouge](https://github.com/rouge-ruby/rouge) instead?

**Comment by KapilSachdev** [comment]
Is this a system specific issue or an intermittent issue and happens sometimes?

BTW, [Rouge](https://github.com/rouge-ruby/rouge) looks great and would be a good replacement.

**Comment by mcmire** [comment]
@KapilSachdev I don't know if it's a system specific issue, but it's definitely repeatable on my machine (Mac). Previously there was an issue with using Python 3 vs. Python 2 — I believe I cleared that up, so there was a long stretch where it did work for a while. But now within the past 6 months I'd say, I've started receiving this error.

**Comment by KapilSachdev** [comment]
Then the alternative would be a better way to go.

However, we can also create a docker image and try to use the image for release, but that would be an overkill and also we can't be sure if it wouldn't appear in the image.

**Comment by KapilSachdev** [comment]
Looks good too.

#### With pgyments
![pgyments](https://user-images.githubusercontent.com/16557539/91482773-38a82880-e8c4-11ea-9d03-cc76c534761f.png)

#### With rouge
![rouge](https://user-images.githubusercontent.com/16557539/91482779-3c3baf80-e8c4-11ea-92e6-59739886d401.png)

**Comment by mcmire** [comment]
Oh nice — do you have it working where it's swapped out in the YARD config, or were you just testing it out on something else?

**Comment by KapilSachdev** [comment]
Changed the yard setup `doc_config/yard/setup.rb` to use `rouge` instead of `pygments.rb`.

```diff
diff --git a/doc_config/yard/setup.rb b/doc_config/yard/setup.rb
index eb654f5b..381b4269 100644
--- a/doc_config/yard/setup.rb
+++ b/doc_config/yard/setup.rb
@@ -1,6 +1,6 @@
 YARD::Templates::Engine.register_template_path(File.dirname(__FILE__) + '/templates')
 
-require 'pygments.rb'
+require 'rouge'
 
 module YARD
   module Templates
@@ -13,8 +13,7 @@ module YARD
         private
 
         def highlight_with_pygments(language, source)
-          html = Pygments.highlight(source, lexer: language.to_s)
-          html.sub(%r{\A<div class="highlight">\s*<pre>}, '').sub(%r{</pre>\s*</div>\Z}, '')
+          Rouge::Formatters::HTML.new.format(Rouge::Lexers::Ruby.new.lex(source))
         end
       end
     end
```
As  the only language being used was `ruby`, so I used `Rouge::Lexers::Ruby` as opposed to defining the constant from `language` for testing.

Can you clarify what the below substitution is doing?
 ```ruby
html.sub(%r{\A<div class="highlight">\s*<pre>}, '').sub(%r{</pre>\s*</div>\Z}, '')
```

**Comment by mcmire** [comment]
@KapilSachdev Very nice, that makes sense. IIRC, Pygments was adding some additional HTML that was making it more difficult to apply CSS to the code blocks, so I got rid of that. I'm not sure if Rouge does the same thing or not.

**Comment by KapilSachdev** [comment]
It is visible when using `pygments.rb` and removing that substitution.

![pygments_sub](https://user-images.githubusercontent.com/16557539/91586084-87ac9700-e972-11ea-8543-cb5b50eb93d2.png)

Adding or removing the block does not change anything using rouge.

**Comment by mcmire** [comment]
Ah yup, there you go, that's what it was. I knew it was something CSS-related.
