### ISSUE TITLE
Replace Hound with GitHub Action

### ISSUE THREAD

**Issue by mcmire** [thoughtbot/shoulda-matchers#1345]
In the past, this gem was using Hound (developed by some now ex-thoughtbotters) to run code through Rubocop. However, it doesn't seem to be maintained much these days — I actually disabled Hound a while back because it started choking on new versions of Rubocop, starting with the Rubocop team's decision to spin `rubocop-rails` off. Since then GitHub Actions has emerged as a more built-in solution for these types of tasks. I believe there is a linter action out there that integrates with Rubocop, and I think we should try to use that instead.

**Comment by KapilSachdev** [comment]
How do you want to implement this, with a third party marketplace tool or a simpler flow maintained by self.

Third party Marketplace tool example
https://github.com/KapilSachdev/shoulda-matchers/pull/1/checks?check_run_id=1348979287

If we create one ourselves 
https://github.com/rails/rails/runs/1348960136?check_suite_focus=true

**Comment by mcmire** [comment]
I'm not sure which PR that build is assigned to, but I found this one https://github.com/rails/rails/actions/runs/343607226 which is tied to this PR https://github.com/rails/rails/pull/40404. I like how Hound would add comments to the PR at the places where the violations failed to let contributors (and maintainers) know why the Rubocop check is failing; otherwise, it seems like those violations would get buried. I found an action that does a similar thing: https://github.com/marketplace/actions/lint-action. What do you think about this one?

**Comment by KapilSachdev** [comment]
Seems good.
`lint-action` seems to be doing want you want.
I think we can try this one for a while and may change later in case needed.
