### ISSUE TITLE
Remove allow_mass_assignment_of matcher

### ISSUE THREAD

**Issue by VSPPedro** [thoughtbot/shoulda-matchers#1346]
I found this [commit](https://github.com/thoughtbot/shoulda-matchers/commit/c1a81d4b132a9e6091c42c3ebcd3144fc593c016) and after reading the description I decided to create this issue so that we do not forget about this change.

I think this can be tagged as 'Beginner Friendly'.

I'm not entirely sure if we want this change now or maybe later with a major release.

**Comment by mcmire** [comment]
Yes! Wow sorry it took me so long to get back to you on this. I think this would be the perfect kind of thing to consider if we are thinking about 5.0.

**Comment by VSPPedro** [comment]
No problem! Should we add a deprecation warning to this first? And for the major release, we remove it.

**Comment by mcmire** [comment]
Ah. Yes. That would be a good idea. :)

**Comment by VSPPedro** [comment]
Closing this issue because the allow_mass_assignment_of matcher was already removed. 🎉
