### ISSUE TITLE
Drop `git` in gemspec

### ISSUE THREAD

**Issue by utkarsh2102** [thoughtbot/shoulda-matchers#1353]
Hiya,

Thanks for your lovely work on this! ❤️ 

However, whilst trying to maintain this in Debian, we found that this library relies on `git` to produce a list of files.
Using `git` in gemspec is a bit troublesome and it's best to not use them!

More about this can be found here: https://docs.rubocop.org/rubocop-packaging/cops_packaging.html#packaginggemspecgit

If you agree with this, I'll be very happy to raise a PR for this! 😄 

CC: @mcmire

**Comment by mcmire** [comment]
Hi @utkarsh2102. For context, the gemspec was originally created using Bundler. My guess as to why `git` was added to the gemspec was to prevent uncommitted changes from being released. I just checked Bundler, however, and it seems that `rake release` already checks against this. Therefore, I can't see a reason why we would need to use `git` in the gemspec. So I'd be fine with a PR that simplifies that part of the gemspec.

**Comment by utkarsh2102** [comment]
Awesome, thanks!
We're working with the Bundler team to avoid using `git` by default (bundler itself doesn't use git!). And also, bundler now won't let you release if you have uncommitted changes, so it's pretty safe that way, too!

I'll work on the PR now :)
