### ISSUE TITLE
have_many(:model).validate(false) causes a false positive test

### ISSUE THREAD

**Issue by kiskoza** [thoughtbot/shoulda-matchers#1357]
I run into a problem where I had to make sure that an association has a `validate: false` on the association. I started it with writing a test for it, but it passed immediately without making the required code change.

I created this code snippet to reproduce the issue: https://gist.github.com/kiskoza/da2b4a0ba6930e9454403ea36e3fd73c

I think the problem is that in my case there weren't a `validate` option prior to the task. When it was [validated as a boolean](https://github.com/thoughtbot/shoulda-matchers/blob/256d3b5ac9a9031af7b7096fbcbb72272784000b/lib/shoulda/matchers/active_record/association_matcher.rb#L1360-L1367), the `nil` value was simply [converted to](https://github.com/thoughtbot/shoulda-matchers/blob/256d3b5ac9a9031af7b7096fbcbb72272784000b/lib/shoulda/matchers/active_record/association_matchers/option_verifier.rb#L71-L72) `false`

Docs about the validate option: https://apidock.com/rails/ActiveRecord/Associations/ClassMethods/has_many

**Comment by VSPPedro** [comment]
Hi, @kiskoza , thank you very much for all this information. The description of this issue helped me a lot.

This fix will be available on the next release.

Thank you!

Thank you again.
