### ISSUE TITLE
Rubygems changelog link does not work

### ISSUE THREAD

**Issue by stefanwork** [thoughtbot/shoulda-matchers#1363]
The Changelog link on https://rubygems.org/gems/shoulda-matchers goes to https://github.com/thoughtbot/shoulda-matchers/blob/master/NEWS.md, which does not work. It should be updated to https://github.com/thoughtbot/shoulda-matchers/blob/master/CHANGELOG.md.

**Comment by mcmire** [comment]
Good catch. Want to submit a PR to fix this?

**Comment by stefanwork** [comment]
I searched for "[NEWS.md](https://github.com/thoughtbot/shoulda-matchers/search?q=NEWS.md)" but came up empty. It doesn't look like it is defined in the gemspec, right? Is it not a thing on the rubygems website?

Oh... looks like it may already have been fixed? https://github.com/thoughtbot/shoulda-matchers/commit/c4f9add764d9ceb0f24cc6b18b9004d5acbfd9bf

**Comment by mcmire** [comment]
Oops, yes! It already got fixed and will propagate in the next version bump (which I think can happen relatively soon).

**Comment by KapilSachdev** [comment]
I think we can close this as it was already resolved in #1338 , and will be available in next release.

**Comment by mcmire** [comment]
Yeah that's fair. Closing now.
