### ISSUE TITLE
with_foreign_key modifier fails with no error message

### ISSUE THREAD

**Issue by orenyk** [thoughtbot/shoulda-matchers#1374]
Steps to replicate:

```ruby
# migration
create_table :foos do |t|
  t.references :bar, foreign_key: true
  t.timestamps
end

create_table :bars do |t|
  t.timestamps
end

# app/model/foo.rb
class Foo < ApplicationRecord
  belongs_to :pub, class_name: 'Bar', foreign_key: :bar_id
end

# app/model/bar.rb
class Bar < ApplicationRecord
  has_many :foos, inverse_of: :pub
end

# spec/models/foo_spec.rb
...
it { is_expected.to belong_to(:pub).class_name('Bar').with_foreign_key(:bar_id) }
...
```

The test passes but if I change the argument of `with_foreign_key` to anything else (e.g. `baz_id`) the spec fails with the following error message:

```
Expected Foo to have a belongs_to association called pub ()
```

If the `class_name` argument is changed to be incorrect there is a specific error message in the parentheses for the submatcher (`pub should resolve to Baz for class_name`), so I'm guessing that somehow the following lines are no longer working as expected: https://github.com/thoughtbot/shoulda-matchers/blob/b7e02184d99014dc57d9e37bc134c4b6c5254b69/lib/shoulda/matchers/active_record/association_matcher.rb#L1404-L1407

Hope that helps!

**Comment by mcmire** [comment]
Dang, okay. These association matchers could use some better error handling so I'm not surprised. But thank you for the report!

**Comment by VSPPedro** [comment]
Hi, @orenyk , thank you very much for all this information. The description of this issue helped me a lot.

This fix will be available on the next release. It's already on the master.

Thanks again!

**Comment by orenyk** [comment]
Awesome, thanks! I meant to take a look myself but ran out of time 😄. Appreciate the heads up too, thanks again!
