### ISSUE TITLE
`validate_numericality_of` with `ActiveModel::Attributes` fails validation

### ISSUE THREAD

**Issue by ollie-nye** [thoughtbot/shoulda-matchers#1403]
When including `ActiveModel::Attributes` in a form object and trying to validate a typed attribute, the attribute seems to cause the validation test to fail with
```
Failure/Error: it { should validate_numericality_of(:cost).is_greater_than_or_equal_to(0) }
     
       Expected Forms::AssetType to validate that :cost looks like a number
       greater than or equal to 0, but this could not be proved.
         After setting :cost to ‹"abcd"› -- which was read back as ‹0› -- the
         matcher expected the Forms::AssetType to be invalid, but it was valid
         instead.
     
         As indicated in the message above, :cost seems to be changing certain
         values as they are set, and this could have something to do with why
         this test is failing. If you've overridden the writer method for this
         attribute, then you may need to change it to make this test pass, or
         do something else entirely.
```

Using `attr_accessor` instead of `attribute` seems to work, but then we lose the type-ness of the field

Working:
```ruby
class Form
  include ActiveModel::Model

  attr_accessor :count

  validates :count, numericality: { greater_than_or_equal_to: 0 }
end
```

Not working:
```ruby
class Form
  include ActiveModel::Model
  include ActiveModel::Attributes

  attribute :count, :integer

  validates :count, numericality: { greater_than_or_equal_to: 0 }
end
```

Test:
```ruby
RSpec.describe Form, type: :model do
    it { should validate_numericality_of(:count).is_greater_than_or_equal_to(0) }
end
```

Do shoulda-matchers not support ActiveModel `attribute`s, or am I doing something wrong with the setup?

**Comment by mcmire** [comment]
This is a known issue with `validates_numericality_of`. It was originally written to work with string columns, not integer columns. I believe it may work with ActiveRecord columns now, I'd have to check, but I don't believe we explicitly support ActiveModel attributes like that. Not saying it's not possible, I just don't think it's something we've addressed yet. So you may have to manually write this test for now.

**Comment by ollie-nye** [comment]
Ah ok, that's good to know, thanks!

**Comment by bvicenzo** [comment]
I've been facing this error today when I've created a basic active model, with no active record.
After looking for it, I realized that in active model, the validation is running using casted values, the active model validations calls the method `read_attribute_for_validation`, defined [here](https://github.com/rails/rails/blob/a6efde6cf648a5c4125c6677b775357cdc1c92f0/activemodel/lib/active_model/validations.rb#LL431C12-L431C41) as an alias for `send`, and this method is called [here](https://github.com/rails/rails/blob/5dd4dcbae3647cb4b37000bfe6273d6865bd6dc8/activemodel/lib/active_model/validator.rb#LL151C1-L151C1).

Then a simple active model is validating the value after it is casted.
Including the module [ActiveRecord::AttributeMethods::BeforeTypeCast](https://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/BeforeTypeCast.html) my validation has started to work as expected.
