### ISSUE TITLE
Uninitialized Constant Rspec

### ISSUE THREAD

**Issue by Merovex** [thoughtbot/shoulda-matchers#1408]
I am only using minitest, not Rspec. However, I get the following error message:

`/shoulda-matchers-4.5.0/lib/shoulda/matchers/integrations/test_frameworks/rspec.rb:13:in include': uninitialized constant RSpec (NameError)`

Given there are instructions for using Minitest, is there a way to solve this without resorting to adding Rspec?

**Comment by Merovex** [comment]
Solved my own problem. The README says to add the following to the bottom of the `test_helper.rb`:

```
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :rails
  end
end
```

But it should be 
```
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :minitest
    with.library :rails
  end
end
```

**Comment by mcmire** [comment]
Did you see the Minitest section? :) https://github.com/thoughtbot/shoulda-matchers#minitest
