### ISSUE TITLE
have_db_column refactor from #1358 broke tests

### ISSUE THREAD

**Issue by lifeiscontent** [thoughtbot/shoulda-matchers#1414]
I have a test:

```rb
it { is_expected.to have_db_column(:author_id).with_options(null: false, foreign_key: { to_table: :users }) }
```

which is now not possible due to the refactor of #1358 because it doesn't have foreign_key in its list of options.

**Comment by lifeiscontent** [comment]
CC: @rodriggochaves @mcmire

**Comment by lifeiscontent** [comment]
example usage here: https://github.com/lifeiscontent/realworld/pull/662

**Comment by mcmire** [comment]
@lifeiscontent We have never officially supported checking for `foreign_key` so far, so presently your test is equivalent to:

``` ruby
it { is_expected.to have_db_column(:author_id).with_options(null: false) }
```

We will happily take a PR to add this.

**Comment by mcmire** [comment]
Closing this since #1421 was closed.
