### ISSUE TITLE
`belong_to` matcher doesn't allow using association in model's public methods

### ISSUE THREAD

**Issue by lioneldebauge** [thoughtbot/shoulda-matchers#1461]
Hello 👋 

I encountered a strange behavior while using your gem. Basically I have this model

```ruby
# residence.rb

class Residence < ApplicationRecord # rubocop:disable Metrics/ClassLength

  belongs_to :lease_document_template

  def german_lease?
    lease_document_template.german?
  end
end
```

I test its belongs_to association with shoulda-matchers

```ruby
# residence_spec.rb

 it { is_expected.to belong_to(:lease_document_template).required }
```

Everything should be fine however when I execute the test I get this error

```
     NoMethodError:
       undefined method `german?' for nil:NilClass
     # ./app/models/residence.rb:184:in `german_lease?'
     # ./spec/models/residence_spec.rb:16:in `block (2 levels) in <top (required)>'
```

After digging a little bit it seems that should-matchers executes all public methods of the model in different state including one when `lease_document_template_id` is nil. 

Is this an expected behavior however ? I would assume that testing what happens if the belongs_to association is nil should not break the test if any public method use this association.

Thanks a lot for any answer you can give me and this amazing gem 🙏 

PS: I found 2 ways to go around it

```ruby
# residence.rb
  def german_lease?
    return false if lease_document_template.nil?

    lease_document_template.german?
  end
```

or

```ruby
# residence_spec.rb

  it { is_expected.to belong_to(:lease_document_template).without_validating_presence }
```

**Comment by mcmire** [comment]
Hi @lioneldebauge ,

Yes, this is expected behavior. By default `belongs_to` will add a presence validation to the association. That means that there is a possibility that the association is nil. Because of this the matcher tests what happens if indeed it is nil. The error could be better but the fact that it happens is revealing a missing check in your code. I would go with the first option you found to ensure that if `lease_document_template` is nil it doesn't break your validations.

**Comment by lioneldebauge** [comment]
@mcmire thanks a lot for your clarification :) 

In our context we can safely rely on the fact that we will always have this association so we will go for the second solution. I understand however why you would recommend the first one ! 

Closing this issue now. Thanks again !
