### ISSUE TITLE
Add Appraisal for Rails 7.0.0

### ISSUE THREAD

**Issue by VSPPedro** [thoughtbot/shoulda-matchers#1469]
TODO

**Comment by mathieujobin** [comment]
Started getting this error with Rails 7

`wrong constant name shoulda-matchers test string`

I do not know yet why, just started investigating

**Comment by mcmire** [comment]
@mathieujobin Would you mind posting a new issue for that? I think that would be easier to track. I think this issue is just intended to be a marker for adding the appraisal, not for addressing any Rails 7 issues necessarily.

**Comment by mathieujobin** [comment]
@mcmire I believe this is exactly https://github.com/thoughtbot/shoulda-matchers/issues/1433
my test isn't instantiating the model, but still fail with that error.
