### ISSUE TITLE
`validate!` support?

### ISSUE THREAD

**Issue by sirwolfgang** [thoughtbot/shoulda-matchers#1481]
Is there a way to use the validation matches for hard validations, ie `validate!`?

This has been [supported by rails](https://apidock.com/rails/ActiveModel/Validations/validate%21) for a long while, and generally seems like the preferable choice for code paths that are the result of developer error and not user input error.

```bash
     Failure/Error: it { is_expected.to validate_presence_of(:type) }

       Expected Model to validate that :type cannot be empty/falsy,
       but this could not be proved.
         After setting :type to ‹""›, the matcher expected the
         Model to be invalid and to produce validation errors, but
         the record raised a validation exception instead.
 ```

**Comment by mcmire** [comment]
There is! Unfortunately this isn't documented anywhere — probably just an oversight — but if you tack on `.strict`, then it will test your validations via `.validate!` instead of `.validate`. For example:

``` ruby
it { is_expected.to validate_presence_of(:type).strict }
```
