### ISSUE TITLE
I don't understand the error message in validate_length_of 

### ISSUE THREAD

**Issue by Jonathandeveloper19** [thoughtbot/shoulda-matchers#1498]
I have the following model with the following validation

`validates :cellphone,
            presence: {
              message: "can't be blank"
            },
            length: {
              minimum: 10
            }`

by running the following test 

`it 'ensures cellphone lenght min 10' do
      should validate_length_of(:cellphone).is_at_least(10)
    end`

I get the following error
 
`Failure/Error: should validate_length_of(:cellphone).is_at_least(10).on(:create)

       Expected User to validate that the length of :cellphone is at least 10,
       but this could not be proved.
         After setting :cellphone to ‹"xxxxxxxxxx"› -- which was read back as
         ‹0› -- the matcher expected the User to be valid, but it was invalid
         instead, producing these validation errors:

         * password: ["can't be blank", "can't be blank", "is invalid", "is too
           short (minimum is 8 characters)"]
         * Municipio: ["can't be blank"]
         * Departamento: ["can't be blank"]
         * cellphone: ["is invalid", "is too short (minimum is 10 characters)"]
         * email: ["El campo email es obligatorio", "El campo es inválido"]

         As indicated in the message above, :cellphone seems to be changing
         certain values as they are set, and this could have something to do
         with why this test is failing. If you've overridden the writer method
         for this attribute, then you may need to change it to make this test
         pass, or do something else entirely.`

I have tried several ways but I can't solve the error, so advice is welcome.

**Comment by mcmire** [comment]
It looks like your `cellphone` column is a numeric column. Unfortunately `validate_length_of` doesn't work with numeric columns, only string ones, so it's not able to test this. This was tracked in https://github.com/thoughtbot/shoulda-matchers/issues/1094 (which was closed for being stale). You may wish to manually test this for the time being.

**Comment by Jonathandeveloper19** [comment]
@mcmire Thank you very much, I will leave it running manually, I will close this topic as it is something that has been discussed before.
