### ISSUE TITLE
No source_type matcher for has_many?

### ISSUE THREAD

**Issue by Kutomore** [thoughtbot/shoulda-matchers#1526]
Pretty much checking docs source code there isn't a matcher for the scenario:

has_many :products, through: :add_ons, source_type: 'Product'

Where add_ons is polymorphic so source_type is required.

**Comment by mcmire** [comment]
If you have a polymorphic association then shoulda-matchers will test it automatically — no need for any extra qualifiers like `.source_type` or anything! Here's a test in our test suite which verifies that polymorphic associations work: https://github.com/thoughtbot/shoulda-matchers/blob/481712b4d062b81a15d8bc3517818c230d1ccea8/spec/unit/shoulda/matchers/active_record/association_matcher_spec.rb#L886
