### ISSUE TITLE
Could Not Prove `not_to validate_length_of` Despite Conditional Validation Equally false

### ISSUE THREAD

**Issue by ndouglasma** [thoughtbot/shoulda-matchers#1541]
In my user model, I have the following conditional validation:

```
validates_length_of :first_name, maximum: 44, if: Proc.new { |u| !u.cook? }
```

In my spec, I have:

```
let(:user)   { build :cook, first_name: 'Super Cook' }

it "doesn't execute the validation" do
  expect(user).not_to validate_length_of(:first_name)
end
```

**Expectation:** Test passes; and the first name conditional validation doesn't execute.
**Actual:** 
```
 Failure/Error: expect(user).not_to validate_length_of(:first_name)
 
   Expected User not to validate that the length of :first_name, but this
   could not be proved.
```

Please note I tried switching the conditional validation to `unless`, and still received the same spec failure.  Interestingly, I have other specs for `not_to validate_presence_of` and `not_to validate_absence_of` with respective conditional validations, and they work as expected.

In fact, when I switch the above spec to `not_to validate_presence_of`, it runs successfully.

```
validates_presence_of :first_name, maximum: 44, if: Proc.new { |u| !u.cook? }
```
```
it "doesn't execute the validation" do
  expect(user).not_to validate_presence_of(:first_name)
end
```

```
Finished in 0.37833 seconds (files took 7.92 seconds to load)
1 example, 0 failures
```

Thoughts?   All help is appreciated.

```
rails (7.0.3.1)
rspec-rails (6.0.1)
rspec-core (~> 3.11)
rspec-expectations (~> 3.11)
rspec-mocks (~> 3.11)
rspec-support (~> 3.11)
ruby 3.1.2p20
shoulda-matchers (5.2.0)
```

**Comment by mcmire** [comment]
When you use `validate_length_of` you need to specify the expected length. In theory this matcher should give you an error; the fact that it does not is a bug. In any case, try saying: 

``` ruby
it "doesn't execute the validation" do
  expect(user).not_to validate_length_of(:first_name).is_at_most(44)
end
```

**Comment by ndouglasma** [comment]
Thanks for the prompt response! I totally understand and will make sure to specify the length moving forward!

**Comment by mcmire** [comment]
No problem, glad I could help!
