### ISSUE TITLE
Uniqueness matcher does not account for custom error messages

### ISSUE THREAD

**Issue by osingaatje** [thoughtbot/shoulda-matchers#1572]
Hi, small annoyance for me, but the `validate_uniqueness_of` matcher only checks if the error message is **exactly** 
`has already been taken`. 

This means I either have to write a custom matcher for uniqueness, or I cannot have custom uniqueness error messages.

Example:
`validates :name, uniqueness: { message: 'Conflicting ScimPlatform name: "%{value}".' }`

This fails the test with:
![screenshot of failed test](https://github.com/thoughtbot/shoulda-matchers/assets/46380170/694a322c-b3ba-4486-8046-b931493221dc)

Maybe it'd be an idea to check that it either starts or ends with 'has already been taken'? This would still allow for custom error messages, as long as developers include the string at the beginning or end

**Comment by matsales28** [comment]
Hi! Thanks for opening this issue.

In cases where you use custom messages, you should use the `with_message` qualifier on the matcher. So, for your example:
```ruby
it { shoulda validate_uniqueness_of(:name).with_message("Conflicting ScimPlatform name...") }
```

Can you test that way?

**Comment by osingaatje** [comment]
It works, thank you!
