### ISSUE TITLE
`belong_to` optional check breaks custom validation 

### ISSUE THREAD

**Issue by thisismydesign** [thoughtbot/shoulda-matchers#1652]
### Description

```rb
class Model < ApplicationRecord
  belongs_to :content
  belongs_to :placement

  validate :custom_validation

  def custom_validation
    return if content.publisher_id == placement.publisher_id
  end
end

RSpec.describe Model do
  subject(:model) { create(:model) }

  it { is_expected.to belong_to(:content) }
end
```

This test case fails with `undefined method 'publisher_id' for nil`. It caused me some headaches until I realized this was because the `belong_to` matcher was testing for `optional`, making the association `nil`.

But this is a super confusing and unexpected error for a valid use case.

I don't want to litter my codebase with checks for the associations being present when `belongs_to` is already making sure. In fact if I do `return if content.nil? || placement.nil?` it will still fail due to the validation failing.

### System configuration
**shoulda_matchers version**: 6.2.0
**rails version**: 7.1.3
**ruby version**: 3.3.2

**Comment by matsales28** [comment]
Hi @thisismydesign, can you check #1524? But summarizing the `belong_to` matcher double-checks the presence of a `content` in your case. It does this by setting `content` to nil and confirming that your model has errors. When it does this, your other validation runs, and if you do not have a check for content, it raises an error.

I'm closing this issue.
