### ISSUE TITLE
ensure_inclusion_of(...).in_array(...) can't cope with 0 in array

### ISSUE THREAD

**Issue by dolzenko** [thoughtbot/shoulda-matchers#179]
Assuming you have something like

```
validates :state_id, inclusion: { in: [0,1,2] }
```

spec setup as

```
it { should ensure_inclusion_of(:state_id).in_array([0,1,2]) }
```

will fail. This won't happen if array doesn't contain 0 element

**Comment by tom-lord** [comment]
With regards to the [true, false] issue:

As of shoulda-matchers v2.7.0+, you can change the code:

    it { is_expected.to ensure_inclusion_of(:foo).in_array [true, false] }

To:

        it { is_expected.to validate_inclusion_of(:foo).in_array [true, false] }

And this test now passes. However (!!!) it will also print the following warning message:

************************************************************************
Warning from shoulda-matchers:

You are using `validate_inclusion_of` to assert that a boolean column
allows boolean values and disallows non-boolean ones. Be aware that it
is not possible to fully test this, as boolean columns will
automatically convert non-boolean values to boolean ones. Hence, you
should consider removing this test.
************************************************************************
