### ISSUE TITLE
validate_presence_of throws wrong number of arguments error on Class inherit from ActiveResource::Base

### ISSUE THREAD

**Issue by cseydel** [thoughtbot/shoulda-matchers#348]
Hi,
got an error with version 2.3.0 that hasn't occured in previous versions:

```
class Klass < ActiveResource::Base
    extend  ActiveModel::Callbacks
    include ActiveModel::MassAssignmentSecurity
    include ActiveModel::Validations::Callbacks

    validates :arg1, :arg2, :presence => true
    # ...
end
```

tested with

```
describe Klass do
    it { should validate_presence_of(:arg1) }
    it { should validate_presence_of(:arg2) }
end
```

throws with shoulda 3.5.0 and shoulda-matchers 2.3.0 following error:

```
Failure/Error: it { should validate_presence_of(:arg1) }
     ArgumentError:
       wrong number of arguments (1 for 0)
```

```
Failure/Error: it { should validate_presence_of(:arg2) }
     ArgumentError:
       wrong number of arguments (1 for 0)
```

Are there any suggestions or things I've been missing?
Best Christoph

**Comment by fabianoalmeida** [comment]
Hi @mcmire! I'm facing exactly the same problem. I'm using `shoulda-matchers (3.1.2)` and Rails 5. I tried with this:
```ruby
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :rails
  end
end
```
in `spec/rails_helper.rb` file and nothing.

Do you have any suggestion?

**Comment by mcmire** [comment]
@fabianoalmeida What's the error you're getting and what's the backtrace?

**Comment by taka41s** [comment]
same here,

  227) ConsumptionLimit is expected to validate that :warehouse cannot be empty/falsy
       Failure/Error: it { should validate_presence_of(:warehouse) }
       
       ArgumentError:
         wrong number of arguments (given 3, expected 1..2)
       # /bundle/ruby/3.2.0/gems/mask_validator-0.2.3/lib/mask_validator.rb:27:in `validate_each'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validator.rb:96:in `perform_validation'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validator.rb:89:in `validation_result'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validator.rb:85:in `validation_error_messages'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validator.rb:64:in `messages'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validator.rb:25:in `has_messages?'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validator.rb:55:in `messages_match?'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validator.rb:21:in `call'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:38:in `matches?'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:24:in `each'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:24:in `detect'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:24:in `first_passing'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:536:in `public_send'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:536:in `run'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:401:in `does_not_match?'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/disallow_value_matcher.rb:32:in `matches?'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validation_matcher.rb:179:in `run_allow_or_disallow_matcher'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validation_matcher.rb:103:in `disallows_value_of'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb:258:in `disallows_original_or_typecast_value?'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb:180:in `block in matches?'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb:179:in `all?'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb:179:in `matches?'
       # ./spec/models/consumption_limit_spec.rb:19:in `block (2 levels) in <top (required)>'

**Comment by taka41s** [comment]
same here, 
`  227) ConsumptionLimit is expected to validate that :warehouse cannot be empty/falsy
       Failure/Error: it { should validate_presence_of(:warehouse) }
       
       ArgumentError:
         wrong number of arguments (given 3, expected 1..2)
       # /bundle/ruby/3.2.0/gems/mask_validator-0.2.3/lib/mask_validator.rb:27:in `validate_each'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validator.rb:96:in `perform_validation'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validator.rb:89:in `validation_result'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validator.rb:85:in `validation_error_messages'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validator.rb:64:in `messages'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validator.rb:25:in `has_messages?'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validator.rb:55:in `messages_match?'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validator.rb:21:in `call'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:38:in `matches?'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:24:in `each'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:24:in `detect'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:24:in `first_passing'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:536:in `public_send'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:536:in `run'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:401:in `does_not_match?'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/disallow_value_matcher.rb:32:in `matches?'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validation_matcher.rb:179:in `run_allow_or_disallow_matcher'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validation_matcher.rb:103:in `disallows_value_of'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb:258:in `disallows_original_or_typecast_value?'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb:180:in `block in matches?'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb:179:in `all?'
       # /bundle/ruby/3.2.0/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb:179:in `matches?'
       # ./spec/models/consumption_limit_spec.rb:19:in `block (2 levels) in <top (required)>'
`

**Comment by thadeu** [comment]
same here guys

```rb
(byebug) is_expected.to(validate_presence_of(:api_url))
*** ArgumentError Exception: wrong number of arguments (given 3, expected 1..2)
```
