### ISSUE TITLE
Problems when running specs with Zeus

### ISSUE THREAD

**Issue by gylaz** [thoughtbot/shoulda-matchers#384]
I'm using `[zeus]`(https://github.com/burke/zeus) to pre-load the code, for when I'm running specs. It appears that zeus isn't properly requiring `shoulda-matchers` library for some reason.

I see errors like this:

``` bash
  1) User validations and associations
     Failure/Error: it { should belong_to(:account) }
     NoMethodError:
       undefined method `belong_to' for #<RSpec::Core::ExampleGroup::Nested_3:0x00000104b8d850>
     # ./spec/models/user_spec.rb:8:in `block (2 levels) in <top (required)>'
     # -e:1:in `<main>'

  2) User validations and associations
     Failure/Error: it { should accept_nested_attributes_for(:account) }
     NoMethodError:
       undefined method `accept_nested_attributes_for' for #<RSpec::Core::ExampleGroup::Nested_3:0x00000104b94f88>
     # ./spec/models/user_spec.rb:9:in `block (2 levels) in <top (required)>'
     # -e:1:in `<main>'

  3) User validations and associations
     Failure/Error: it { validate_presence_of(:account) }
     NoMethodError:
       undefined method `validate_presence_of' for #<RSpec::Core::ExampleGroup::Nested_3:0x00000104b9c800>
     # ./spec/models/user_spec.rb:10:in `block (2 levels) in <top (required)>'
     # -e:1:in `<main>'
```

**Comment by grammakov** [comment]
same issue on 3.0.0 alpha, rolling back to 2.8.0 solves issue

**Comment by mcmire** [comment]
That's because shoulda-matchers no longer installs itself into your test framework, you'll need to add this to your rails_helper:

``` ruby
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :rails
  end
end
```

**Comment by SergeyBukhman** [comment]
Still getting this when running with zeus: 

NoMethodError: undefined method `belong_to' for #<RSpec::ExampleGroups::Business::AssociationSpecs:0x007fba5722d580>

I added require: false as suggested, it didn't help

**Comment by mcmire** [comment]
@SergeyBukhman Are you experiencing this on 2.8.0 or 3.0.0.alpha?

**Comment by SergeyBukhman** [comment]
2.8.0

**Comment by laptite** [comment]
(using rails 4.2.1 and shoulda-matchers 2.8.0)

To get it to work, I added a support file with the following:
```
RSpec.configure do |config|
  config.include Shoulda::Matchers
end
```

**Comment by SergeyBukhman** [comment]
Works now. Added `require 'shoulda/matchers'` to rails_helper. Not even sure how this worked before without this. Pretty confused about the whole thing, but it works with zeus.

**Comment by mcmire** [comment]
Zeus does the same thing that Spring does: it preloads your gems (as well as your Rails env). You need to prevent shoulda-matchers from preloading b/c otherwise it gets preloaded before RSpec does, so it doesn't automatically mix itself into your example groups. That's why there's a [two-step process](https://github.com/thoughtbot/shoulda-matchers#installation) in the README. You shouldn't have to `include` anything extra in your rails_helper.rb

**Comment by jwgoh** [comment]
```ruby
group :test do
   gem 'shoulda-matchers', require: false
end
```
The above works for me. Funnily enough it has been working for other developers.

**Comment by kriskhaira** [comment]
Adding `require: false` to the Gemfile declaration and `require 'shoulda/matchers` to rails_helper.rb worked for me. I'm on shoulda-matchers 2.8.0, Rails 4.2.1, Ruby 2.1.2.

**Comment by usamanoman** [comment]
version 2.8.0 solved my problem.

**Comment by sylvinho81** [comment]
version 2.8.0 solved my problem.

**Comment by nkchouhan** [comment]
It is working for me
```
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :rails
  end
end
```

**Comment by CUnknown** [comment]
Make sure you have `type: :model` as argument of the describe call in the model spec files.

**Comment by matrinox** [comment]
:+1: Add `require: false` to `gem 'shoulda-matchers', require: false` worked for me

Moving the gems around didn't, same with the requires. Thanks!

**Comment by perryqh** [comment]
@CUnknown suggestion of ```type: :model``` worked for me in an engine-gem.

**Comment by kdmcclin** [comment]
I'm on Rails 4.1.6 and shoulda-matchers 3.1.1 and I had to do the new configuration as described in the [official documentation](http://matchers.shoulda.io/docs/v3.1.1/) and the `describe Category, type: :model do` bit mentioned above.
