### ISSUE TITLE
Route with symbol for default format cannot match

### ISSUE THREAD

**Issue by brianhempel** [thoughtbot/shoulda-matchers#454]
In Rails 4, the default `format` route parameter may have been set to a symbol, but because shoulda stringifies the expected parameters given, it is impossible to match a route with a default `format` set to a symbol.

```ruby
namespace :api, defaults: {format: :json} do
  resources :user
end
```

Try to match it and you will get an unhelpful error, like:

```
       <{"format"=>"json",
        "action"=>"show",
        "controller"=>"api/users"}> expected but was
       <{"format"=>:json,
        "action"=>"show",
        "controller"=>"api/users"}>
```

Even crazier, when you switch from back and forth from a symbol to a string in your tests, the error message alternates between the first and the second hash containing the symbol value.

A temporary fix is to use the RSpec `route_to` matcher, which does not stringify the values.

**Comment by maurogeorge** [comment]
@mcmire I think we can close this since the #693 was merged. :smile:

**Comment by mcmire** [comment]
Is this issue really a year old? :grimacing: 

Closed.
