### ISSUE TITLE
`validate_uniqueness_of` doesn't support associations

### ISSUE THREAD

**Issue by gberger** [thoughtbot/shoulda-matchers#459]
Model:

    class Exam < ActiveRecord::Base
      belongs_to :course
      validates_presence_of :year, :semester, :course

      # Unique on all columns at the same time
      validates_uniqueness_of :course, scope: [:year, :semester]
    end

Test:

    describe Exam do
      it { should belong_to(:course) }
      it { should validate_presence_of(:year) }
      it { should validate_presence_of(:semester) }
      it { should validate_presence_of(:course) }
    end

This explodes, throwing **NoMethodError: undefined method `attributes' for nil:NilClass**.

However, if I change the validation to this:

      validates_uniqueness_of :year, scope: [:course, :semester]

It works.

**Comment by mcmire** [comment]
@hiasinho is right -- if you're validating uniqueness of an association, you need to add `allow_nil: true` to the validation, since the result of reading the association may be `nil` (if there's no connection).

However, even with this change I don't think the uniqueness matcher would work, since it doesn't support associations, only foreign keys. I'll rename the issue to match.

**Comment by sergiopantoja** [comment]
+1

Seems like the issue might be with [this method](https://github.com/thoughtbot/shoulda-matchers/blob/a3fb06c369c2b5e96831cb2c6c8532de8e2f0e62/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb#L352-L359) and [this method](https://github.com/thoughtbot/shoulda-matchers/blob/a3fb06c369c2b5e96831cb2c6c8532de8e2f0e62/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb#L368-L374).

`value_for_new_record` returns the String `a`.
`create_record_in_database ` tries to assign `a` to the attribute.

With Rails 4.1, ActiveRecord throws an AssociationTypeMismatch. It's expecting an instance of the association, but we're passing it a String instead.

**Comment by sergiopantoja** [comment]
#535 looks like the same problem.

**Comment by mcmire** [comment]
That's a good point. I'll close this issue in favor of that one.
