### ISSUE TITLE
NoMethodError when testing with join_table

### ISSUE THREAD

**Issue by Willux** [thoughtbot/shoulda-matchers#476]
I have the following line in my code:
`has_and_belongs_to_many :future_cars,  :join_table => :users_future_cars,  :class_name => "Car"`

The test line is
`it { should have_and_belong_to_many(:future_cars).join_table(:users_future_cars).class_name("Car") }`, but for some reason this throws the following error:
```
Failure/Error: it { should have_and_belong_to_many(:future_cars).join_table(:users_future_cars).class_name("Car") }
     NoMethodError:
       undefined method `reflect_on_association' for NilClass:Class
```

All the tables do exist and everything works with manual testing.

**Comment by maurogeorge** [comment]
@mcmire I think we can close this, since the https://github.com/thoughtbot/shoulda-matchers/commit/af85ac1f0e5b9a267efd4c05b30a73fe2f44d84e was merged, the full PR to get more context https://github.com/thoughtbot/shoulda-matchers/pull/556.

**Comment by mcmire** [comment]
You're right, thanks!
