### ISSUE TITLE
uninitialized constant Shoulda::Matchers::ActiveRecord

### ISSUE THREAD

**Issue by eirc** [thoughtbot/shoulda-matchers#480]
This happens when `ActiveRecord` is not defined so it's matchers [are not required](https://github.com/thoughtbot/shoulda-matchers/blob/v2.6.0/lib/shoulda/matchers.rb#L13) but `ActiveSupport::TestCase` is defined and [tries to include them](https://github.com/thoughtbot/shoulda-matchers/blob/v2.6.0/lib/shoulda/matchers/integrations/test_unit.rb#L22)

I think this is referred to by this https://github.com/thoughtbot/shoulda-matchers/issues/408#issuecomment-40191487 too

**Comment by Anyoks** [comment]
I had the same issue `uninitialized constant Shoulda` while running on circle CI. My problem was the `Gemfile`. I had the shoulda gem in the development environment on my local machine and test on circle and so the  `shoulda-matchers` gem was not loading in cirlcle ci. If you run in to this, make sure you have the gem in the right environment.

```
group :test do
   gem 'factory_bot_rails', '~> 4.0'
   gem 'shoulda-matchers', '~> 3.1' # make sure it's in the right environment, test? development?
   gem 'faker'
   gem 'database_cleaner'
   gem 'rubocop-rspec'
   gem 'rspec_junit_formatter'
end
```
