### ISSUE TITLE
validate_numericality_of on failure may not provide the reason for failure

### ISSUE THREAD

**Issue by mcmire** [thoughtbot/shoulda-matchers#509]
Given this validation

``` ruby
validates :ano, numericality: { only_integer: true, greater_than_or_equal_to: 1900 }
```

and this test:

``` ruby
it { should validate_numericality_of(:ano).is_greater_than_or_equal_to(1900) }
```

It will fail with:

```
Did not expect errors  when ano is set to 1900.000000000001, got error:
```

As you can see the failure message doesn't contain the validation error.

I believe this is because none of the submatchers for ValidateNumericalityOfMatcher set a default message.

Really, all of the submatchers should share the same message, and updating that message should propagate to all submatchers.

**Comment by maurogeorge** [comment]
@mcmire I think we can close this issue. The specific matcher has the correct message today as you can see [here](https://github.com/thoughtbot/shoulda-matchers/blob/97488690910520ed8e1f2e164b1982eff5ef1f19/spec/unit/shoulda/matchers/active_model/validate_numericality_of_matcher_spec.rb#L373-L375).

In all this [file](https://github.com/thoughtbot/shoulda-matchers/blob/97488690910520ed8e1f2e164b1982eff5ef1f19/spec/unit/shoulda/matchers/active_model/validate_numericality_of_matcher_spec.rb) we have assertions on the message, just search for `fail_with_message_including`.

And the submatchers has the test for his messages too [1](https://github.com/thoughtbot/shoulda-matchers/blob/97488690910520ed8e1f2e164b1982eff5ef1f19/spec/unit/shoulda/matchers/active_model/numericality_matchers/comparison_matcher_spec.rb#L220-L235), [2](https://github.com/thoughtbot/shoulda-matchers/blob/97488690910520ed8e1f2e164b1982eff5ef1f19/spec/unit/shoulda/matchers/active_model/numericality_matchers/even_number_matcher_spec.rb#L30-L35), [3](https://github.com/thoughtbot/shoulda-matchers/blob/97488690910520ed8e1f2e164b1982eff5ef1f19/spec/unit/shoulda/matchers/active_model/numericality_matchers/odd_number_matcher_spec.rb#L30-L35) and [4](https://github.com/thoughtbot/shoulda-matchers/blob/97488690910520ed8e1f2e164b1982eff5ef1f19/spec/unit/shoulda/matchers/active_model/numericality_matchers/only_integer_matcher_spec.rb#L40-L45).

**Comment by mcmire** [comment]
The code does look correct (I'd expected [this][1] to be present and indeed it is, and has been there for a while), but I'd like to verify this in a test, though, because I think we only test the message partially. 

[1]: https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb#L383

**Comment by maurogeorge** [comment]
@mcmire I started this on https://github.com/maurogeorge/shoulda-matchers/commit/5710a641f858a604f9bc2b26eeb57cb7bcfba7e6. But I think I got a [issue](https://github.com/maurogeorge/shoulda-matchers/commit/5710a641f858a604f9bc2b26eeb57cb7bcfba7e6#diff-d7c315235a16eb29151b8251207fbd67R538) when we test against two or more qualifiers and the fail qualifier is not the last in the chain of methods, the message is showed like:

> Expected errors to include "must be an integer" when attr is set to 0.1,
> got errors:

The cause of the error is not showed.

**Comment by maurogeorge** [comment]
@mcmire I think we can close this since the #699 was merged :smile:

**Comment by mcmire** [comment]
Yes, you're right :)
