### ISSUE TITLE
compatible with rspec 3.0.0 ?

### ISSUE THREAD

**Issue by zhu1230** [thoughtbot/shoulda-matchers#519]
Shoulda::Matchers::ActiveRecord::AssociationMatcher implements a legacy RSpec matcher
       protocol. For the current protocol you should expose the failure messages
       via the `failure_message` and `failure_message_when_negated` methods.

any idea? thanks

**Comment by mcmire** [comment]
@xl1004v Are you still experiencing issues with 2.8.0?

**Comment by maurogeorge** [comment]
@mcmire I think we can close this.

I double checked and we have defined the alias properly. 
@matiasleidemer replied that got no warning on `2.7.0`
The last reply when this was a problem was 5 months ago.

I think we can close for now, and reopen if we got new reports on it.

**Comment by mcmire** [comment]
@maurogeorge Yeah, that sounds like a good plan. Closing.

**Comment by mcmire** [comment]
I actually need to go back through and remove all the aliases since we're technically just targeting RSpec 3 now.

**Comment by jankeesvw** [comment]
I am seeing this error too.

**Comment by mcmire** [comment]
Which RSpec version and which shoulda-matchers version?

**Comment by maurogeorge** [comment]
@mcmire today what is your idea to the `shoulda-matcher` integration with RSpec 2? Is to [drop support](https://github.com/thoughtbot/shoulda-matchers/issues/519#issuecomment-90161242)? Or [keep the support](https://github.com/thoughtbot/shoulda-matchers/issues/519#issuecomment-42686507)?

I vote for keep support like the [clearence did](https://github.com/thoughtbot/clearance/pull/460).

**Comment by mcmire** [comment]
@maurogeorge In 3.0, we've dropped support for RSpec 2, and no longer support it.

**Comment by maurogeorge** [comment]
@mcmire thanks, I missed this on News.
