### ISSUE TITLE
validates_uniqueness_of fails in Postgresql with text columns

### ISSUE THREAD

**Issue by fj** [thoughtbot/shoulda-matchers#521]
If I validate against a `text` Postgresql field in a model that has only a single uniqueness validator, like this:

```ruby
class Organization < ActiveRecord::Base
  validates :slug, :uniqueness => { :allow_nil => true }
end
```

then I get this:

```
  1) Organization validations should require case sensitive unique value for slug
     Failure/Error: it { expect(subject).to validate_uniqueness_of :slug }
     ActiveRecord::StatementInvalid:
       PG::UndefinedFunction: ERROR:  operator does not exist: text = integer
       LINE 1: ...ROM "organizations"  WHERE "organizations"."slug" = 0 LIMIT ...
                                                                    ^
       HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
       : SELECT  1 AS one FROM "organizations"  WHERE "organizations"."slug" = 0 LIMIT 1
```

This seems to occur because shoulda-matchers sets the field to `0`, but this is not a valid value without a typecast in Postgresql. It will work if the migration is for a `string` (`character varying(255)`), however.

**Comment by mcmire** [comment]
Hi @fj, I just pushed a fix for this to master -- if you can, do you mind running your tests against it and let me know if you're still seeing this bug?
