### ISSUE TITLE
using scope with have_and_belong_to_many association throws "wrong number of arguments" in Rails 4.1.2

### ISSUE THREAD

**Issue by monfresh** [thoughtbot/shoulda-matchers#549]
In Rails 4.1.1, this works fine:

``` ruby
it { is_expected.to have_and_belong_to_many(:categories).order('oe_id asc') }
```

In Rails 4.1.2, it raises ArgumentError:

```
Failure/Error: it { is_expected.to have_and_belong_to_many(:categories).order('oe_id asc') }
     ArgumentError:
       wrong number of arguments (1 for 0)
```

Not sure what's causing this, but there seem to be many fixes related to `has_and_belongs_to_many` in the Changelog:
https://github.com/rails/rails/blob/v4.1.2/activerecord/CHANGELOG.md

**Comment by graysonwright** [comment]
@mcmire I inherited @monfresh's Code for America application, which was the source of this bug. Let me know if I can help debug it at all.

**Comment by graysonwright** [comment]
Specifically, https://github.com/sfbrigade/ohana-api/blob/master/spec/models/service_spec.rb#L29

**Comment by mcmire** [comment]
@graysonwright Oh, sweet! I had no idea. Okay, I'll revisit this when I get a chance.

**Comment by monfresh** [comment]
@graysonwright I've actually removed that proc from the [Service model](https://github.com/codeforamerica/ohana-api/blob/master/app/models/service.rb#L12) as I realized it's not needed. If you fetch the latest code from the ohana-api repo, you won't need this test anymore.

**Comment by graysonwright** [comment]
@monfresh thanks for the heads up!

**Comment by guialbuk** [comment]
Shoulda-matchers 3.1.2 is the last that supports Rails 4.1, so future development will continue on #981 .
