### ISSUE TITLE
'example at' message

### ISSUE THREAD

**Issue by SaimonL** [thoughtbot/shoulda-matchers#570]
Hi guys excellent work as usual.
I have this issue, when I run the test I get messages success green message "example at" when I run the command 
"rspec spec/models/section_spec.rb"

<pre>
example at ./spec/models/section_spec.rb:10
example at ./spec/models/section_spec.rb:16
example at ./spec/models/section_spec.rb:13
example at ./spec/models/section_spec.rb:20
example at ./spec/models/section_spec.rb:17
example at ./spec/models/section_spec.rb:19
example at ./spec/models/section_spec.rb:9
example at ./spec/models/section_spec.rb:15
example at ./spec/models/section_spec.rb:21
</pre>

Code:

<pre>
    it { expect validate_presence_of(:name) }
    it { expect ensure_length_of(:name).is_at_least(4) }
    it { expect validate_uniqueness_of(:name) }

    it { expect validate_presence_of(:description) }
    it { expect ensure_length_of(:description).is_at_least(10) }
    it { expect validate_uniqueness_of(:description) }
</pre>

How do I get the full message like i used to.

Possible cause:

My Rspec configuration:

<pre>
  if config.files_to_run.one?
    config.default_formatter = 'doc'
  end
</pre>

My .rspec file

<pre>
--color
--require spec_helper
</pre>

Version I am using: 

Rails 4.1.4
Ruby 2.1.2p95
rspec (3.0.0)
rspec-context-private (0.0.1)
rspec-core (3.0.3)
rspec-expectations (3.0.3)
rspec-mocks (3.0.3)
rspec-rails (3.0.2)
rspec-support (3.0.3)
shoulda (3.5.0)
shoulda-context (1.2.1)
shoulda-matchers (2.6.2)

If you need more info please let me know.

**Comment by MPV** [comment]
@SaimonL: Were you able to get the expected output when using the `is_expected.to` syntax? I tried changing from `should` to `is_expected.to` but I am still getting the same output ever since I upgraded to RSpec 3:

 `example at ./spec/models/user_spec.rb:5`
 `example at ./spec/models/user_spec.rb:6`
 `example at ./spec/models/user_spec.rb:7`
 `example at ./spec/models/user_spec.rb:8`

**Comment by SaimonL** [comment]
Yes thank you very much as always. I did get the correct output by using is_expected syntax. You can close this issue.

**Comment by mcmire** [comment]
@MPV What's the exact RSpec version that you're using?

**Comment by MPV** [comment]
@mcmire I'm using `gem 'rspec', '~> 3.0'` and my Gemfile.lock is showing `rspec (3.0.0)`.

Here you can see which shoulda(-matchers) version I am using:

    $ grep shoulda Gemfile*    
    Gemfile:       gem 'shoulda'
    Gemfile.lock:    shoulda (3.5.0)
    Gemfile.lock:      shoulda-context (~> 1.0, >= 1.0.1)
    Gemfile.lock:      shoulda-matchers (>= 1.4.1, < 3.0)
    Gemfile.lock:    shoulda-context (1.2.1)
    Gemfile.lock:    shoulda-matchers (2.8.0)
    Gemfile.lock:  shoulda

**Comment by MPV** [comment]
Note: I get this issue when I run RSpec from within RubyMine. I just tried running it with `bundle exec rspec --format documentation` now and it worked as intended. Any idea what might cause this? 

My .rspec file:

    --color
    --format Fuubar

I will also try changing from `Fuubar` to `documentation` when I get back to development and see if that changes anything.

**Comment by mcmire** [comment]
What does `rspec -v` (so, without `bundle exec`) output?

What version of Ruby does RubyMine use? What's the gem path that it uses?

**Comment by MPV** [comment]
$ rspec -v
    3.0.4

Screenshot of RubyMine SDK/Gems settings:
https://www.dropbox.com/s/c4qod0hm7tnlq82/Sk%C3%A4rmklipp%202015-02-23%2022.30.45.png?dl=0
(Ruby 2.0.0 and rspec 3.0.0?)

Gem path, not sure. It seems to have picked up my RVM settings as it should, using it's gemset?

**Comment by MPV** [comment]
Looking closer at the RubyMine output of running RSpec gives us more interesting info:

    /Users/vs/.rvm/rubies/ruby-2.0.0-p0/bin/ruby -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) /Users/vs/.rvm/gems/ruby-2.0.0-p0@bls/bin/rspec /Users/vs/src/rbls/spec --require teamcity/spec/runner/formatter/teamcity/formatter --format Spec::Runner::Formatter::TeamcityFormatter --pattern **/*_spec.rb

So it turns out that RubyMine uses it's own TeamcityFormatter. 

This here below is probably the corresponding bug?
https://youtrack.jetbrains.com/issue/RUBY-15519

**Comment by mcmire** [comment]
@MPV Yeah, that makes a lot of sense actually. The formatter would need to read the description of a test after running it, not before.

**Comment by SaimonL** [comment]
```bash
rspec -v
3.2.1
```

**Comment by rui-ribeiro** [comment]
Hi!

If anyone is searching for the solution, where it is: https://gist.github.com/rui-ribeiro/21108feecd0c3e85d32415eb2f1e1adf
