### ISSUE TITLE
validate_uniqueness_of matcher tests out of range value for bigint column postgresql

### ISSUE THREAD

**Issue by sanemat** [thoughtbot/shoulda-matchers#573]
I'm using bigint in postgresql 9.3, and use validate_uniqueness_of matcher, then I get out of range postgresql error.

I set `validates :uuid, uniqueness: true, presence: true`, and schma.rb:

```ruby
# schema.rb
  create_table "builds", force: true do |t|
    t.integer "uuid",    limit: 8, null: false
  end

  add_index "builds", ["uuid"], name: "index_builds_on_uuid", unique: true, using: :btree
```

I got error below:
```text
     Failure/Error: it { is_expected.to validate_uniqueness_of :uuid }
     ActiveRecord::StatementInvalid:
       PG::NumericValueOutOfRange: ERROR:  value "11820096777168289209" is out of range for type bigint
       : INSERT INTO "builds" ("uuid") VALUES ($1) RETURNING "id"
```
[postgresql bigint range](http://www.postgresql.org/docs/9.3/static/datatype-numeric.html) `-9223372036854775808 to +9223372036854775807`

My environments:
```
activemodel (4.1.5)
shoulda-matchers (2.6.2)
ruby 2.1.2p95
psql (PostgreSQL) 9.3.1
```

**Comment by mcmire** [comment]
@sanemat I just took a look at this issue and am not able to reproduce it. Do you mind pointing to master (or, alternatively, 2.7.0) and re-running your test against that?

**Comment by sanemat** [comment]
@mcmire Thanks for your confirming. I don't reproduce this. It works!

related fix?
https://bitbucket.org/ged/ruby-pg/src/b60c89ee93c8d3afa2e15b4916aba3f25907a830/History.rdoc?at=default#cl-14

**Comment by mcmire** [comment]
@sanemat Oh... hmm... interesting. Yeah, maybe!
