### ISSUE TITLE
ensure_inclusion_of does not work with polymorphic attributes

### ISSUE THREAD

**Issue by gnilrets** [thoughtbot/shoulda-matchers#574]
So I had `ensure_inclusion_of` working just fine, then I migrated some things to use FactoryGirl instead of explicit create statements and suddenly it's failing.  If I `dup` the object created by FactoryGirl, it works again.  Here's an example in my spec:

``` ruby
  before { @job_spec = FactoryGirl.create(:job_spec) }
  subject { @job_spec }

  it { should ensure_inclusion_of(:job_template_type).in_array(JobSpec::JOB_TEMPLATE_TYPES) }

  context "using a copy to get around ensure_inclusion_of bug" do
    before { @job_spec_dup = @job_spec.dup }
    subject { @job_spec_dup }

    it { should ensure_inclusion_of(:job_template_type).in_array(JobSpec::JOB_TEMPLATE_TYPES) }
  end
```

The first test fails, the second is successful:

```
JobSpec
  should ensure inclusion of job_template_type in ["TplBirstSoapGenericCommand", "TplBirstDuplicateSpace"] (FAILED - 1)
  using a copy to get around ensure_inclusion_of bug
    should ensure inclusion of job_template_type in ["TplBirstSoapGenericCommand", "TplBirstDuplicateSpace"]

Failures:

  1) JobSpec should ensure inclusion of job_template_type in ["TplBirstSoapGenericCommand", "TplBirstDuplicateSpace"]
     Failure/Error: it { should ensure_inclusion_of(:job_template_type).in_array(JobSpec::JOB_TEMPLATE_TYPES) }
     NameError:
       wrong constant name shouldamatchersteststring
     # ./spec/models/job_spec_spec.rb:19:in `block (2 levels) in <top (required)>'

Finished in 0.3576 seconds (files took 1.73 seconds to load)
15 examples, 1 failure

Failed examples:

rspec ./spec/models/job_spec_spec.rb:19 # JobSpec should ensure inclusion of job_template_type in ["TplBirstSoapGenericCommand", "TplBirstDuplicateSpace"]
```

**Comment by cindyward1** [comment]
Using Ruby 2.1.5, Rails 4.2.0, and Shoulda-Matchers 2.8.0, shoulda-matchers also fails trying to validate_inclusion_of [:user] for resource_type in the popular 'rolify' gem. The Role class:

class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, join_table: :users_roles
  belongs_to :resource, polymorphic: true
  validates :resource_type,
            inclusion: { in: [:user] },
            allow_nil: true
  scopify
end

My attempted validation of validates_inclusion_of(:resource_type):
it { should validate_inclusion_of(:resource_type).in_array([nil, "user"]) }

The error message I get (it doesn't matter whether or not I include nil in the array):
Failures:
  1) Role should ensure inclusion of resource_type in [nil, "user"]
     Failure/Error: it { should validate_inclusion_of(:resource_type).in_array([nil, "user"]) }
       [nil, "user"] doesn't match array in validation

(If I use only ["user"], the error I get is the expected ["user"] doesn't match array in validation)

I added some puts in the shoulda-matcher code to try to figure out what was going on:
allows_all_values_in_array @array = [nil, "user"]
allows_all_values_in_array: @low_message = nil
allows_all_values_in_array: true, , 
allows_all_values_in_array: @low_message = nil
allows_all_values_in_array: false, user, 
matches_for_array: false true true true

(If I use only ["user"], the output is:
allows_all_values_in_array @array = ["user"]
allows_all_values_in_array: @low_message = nil
allows_all_values_in_array: false, user, 
matches_for_array: false true true true)

My next attempted validation using allows_value doesn't work either:
Failures:
  1) Role should allow resource_type to be set to "user"
     Failure/Error: it { should allow_value("user").for(:resource_type) }
       Did not expect errors when resource_type is set to "user",
       got errors:
       * "is not included in the list" (attribute: resource_type, value: "user")

(Note that "Role should allow resource_type to be set to nil" does validate correctly, as would be expected from the output above.)

**Comment by mcmire** [comment]
@cindyward1 Doesn't `resource_type` take the name of a class as a value, and not a symbol? What if you say:

``` ruby
validates :resource_type, inclusion: { in: ['User'] }, allow_nil: true
```

and then to test it:

```
should validate_inclusion_of(:resource_type).in_array('User').allow_nil
```

**Comment by cindyward1** [comment]
What you sent me works fine and explains why resource_type is always NULL in my development database. I misunderstood how to modify the Role class. Thanks for finding my bug ... Cindy
 

     On Tuesday, February 17, 2015 9:18 AM, Elliot Winkler <notifications@github.com> wrote:
   

 @cindyward1 Doesn't resource_type take the name of a class as a value, and not a symbol? What if you say:validates :resource_type, inclusion: { in: ['User'] }, allow_nil: trueand then to test it:should validate_inclusion_of(:resource_type).in_array('User').allow_nil

**Comment by NamrataSoni20** [comment]
Try this , It works for me 
it do
    should validate_inclusion_of(:resource_type)
              .in_array(Rolify.resource_types)
              .allow_nil(true)
  end

**Comment by amnesia7** [comment]
@mcmire I think I'm hitting this issue as well.
I'm using ruby v2.4.1, rails v5.1.4 and shoulda-matchers v3.1.2
```
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :favourable, polymorphic: true

  validates_presence_of :user_id, :favourable_id, :favourable_type
  validates :favourable_type, inclusion: { in: %w[Project],
                                           message: "%{value} can't be favourited" }
```
Rspec tests:
```
  context 'validation' do
    let!(:user) { create(:user) }
    let!(:project) { create(:project) }
    let!(:favourite_project) { user.favourites.build(favourable: project) }

    context 'favourable type' do
      specify 'valid type' do
        expect(favourite_project).to validate_inclusion_of(:favourable_type)
          .in_array(%w[Project])
      end
    end
  end
```
Error thrown:
```
     NameError:
       wrong constant name shoulda-matchers test string
```

**Comment by mcmire** [comment]
@amnesia7 Cool, thanks for reporting this :) This is definitely something we need help fixing.

**Comment by amnesia7** [comment]
Let me know if you need any more info or need anything testing, or if there's anything straight forward that I can help with to get this resolved.

Col

--------------------------------------------
On Thu, 26/10/17, Elliot Winkler <notifications@github.com> wrote:

 Subject: Re: [thoughtbot/shoulda-matchers] ensure_inclusion_of does not work with polymorphic attributes (#574)
 To: "thoughtbot/shoulda-matchers" <shoulda-matchers@noreply.github.com>
 Cc: "amnesia7" <col.gibson@gmail.com>, "Mention" <mention@noreply.github.com>
 Date: Thursday, 26 October, 2017, 21:12
 
 @amnesia7 Cool, thanks
 for reporting this :) This is definitely something we need
 help fixing.
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by cickes** [comment]
Still present in 2019.  Will see if I can help.

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!

**Comment by LucasCarrias** [comment]
Any update regarding this issue?

**Comment by mcmire** [comment]
No update, but if you can come up with a fix for this then we'd be happy to merge it in!

**Comment by danderozier** [comment]
If you're testing a lot of models with polymorphic associations, you can use [rspec helpers](https://relishapp.com/rspec/rspec-core/docs/helper-methods/define-helper-methods-in-a-module) to DRY things up a bit:

```ruby
# spec/support/model_helpers.rb

module ModelHelpers
  def all_models_except(*models)
    ApplicationRecord.subclasses.map(&:to_s) - models
  end
end

# spec/models/your_model.rb

it { should_not allow_value(*all_models_except('Foo', 'Bar').for(:whatever_type) }

```
