### ISSUE TITLE
Problem with Rails 3.2.21 and Ruby 2.0.0

### ISSUE THREAD

**Issue by timoschilling** [thoughtbot/shoulda-matchers#633]
I (@activeadmin) have a problem with `shoulda-matchers 2.7.0` used with `rails 3.2.21` on ruby `2.2.0`.

The specs raises:
```
/home/travis/build/activeadmin/activeadmin/bundle/ruby/2.2.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require': cannot load such file -- test/unit/testcase (LoadError)
```
([Full stacktrace on Travis](https://travis-ci.org/activeadmin/activeadmin/builds/45350100#L285))

The same test are passing on `rails 3.2.21` with ruby `2.1.x` and `rails 4.1.x` on ruby `2.2.0`.

Here is the travis job for all details: https://travis-ci.org/activeadmin/activeadmin/builds/45350100

**Comment by mcmire** [comment]
@timoschilling I'm not able to load that Travis build as it keeps hanging. But, [someone else][] got the same message when they were running tests. Are you sure this isn't just a warning? Was it actually causing the test to fail?

[someone else]: https://github.com/thoughtbot/shoulda-matchers/pull/632#issuecomment-68455923

**Comment by timoschilling** [comment]
Here is a other Travis build with failing tests on 2.2: https://travis-ci.org/activeadmin/activeadmin/jobs/46036675

**Comment by JuanitoFatas** [comment]
rails/rails#18306 got merged.

**Comment by lucianosousa** [comment]
Awesome! Just waiting the new version here.
:wine_glass:

**Comment by mcmire** [comment]
Yeah but it sounds like they won't release this until they have to come out with a security fix for 3.2 and therefore have to release a new version. So I wonder how soon it will be until this will actually work.

**Comment by mcmire** [comment]
Since Rails is no longer releasing any updates for Rails 3.2, we are dropping support for it. Sorry :(

**Comment by dfurber** [comment]
I came here with a similar problem, and thought, what if I put "  gem 'test-unit'" in my Gemfile. Voila.

**Comment by flanger001** [comment]
I came here with the exact same problem and realized I should have asked @dfurber!

**Comment by mikz** [comment]
Or if you don't want old test-unit, you can use https://github.com/iGEL/test-unit-minitest that actually ports the test-unit / minitest wrapper from Ruby 2.1.
