### ISSUE TITLE
NoMethodError: undefined method `flash'

### ISSUE THREAD

**Issue by osiro** [thoughtbot/shoulda-matchers#636]
Hey guys,

Not sure if it's only me, but I'm getting the following error with the matcher `set_flash`.

```bash
NoMethodError:
  undefined method `flash' for #<ActionController::TestResponse>
.../shoulda-matchers-2.8.0.rc1/lib/shoulda/matchers/action_controller/set_flash_matcher.rb:242:in `copy_of_flash_from_controller'
.../shoulda-matchers-2.8.0.rc1/lib/shoulda/matchers/action_controller/set_flash_matcher.rb:238:in `flash'
.../shoulda-matchers-2.8.0.rc1/lib/shoulda/matchers/action_controller/set_flash_matcher.rb:230:in `flash_values'
.../shoulda-matchers-2.8.0.rc1/lib/shoulda/matchers/action_controller/set_flash_matcher.rb:209:in `sets_the_flash?'
.../shoulda-matchers-2.8.0.rc1/lib/shoulda/matchers/action_controller/set_flash_matcher.rb:187:in `matches?'
```

Using:

* Rails 4.2.0
* rspec-rails 3.1.0
* Ruby 2.2.0
* shoulda-matchers-2.8.0.rc1

It works fine when replacing the following piece of code: https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/action_controller/set_flash_matcher.rb#L243 with:

```ruby
def copy_of_flash_from_controller
  @controller.request.flash.dup.tap do |flash|
    copy_flashes(@controller.request.flash, flash)
    copy_discard_if_necessary(@controller.request.flash, flash)
    sweep_flash_if_necessary(flash)
  end
end
```

I was about to Pull Request the changes but l've got a bunch of failing specs when testing against Ruby 2.2.0 (as per https://github.com/thoughtbot/shoulda-matchers/pull/632).

Happy 2015! :tada: :tada: :tada:

**Comment by mcmire** [comment]
This is odd, as I just merged in some fixes for Rails 4.2 into master and the tests seem to pass. I'll look into this further, though.

**Comment by mcmire** [comment]
Hi @osiro, I just looked into this more closely. The error you're getting appears that you're using `set_flash` against the `response` object, as in:

```
expect(response).to set_flash(...)
```

Is this true? If so, you're not supposed to do that -- use it on the `controller` object instead:

```
expect(controller).to set_flash(...)
```

**Comment by mcmire** [comment]
I'm going to close this since it's been a while since you've responded. If you're still experiencing issues with this, let me know and I'll reinvestigate.

**Comment by osiro** [comment]
@mcmire you're right, `expect(response).to set_flash(...)` seems to work, thanks!
