### ISSUE TITLE
use_before_filter documentation not appearing in Github pages documentation.

### ISSUE THREAD

**Issue by georgemillo** [thoughtbot/shoulda-matchers#638]
I just learned about the new `use_before_filter`, `use_around_filter` etc matchers from [the Thoughtbot blog](http://robots.thoughtbot.com/shoulda-matchers-2-6-0]), but I'm surprised to find that they're not mentioned anywhere in the existing README file or in the [2.7.0 documentation](https://thoughtbot.github.io/shoulda-matchers/v2.7.0/).

Seems like the documentation does exist [within the module itself](https://github.com/thoughtbot/shoulda-matchers/blob/v2.7.0/lib/shoulda/matchers/action_controller/callback_matcher.rb) - can we get this added to the 'main' documentation?

**Comment by mcmire** [comment]
Thanks for bring this to my attention! I totally didn't know. It's in the README now and should be published in the official documentation in the next release.
