### ISSUE TITLE
Check 2.8.0 release against real projects

### ISSUE THREAD

**Issue by mcmire** [thoughtbot/shoulda-matchers#644]
- [x] C40
- [x] https://github.com/sungwoncho/wingFind
- [x] Ello

**Comment by lucianosousa** [comment]
two things here:

1:
```
************************************************************************
Warning from shoulda-matchers:

set_the_flash is deprecated and will be removed in the next major
release. Please use set_flash instead.
************************************************************************
```
My terminal print this a lot of times. why not just put an alias?

2:
```
     Failure/Error: expect(subject.errors.full_messages).to include("custom message")
       expected ["custom message"] to include "custom message"
```

;)

**Comment by mcmire** [comment]
1. I could add an alias, but I don't want to keep the method around in 3.0, because I don't want people to use it. I'm bringing `set_the_flash` and `set_session` closer together, because they're basically the same concept.

2. This is weird, I'm not sure why you're getting this error...

**Comment by lucianosousa** [comment]
wow. 2 is also broke on v2.7 here. my mistake.

I can assume in the project I've more related things with shoulda-matchers everything is fine
