### ISSUE TITLE
Feature Request: support for RSpec 3 composable matchers

### ISSUE THREAD

**Issue by soupmatt** [thoughtbot/shoulda-matchers#645]
RSpec 3 added the ability to compose matchers together like this:
```ruby
expect(3).to eq(3).and be < 4
```
It would be nice if the shoulda-matchers would support this. There is a `RSpec::Expectations::Composable` module that you can include to add support for this, but I noticed there is not superclass on which to do this in a centralized place.

**Comment by mcmire** [comment]
@soupmatt Can you give an example on how you'd like to use shoulda-matchers in a composable way?

**Comment by mcmire** [comment]
I'm going to close this as we don't tend to leave feature requests open unless there's a PR, but if you have ideas I'm all ears.
