### ISSUE TITLE
#permit is broken on rails 4.2

### ISSUE THREAD

**Issue by ryanong** [thoughtbot/shoulda-matchers#648]
When stubbing strong parameters it breaks `#require` to not return a child key.

```ruby
params = ActionController::Parameters.new({"course" => { "foo" => "bar"}})
params.require(:course) #=> { "course" => { "foo" => "bar" } }
# it should return  { "foo" => "bar" }
```

**Comment by mcmire** [comment]
Hmm... okay. I see why this is -- we need to spy on `#permit` on the object that `#require` returns, not on the entire `params` object. Thanks for the report.
