### ISSUE TITLE
undefined method `flash` for #<ActionController::TestResponse>

### ISSUE THREAD

**Issue by mecampbellsoup** [thoughtbot/shoulda-matchers#649]
When using the `set_flash` matcher as so:

```ruby
context "when a new default payment is created" do
  subject { post :create, new_card }

  it { is_expected.to set_flash[:notice].to("Credit card successfully added.") }
```

... this exception is raised: `NoMethodError: undefined method 'flash' for #<ActionController::TestResponse:0x007fc14a328a08>`

This usage is acceptable, however, and does not raise an exception:

```ruby
context "when a new default payment is created" do
  before { post :create, new_card }

  it { is_expected.to set_flash[:notice].to("Credit card successfully added.") }
```

This issue is that when explicitly setting `subject { post :create, new_card }`, the `set_flash` assertion is being made on RSpec's `TestResponse` object instead of the `PaymentsController` (the implicit subject when simply using `before` to fire the request).

When using an explicit subject as I'm trying to do, perhaps this matcher could inspect the request's headers to identify the controller and make the assertion on `PaymentsController` under the hood:

```ruby
input> subject.headers
=> {"X-Frame-Options"=>"SAMEORIGIN",
 "X-XSS-Protection"=>"1; mode=block",
 "X-Content-Type-Options"=>"nosniff",
 "Location"=>"http://test.host/payments",
 "Set-Cookie"=>"request_method=POST; path=/",
 "Content-Type"=>"text/html; charset=utf-8"}
```

Is this a feature that the maintainers of this gem would be interested in? If so, I'll add test coverage and write the code.

**Comment by mcmire** [comment]
Well, I don't think that using `get`, `post`, etc. inside of a `subject` block makes sense. It's not the response that should set the flash, it's the controller. Is there a reason why you're setting the response object to the subject and not the controller? Perhaps you have other tests in the same context block?

**Comment by mecampbellsoup** [comment]
You don't think it makes sense to say the following: "This POST request to the controller we're testing is expected to set `flash[:notice]` to `<expectation>`"? That seems sensible enough to me. That said, after researching a bit it does seem there's a debate about whether that's a code smell or not.

The main reason is that setting `subject` to the response instead of the controller allows me to DRY up my code and use RSpec's nice DSL in ways like this (out of context example but the point still stands):

```ruby
context "when the current user is the trip's whale" do
  it { is_expected.to redirect_to trip_ticket_path(trip, ticket) }
end
```

**Comment by mcmire** [comment]
Do you have to set the subject to the response, though? I think that all of the rspec-rails matchers should work with controllers, too.

**Comment by mcmire** [comment]
I'm closing this due to lack of response, but feel free to continue the discussion.

**Comment by jordanmaguire** [comment]
Updated one of my company's old projects version of shoulda and ran into this issue. Since it took a couple seconds of thought to work out what was going on here - the error being reported is because the `set_flash` matcher is expecting the `subject` to have a `#flash` method implemented.

The solution is to test the controller object directly. In RSpec:

```ruby
subject
expect(controller).to set_flash[:alert].to("I like turtles").
```

**Comment by mecampbellsoup** [comment]
@jordanmaguire Can you just make assertions on the `response` object or na?

**Comment by jordanmaguire** [comment]
@mecampbellsoup Nope:

```
undefined method `flash' for #<ActionController::TestResponse:0x007fff19df47b8>

**Comment by mecampbellsoup** [comment]
Cool, thanks @jordanmaguire :+1:
