### ISSUE TITLE
undefined method `on' for validate_numericality_of

### ISSUE THREAD

**Issue by rodolfospalenza** [thoughtbot/shoulda-matchers#678]
Hello,

I'm try use shoulda matchers for testing validates uniqueness when object is updated. My validation in model is like this:

```ruby```
validates :priority, uniqueness: { scope: :product_id }, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, on: :update
```

Teste:

```ruby
it { is_expected.to validate_numericality_of(:priority).only_integer.is_greater_than_or_equal_to(0).on(:update) }
```

When I run test I saw this error.

```
     Failure/Error: it { is_expected.to validate_numericality_of(:priority).only_integer.on(:update).is_greater_than_or_equal_to(0) }
     NoMethodError:
       undefined method `on' for #<Shoulda::Matchers::ActiveModel::ValidateNumericalityOfMatcher:0x007fc1cf1734a8>
     # ./spec/models/adena/product/sku_spec.rb:9:in `block (2 levels) in <module:Adena>'
     # ./lib/adena/common/spec/rails_helper.rb:32:in `block (2 levels) in <top (required)>'
```

Thanks.

**Comment by mcmire** [comment]
Yup, this is a known issue, first raised in #246 and #356. We're working on it for the next release.
