### ISSUE TITLE
Undefined method respond_with for namespaced controller spec

### ISSUE THREAD

**Issue by razasayed** [thoughtbot/shoulda-matchers#684]
I have a namespaced controller for an Api, and when i use the `should respond_with` matcher in the spec for the same , i get the message ```undefined method `respond_with' for #<RSpec::ExampleGroups::ApiV1UsersController::GETShow:0x007fd30e4a5c20>```

The spec i have is as follows :

```ruby
describe Api::V1::UsersController, type: :controller do
  describe "GET #show" do
    before(:each) do
      @user = create(:user)
      get :show, id: @user.id, format: :json
    end

   it {  should respond_with 200 }
  end
end
```

I have added the rspec-rails gem before the shoulda-matchers gem in my Gemfile. Also, my users controller is located in app/controllers/api/v1/users_controller.rb and the spec in spec/controllers/api/v1/users_controller_spec.rb .

**Comment by razasayed** [comment]
Had added the shoulda-matchers gem only to test group in Gemfile, instead of both development and test. It works after its added to both groups. Closing this ticket.

**Comment by CharlesJQuarra** [comment]
"instead of both development and test. It works after its added to both groups."

why should a rspec matcher be added to development group? that doesn't make any sense, it should be test only. Also I'm having this issue with rails 4.2.0 and adding to both groups does NOT solve it

**Comment by ajohns13** [comment]
I'm having the same error with rails 4.2.4 as well

**Comment by fake-or-dead** [comment]
I have found this error before

and found this one about configure (that I thinks newly add in new versions)
https://github.com/thoughtbot/shoulda-matchers#configuration

so I add this to spec_helper.rb
```
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    # Choose a test framework:
    with.test_framework :rspec
    with.library :rails
  end
end
```

hope this help

**Comment by jsvelasquezv** [comment]
I was having the same problem and solve it using your method. Thank you

**Comment by oseifrimpong** [comment]
I added this and it worked!

    Shoulda::Matchers.configure do |config|
       config.integrate do |with|
       # Choose a test framework:
       with.test_framework :rspec
      with.library :rails
       end
  end

**Comment by artdias90** [comment]
+1 for the fix

**Comment by SupremeA** [comment]
+1 for that fix Thanks!

**Comment by vinsy** [comment]
+1

**Comment by adinsley** [comment]
I needed this fix to get shoulda-matcher working with rspec as well

**Comment by daltondiaz** [comment]
Thanks, fix the problem with **respond_with** o/

**Comment by ecdfernandes** [comment]
+1 😎

**Comment by harshal2802** [comment]
I also had same problem.. and solved it by adding 

Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    # Choose a test framework:
    with.test_framework :rspec
    with.library :rails
  end
end

to spec_helper.rb

thanks for the fix :)

**Comment by JohnBDonner** [comment]
Thanks! @fake-or-dead

**Comment by GabrielCabrera** [comment]
Had the same problem, but following the tip from @fake-or-dead it was solved.

```ruby
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    # Choose a test framework:
    with.test_framework :rspec
    with.library :rails
  end
end
```

But according to the link https://github.com/thoughtbot/shoulda-matchers#rspec it must go in `rails_helper.rb`

**Comment by thomascarterx** [comment]
Same thing here. Like @GabrielCabrera said it has to go in rails_helper.rb

**Comment by BKSpurgeon** [comment]
@GabrielCabrera yes gotta go in rails_helper

**Comment by hiendinhngoc** [comment]
the @GabrielCabrera 's solution worked for me, thanks

**Comment by domanhtien2011** [comment]
@fake-or-dead , I appreciate your solutions. It helps me a lot. Have a great day.

**Comment by huskynation** [comment]
Make sure to add outside of the Rspec.configure do block. Works like a charm!

``` ruby
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    # Choose a test framework:
    with.test_framework :rspec
    with.library :rails
  end
end
```
