### ISSUE TITLE
Using described_class syntax results in unexpected class lookup behavior

### ISSUE THREAD

**Issue by stephaneliu** [thoughtbot/shoulda-matchers#686]
Using rspec 3.2.0 and shoulda-matchers 2.5.0.
   
    class Lookup < ActiveRecord::Base
      belongs_to :referencer, polymorphic: true
    end

    Rspec.describe Lookup do
      it 'has belongs_to relationship' do
        expect(referenced_class).to belong_to(:referencer)
      end
    end
Result:
`NoMethodError: undefined method 'reflect_on_association' for Class:Class`

But expect(subject).to belong_to(:referencer) => 0 failures

**Comment by mcmire** [comment]
The association matchers were designed to have a succinct syntax. In other words, here you can simply say:

``` ruby
it { should belong_to(:referencer) }
```

Are you saying that you'd like to use the model instead?

**Comment by stephaneliu** [comment]
Understood.

`it { is_expected.to belong_to(:referencer) }`

Thanks.

**Comment by mcmire** [comment]
Yup, or that too :)
