### ISSUE TITLE
`validates_numericality_of` does not work with `on` context matcher

### ISSUE THREAD

**Issue by mateusg** [thoughtbot/shoulda-matchers#698]
When I try to run `expect(model).to validate_numericality_of(:attribute).on :create`, it gives me this error:
```ruby
NoMethodError:
       undefined method `on' for #<Shoulda::Matchers::ActiveModel::ValidateNumericalityOfMatcher:0x007fae94901290>
```
Going through the code, I can see that `ValidateNumericalityOfMatcher` no longer inherits from `ValidationMatcher`, which is the class that contains this submatcher.

I think this commit caused this: 6ba8c9f1.

I'm currently using:
- shoulda-matchers 2.7.0
- Rails 4.2.1
- RSpec 3.1.0
- Ruby 2.2.1

Any thoughts on how to fix it? I think the inheritance was removed for a reason, so I shouldn't just add it back, right?

I will have more time to look at this on the weekend and maybe send a PR.

**Comment by mcmire** [comment]
Yup, your deduction is correct, and it's a known issue (that we've unfortunately left standing for a while): #356, #358. 

I finally sat down and worked on incorporating some of those suggested changes a couple days ago, though. I'll have a fix soon in master. I can cut an alpha release after that so you can use it, although note you'll have to update your spec helper.

**Comment by mateusg** [comment]
:+1:

**Comment by mcmire** [comment]
It's in master now (97488690910520ed8e1f2e164b1982eff5ef1f19), so I'll close this. I think I'm nearing an rc release for 3.0 so you should be able to use it soon.
