### ISSUE TITLE
about Readme

### ISSUE THREAD

**Issue by masciugo** [thoughtbot/shoulda-matchers#700]
Just point out that:

`gem 'shoulda'`

and

`Shoulda::Matchers.configure ....`

are incompatible. You need to be on the edge:

`gem 'shoulda-matchers', github: 'thoughtbot/shoulda-matchers'`

or configure some other way.

**Comment by mcmire** [comment]
I know. This is why it says "This is the README for the master branch" at the top :)

**Comment by masciugo** [comment]
sorry, my bad. It's one of those things you don't expect from our best friend: README file! ... above all when it's written by thoughtbot, always so accurate. Thanks for sharing.
