### ISSUE TITLE
validate_uniqueness scoped_to doesn't work for non-associations

### ISSUE THREAD

**Issue by kruszczynski** [thoughtbot/shoulda-matchers#702]
I have an `Order` model that has a `date` column. So I tried to write the following test:
```
validate_uniqueness_of(:from).scoped_to(:date)
```
That did not work as expected, I got the following error:
```
ActiveRecord::StatementInvalid: PG::UndefinedFunction: ERROR:  operator does not exist: date = integer
LINE 1: ... WHERE ("orders"."from" = 'a' AND "orders"."date" = 1) LIMIT...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

I might take a swing at fixing this, the question is should I?

**Comment by mcmire** [comment]
Yeah, this is a known issue for 2.8.0. It's fixed in master, we just haven't issued a new release just yet. We hope to issue some kind of pre-release version soon.

**Comment by kruszczynski** [comment]
Cool! I guess this issue can be closed and I'm waiting.
