### ISSUE TITLE
Any plans to include matcher for AMS?

### ISSUE THREAD

**Issue by npearson72** [thoughtbot/shoulda-matchers#707]
With Rails api being released, do you guys have any plans for adding matchers for active_model_serializer?

Would be great if you did! :+1:

**Comment by mcmire** [comment]
We don't have any plans for AMS matchers... do you have any suggestions on what you'd want?

**Comment by npearson72** [comment]
I currently made my own that look like this:

````
RSpec::Matchers.define :have_attribute do |key|
  match do |actual|
    actual = actual.attributes
    actual.keys.include?(key) && (value.present? ? actual[key] == value : true)
  end
  chain :with_value, :value
end

RSpec::Matchers.define :have_many_serialized do |key|
  match do |actual|
    actual.associations[key].present?
  end
end

RSpec::Matchers.define :have_one_serialized do |key|
  match do |actual|
    actual.associations[key].present?
  end
end
````

But thought it would be nice if something like this is included in the shoulda matchers since I already use this gem.

Do you think AMS is out of scope for the gem?

**Comment by mcmire** [comment]
No, not necessarily. The concern is not that this feature would be out of scope, but that it may not be used widely within the company. We're the primary users of shoulda-matchers, so any new functionality has to be evaluated in this context: is this something that most of us would use on a regular basis? If that's not the case, then the feature may not be designed well or may not be as maintained as well as other, more popular features.

I have yet to ask around within the company, but so far my sense is, I'm not sure we tend to test serializers like this. Serializers tend to be tested implicitly by request specs -- if the route responds with the right format, then we can assume the serializer is working like it should. Now of course if there's a method within the serializer that does something sufficiently complex, then I'd probably add a test for that. But so far I haven't felt a need for testing basic stuff like attributes or associations.

So this is a good suggestion, but I think I'd prefer to take a "wait and see" stance on this.

**Comment by npearson72** [comment]
Sounds good.

I do wonder what your rationale is for not testing attributes and associations on serializers but testing them on models.

Also, do you typically test data in your end-points? I usually test my model scopes and service objects rather thoroughly and when it comes to controllers am mostly concerned with methods getting called, variable assignments, response codes, and response data types (not the data structure itself). Just curious about your thinking to go further if you do -- and if that might be influenced by testing serializers.
