### ISSUE TITLE
have_and_belong_to_many looking for wrong join table

### ISSUE THREAD

**Issue by patmbolger** [thoughtbot/shoulda-matchers#711]
I have a model that looks like this (partial listing):

class MenuCategory < ActiveRecord::Base
  has_and_belongs_to_many :menus
  has_and_belongs_to_many :menu_items
end

And this spec:

it { is_expected.to have_and_belong_to_many :menu_items }

The spec throws this exception:

"Expected MenuCategory to have a has_and_belongs_to_many association called menu_items (join table **menu_categories_items** doesn't exist)"

This *should* be looking for the table: **menu_categories_menu_items**.

**Comment by patmbolger** [comment]
I was incorrect in the expected behavior of this shoulda matcher.  It is actually working correctly, given the behavior of the [association method](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_and_belongs_to_many): "If your tables share a common prefix, it will only appear once at the beginning. For example, the tables “catalog_categories” and “catalog_products” generate a join table name of “catalog_categories_products”."

**Comment by mcmire** [comment]
Cool. This doesn't appear to be a bug, then -- mind if I close?

**Comment by patmbolger** [comment]
Yes, please close as there is no bug (other then user error :) )
