### ISSUE TITLE
`allow_blank` signature in `validate_uniqueness_of` is different from that in `validate_inclusion_of`

### ISSUE THREAD

**Issue by PikachuEXE** [thoughtbot/shoulda-matchers#721]
I prefer the one with optional argument

**Comment by mcmire** [comment]
Yeah, we should probably make them all optional. We should still use the explicit form in documentation, though -- I'd rather new people notice the close correlation between the matcher and the validation/association.

**Comment by PikachuEXE** [comment]
Need PR?

**Comment by mcmire** [comment]
Yup, that would be great.

**Comment by PikachuEXE** [comment]
#722 opened

**Comment by mcmire** [comment]
Thanks!

**Comment by mcmire** [comment]
Closing this in favor of #722.
