### ISSUE TITLE
set_flash does not accept a symbol as key on 3.0.0.rc1

### ISSUE THREAD

**Issue by maurogeorge** [thoughtbot/shoulda-matchers#728]
My spec is:

```ruby
post :create, params
is_expected.to set_flash[:notice].to(/sucesso/)
```
My controller redirect is

```ruby
redirect_to root_path, notice: 'Resposta criada com sucesso!'
```

This works on 2.7 but when I update to 3.0.0.rc1 the specs fail.
If I change the the key to a string the specs pass.

```ruby
post :create, params
is_expected.to set_flash['notice'].to(/sucesso/)
```
I think the expected behavior is that we accept string and symbol as keys.

**Comment by mcmire** [comment]
Okay, that's a good catch.

**Comment by mcmire** [comment]
Closing this issue in favor of #732.
