### ISSUE TITLE
Should we add in #have_foreign_key now that Rails 4.2 supports foreign key constraints?

### ISSUE THREAD

**Issue by rickarubio** [thoughtbot/shoulda-matchers#730]
Rails 4.2 adds foreign key support to the migration DSL http://edgeguides.rubyonrails.org/4_2_release_notes.html

What do you think about creating a new ActiveRecord matcher, `#have_foreign_key` ?

I've been browsing through the source trying to implement this, however the first road block I run into is that by default all specs are run with a sqlite3 database.

I see that in `support/tests/database_adapters` we have classes for sqlite3 and postgresql.

My problem is that all specs seem to run with `sqlite3` as the default due to `database.rb` having:

`ADAPTER_NAME = ENV.fetch('DATABASE_ADAPTER', 'sqlite3').to_sym`

Is there anyway to run a spec file with a postgresql database instead of a sqlite3 database selectively?

I'd like to make a file called `have_foreign_key_matcher_spec.rb` for example and have the specs in this entire file run with a postgresql db.

How could I do this?

Any help appreciated, also do you think adding in a shoulda matcher for `#have_foreign_key` is a good idea? Because if it's not, no point in trying to figure this out :-)

Thanks!

**Comment by mcmire** [comment]
I think this has been suggested before, but let me run this by my coworkers and get some opinions on this first.

**Comment by jferris** [comment]
I don't use the existing database matchers (`have_db_column`, `have_db_index`), so I don't think I'd use this matcher. I don't feel like testing the database schema improves the design of any of the classes or realistically catches regressions.

**Comment by rickarubio** [comment]
Closing issue as there is not much interest for the proposed matcher.
