### ISSUE TITLE
Preferred way to handle matchers with conflicting names

### ISSUE THREAD

**Issue by ramontayag** [thoughtbot/shoulda-matchers#742]
I'm using https://github.com/adambarber/active_model_serializers-matchers to test `ActiveModel::Serializer`. The gem has matchers called `have_many` and `has_one` which conflict with `shoulda-matchers`.

What's the preferred way to handle the conflict? I was thinking that `shoulda-matchers`' ActiveRecord matchers only get included when there's a spec type of `:model` (and the corresponding appropriate version in MiniTest). However, since this would probably break a lot of people's specs, perhaps turning on an option in `shoulda-matchers` like `.load_libs_only_with_type_defined!`

**Comment by mcmire** [comment]
There isn't currently a way to resolve this, but including the matchers into certain example groups is something we can definitely do in the upcoming 3.0.

**Comment by ramontayag** [comment]
Ok cool thanks. :) I'll leave this up to you to close.

**Comment by mcmire** [comment]
Okay, matchers are now only mixed into certain example groups, so if you have an example group that isn't in spec/models or spec/controllers and isn't tagged, then you are free to bring in whichever other matchers you like.

(af98a23091551fb40aded5a8d4f9e5be926f53a9, 8cf449b4ca37d0d7446d2cabbfa5a1582358256d)
