### ISSUE TITLE
undefined method `on' for .. StrongParametersMatcher

### ISSUE THREAD

**Issue by benoittgt** [thoughtbot/shoulda-matchers#748]
Hello

I'm having something like

```ruby
def update
    @user = User.find params[:id]
    @user.update_attributes user_params
end
...
private
def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
end
```

Rspec : 
```ruby
    let(:new_email) { "marcel@kittel.com" }
    let(:password) { "XsghgJUwwyooCT8X" }
    let(:params) { {email: new_email, first_name: user.first_name, last_name: user.last_name} }

    it do
      should permit(:first_name, :last_name, :email, :password).
        for(:update, params: params).on(:user)
    end
```

```
Failure/Error: for(:update, params: params).on(:user)
     NoMethodError:
       undefined method `on' for #<Shoulda::Matchers::ActionController::StrongParametersMatcher:0x007fb0b5942420>
```

**Comment by maurogeorge** [comment]
Hi @benoittgt,

what version are you using? The qualifier `on` is defined only on the [3.0.0.rc](https://github.com/thoughtbot/shoulda-matchers/blob/master/NEWS.md#features).

If you are before 3.0.0.rc1, you can take a look at the 2.8 [doc here](https://github.com/thoughtbot/shoulda-matchers/blob/v2.8.0/lib/shoulda/matchers/action_controller/strong_parameters_matcher.rb).

But you are good to go only with:

```ruby
    it do
      should permit(:first_name, :last_name, :email, :password).
        for(:update, params: params)
    end
```

If you are not on 3.0.0.rc1.

**Comment by benoittgt** [comment]
It's a problem in the request. Removing `on(:user)`.

```
Failure/Error: should permit(:first_name, :last_name, :email, :password).
ActionController::UrlGenerationError:
 No route matches {:action=>"update", :controller=>"api/v1/users"}
```

I've tried something like : 
```ruby
it do
    should permit(:first_name, :last_name, :email, :password).
        for(:update, store_id: store.id, id: user.id, user: params, format: format, verb: :patch)#.on(:user)
end
```

My other tests have this request : 
```ruby
subject { xhr :patch, :update, store_id: store.id, id: user.id, user: params, format: format }
```

**Comment by maurogeorge** [comment]
Hi @benoittgt 

This probably will solve your problem:

```ruby
it do
  user_params =  { first_name: 'Jon', last_name: 'Doe',
                   email: 'jon@example.com', password: 'password' }
  params = { store_id: store.id, id: user.id, user: user_params }
  should permit(:first_name, :last_name, :email, :password).
    for(:update, params: params)
end

```
We need to send the params to a params key first, and do not need format and verb, verb is only needed to handle an action that isn't one of the seven resourceful actions.

I think only this is enough:

```ruby
it do
  params = { store_id: store.id, id: user.id }
  should permit(:first_name, :last_name, :email, :password).
    for(:update, params: params)
end
```

You are getting a `ActionController::UrlGenerationError:` because you are not sending the url params, with this last code you send only the url params.

**Comment by maurogeorge** [comment]
On the 3.0.0 we will need to send all params in the params hash, as you can see here https://github.com/thoughtbot/shoulda-matchers/pull/731

**Comment by benoittgt** [comment]
Awesome. It's work like a charm. Thanks a lot @maurogeorge
