### ISSUE TITLE
Support for allow_nil option to delegate_method matcher.

### ISSUE THREAD

**Issue by alejandrogutierrez** [thoughtbot/shoulda-matchers#749]
Hi everyone! I would like to add support for allow_nil option to delegate_method matcher.
```ruby
it { should delegate_method(:deliver).to(:post_office).allow_nil(true) }
```
What do you think?

**Comment by maurogeorge** [comment]
Hi @alejandrogutierrez I like the idea :+1: 

Just a note, I think it is better to not pass a param to `allow_nil`, but something like:

```ruby
it { should delegate_method(:deliver).to(:post_office).allow_nil }
```

Take a look [here](https://github.com/thoughtbot/shoulda-matchers/pull/722) where this was discussed.

I guess I never worked on this matcher code, but as you can see [here](https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/independent/delegate_method_matcher.rb) the matcher works with different kinds of delegation([Fowardable](http://ruby-doc.org/stdlib-2.0.0/libdoc/forwardable/rdoc/Forwardable.html), [delegate](http://api.rubyonrails.org/classes/Module.html#method-i-delegate) and methods) so I think we will need to handle this across all delegation and not only on the `delegate` from Rails. Makes sense to you?

Could you please send a PR?

**Comment by alejandrogutierrez** [comment]
Yes, it makes sense!
I will work on this and will send a PR as soon as possible.
Thanks!

**Comment by mcmire** [comment]
Closing in favor of #751.
