### ISSUE TITLE
Uninitialized constant ActiveSupport::TestCase

### ISSUE THREAD

**Issue by ybur-yug** [thoughtbot/shoulda-matchers#763]
When configuring shoulda-matchers in a small project I have, I have been unable to get things running at all. I am pointing to `3.0.0.rc1`.

This is my configuration:

```ruby
...
require 'shoulda/matchers'

Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :rails
  end
end
...
```

It is a typical rails project, and this is included in `spec/rails_helper.rb`.

When guard runs (or if I run manually its identical) my specs I get:

```
...
[gems path]/shoulda-matchers-a3fb06c369c2/lib/shoulda/matchers/integrations/libraries
/rails.rb:19:in `integrate_with': uninitialized constant ActiveSupport::TestCase (NameError)
```
(broke the lines and shortened path for readability)

I know its a release candidate but couldn't find another issue. For reference, I am on rails 4.2.3 and rspec 3.3.2. I can gladly provide any other information you would want or need.

**Comment by mcmire** [comment]
This seems odd to me... is there anything special about your setup? It shouldn't be looking for ActiveSupport::TestCase, but it shouldn't be failing to find it, either...

**Comment by ybur-yug** [comment]
This is a pretty boilerplate rails app. Was making it for a tutorial I'm doing at a beginners meetup. I since deleted the project and just required `2.8` in a new one and it worked fine.

Might not be worth keeping open? I can try to replicate and send you a repository if you think it is actionable, though.

:confounded:

**Comment by ybur-yug** [comment]
@mcmire I have done some research on this and put together a sample repository. So this is the exact setup I have in each situation:
`rspec 3.3.0`

`rspec-rails 3.3.3`

`shoulda-matchers 3.3.0.rc1`

Specific to these tests. The tests can be found in `spec/models/list_spec.rb` and `spec/models/task_spec.rb`. They are very simple:

```ruby
# list_spec.rb
describe List do
  it { is_expected.to validate_presence_of :name }
  it { is_expected.to have_many :tasks }
end

# task_spec.rb
describe Task do
  it { is_expected.to validate_presence_of :description }
  it { is_expected.to belong_to :list }
end
```
In this repository I have 2 commits. One with shoulda `3.3.0.rc1` and one with `2.8.0` where it is working.

[Commit With Error](https://github.com/ybur-yug/shoulda_bug_example/commit/854da1d4f52c93b3f7d4af34e2ee98fbefe19283)

Here the specific, full trace is:

```
bobby@devbox:~/code/rails_refresh/todos$ rspec spec/models/
[rvm path]/shoulda/matchers/integrations/libraries/rails.rb:19:in `integrate_with': uninitialized constant ActiveSupport::TestCase (NameError)
	[rvm path]/shoulda-matchers-a3fb06c369c2/lib/shoulda/matchers/integrations/configuration.rb:48:in `block (2 levels) in apply'
	[rvm path]/ruby-2.2.2/lib/ruby/2.2.0/set.rb:283:in `each_key'
	[rvm path]/ruby-2.2.2/lib/ruby/2.2.0/set.rb:283:in `each'
	[rvm path]/ruby-2.2.2/bundler/gems/shoulda-matchers-a3fb06c369c2/lib/shoulda/matchers/integrations/configuration.rb:48:in `block in apply'
	[rvm path]/ruby-2.2.2/lib/ruby/2.2.0/set.rb:283:in `each_key'
	[rvm path]/ruby-2.2.2/lib/ruby/2.2.0/set.rb:283:in `each'
	[rvm path]/shoulda-matchers-a3fb06c369c2/lib/shoulda/matchers/integrations/configuration.rb:46:in `apply'
	from /home/bobby/.rvm/gems/ruby-2.2.2/bundler/gems/shoulda-matchers-a3fb06c369c2/lib/shoulda/matchers/integrations/configuration.rb:9:in `apply'
	from /home/bobby/.rvm/gems/ruby-2.2.2/bundler/gems/shoulda-matchers-a3fb06c369c2/lib/shoulda/matchers/configuration.rb:16:in `integrate'
```

[Commit With Working Current Version of Gem](https://github.com/ybur-yug/shoulda_bug_example/commit/292801d5d0e7a6f631c93e2e683c8d616147cb38)

and running specs goes fine:

```
bobby@devbox:~/code/rails_refresh/todos$ rspec spec/models
....

Finished in 0.84229 seconds (files took 1.38 seconds to load)
4 examples, 0 failures

```
Let me know if there is anything I can do.

**Comment by mcmire** [comment]
What does your `rails_helper` looks like?

**Comment by mcmire** [comment]
You shouldn't be requiring shoulda-matchers in your spec_helper. The gem relies on Rails to have been loaded. That hasn't happened yet when spec_helper is loaded. You need to require and configure the gem in rails_helper instead.

**Comment by ybur-yug** [comment]
Ah, got it. Thanks.

**Comment by betesh** [comment]
I'm using shoulda-matchers outside of Rails, in a standalone ActiveRecord environment.  I need to configure the test environment before loading my application code.  Here's what worked for me:

    require "shoulda-matchers"
    Shoulda::Matchers.configure do |config|
      config.integrate do |with|
        with.test_framework :rspec

       # This require statement solves the LoadError
        require "active_record" 
        with.library :active_record
        with.library :active_model
      end
    end

**Comment by mcmire** [comment]
Yup! shoulda-matchers makes the assumption you've already required ActiveRecord. It doesn't make that require on its own anymore.

That would be a good error message to have.

**Comment by serixscorpio** [comment]
Thanks @betesh! I'm using shoulda-matchers outside of rails as well, using only ActiveModel.  Based on your feedback, I have this which worked:
```ruby
require "shoulda/matchers"
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
   # This require statement solves the uninitialized constant / NameError issue
    require "active_model" 
    with.library :active_model
  end
end
```
@mcmire Is this the recommended way?

**Comment by mcmire** [comment]
@serixscorpio Yup, that would work. You could put the require at the top so it doesn't get lost, but that's just a suggestion. (Also, FYI, you don't need to explicitly require shoulda-matchers anymore.)

**Comment by dchersey** [comment]
I'm running with shoulda-matchers 3.1.1 and also getting this reference. 
My rails_helper has 
```ruby
require 'spec_helper'
require 'shoulda/matchers'
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    # Choose a test framework:
    with.test_framework :rspec
    with.library :rails
  end
end
```

I am getting 

````
shoulda-matchers-3.1.1/lib/shoulda/matchers/integrations/libraries/rails.rb:20:in `integrate_with': uninitialized constant ActiveSupport::TestCase (NameError)
	from /Users/david/projects/feelwe/vendor/ruby/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/integrations/configuration.rb:48:in `block (2 levels) in apply'
	from /Users/david/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/set.rb:283:in `each_key'
	from /Users/david/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/set.rb:283:in `each'
	from /Users/david/projects/feelwe/vendor/ruby/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/integrations/configuration.rb:48:in `block in apply'
	from /Users/david/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/set.rb:283:in `each_key'
	from /Users/david/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/set.rb:283:in `each'
	from /Users/david/projects/feelwe/vendor/ruby/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/integrations/configuration.rb:46:in `apply'
	from /Users/david/projects/feelwe/vendor/ruby/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/integrations/configuration.rb:9:in `apply'
	from /Users/david/projects/feelwe/vendor/ruby/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/configuration.rb:16:in `integrate'
	from /Users/david/projects/feelwe/spec/rails_helper.rb:14:in `block in <top (required)>'
	from /Users/david/projects/feelwe/vendor/ruby/2.2.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/configuration.rb:5:in `configure'
	from /Users/david/projects/feelwe/spec/rails_helper.rb:13:in `<top (required)>'
	from /Users/david/projects/feelwe/vendor/ruby/2.2.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1295:in `require'
	from /Users/david/projects/feelwe/vendor/ruby/2.2.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1295:in `block in requires='
	from /Users/david/projects/feelwe/vendor/ruby/2.2.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1295:in `each'
	from /Users/david/projects/feelwe/vendor/ruby/2.2.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1295:in `requires='
	from /Users/david/projects/feelwe/vendor/ruby/2.2.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
	from /Users/david/projects/feelwe/vendor/ruby/2.2.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration_options.rb:108:in `each'
	from /Users/david/projects/feelwe/vendor/ruby/2.2.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
	from /Users/david/projects/feelwe/vendor/ruby/2.2.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration_options.rb:21:in `configure'
	from /Users/david/projects/feelwe/vendor/ruby/2.2.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:105:in `setup'
	from /Users/david/projects/feelwe/vendor/ruby/2.2.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:92:in `run'
	from /Users/david/projects/feelwe/vendor/ruby/2.2.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:78:in `run'
	from /Users/david/projects/feelwe/vendor/ruby/2.2.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/david/projects/feelwe/vendor/ruby/2.2.0/gems/rspec-core-3.4.2/exe/rspec:4:in `<top (required)>'
	from /Users/david/projects/feelwe/vendor/ruby/2.2.0/bin/rspec:23:in `load'
	from /Users/david/projects/feelwe/vendor/ruby/2.2.0/bin/rspec:23:in `<main>'
```

which comes from code:

```ruby
          def integrate_with(test_framework)
            Shoulda::Matchers.assertion_exception_class =
              ActiveSupport::TestCase::Assertion

            SUB_LIBRARIES.each do |name|
              library = Integrations.find_library!(name)
              library.integrate_with(test_framework)
            end
          end
```

I'm running Rails 4.2.5 and apparently I don't have this part of active support loaded. Not sure why, except that I generated the app using rspec and not test:unit.  

Any idea on what I can do to resolve this dependency, or why I need it in the first place?

Thanks!

**Comment by variousred** [comment]
@dchersey  I'm getting the exact same thing.

**Comment by dchersey** [comment]
I went back to 3.1.1 and added require: false to my gemfile and it resolved
my original issue of the matchers not being picked up. I am not sure what
is up with this latest release; it seems shoulda does not support it
(perhaps for this reason).

My gemfile now has:

 gem "shoulda", require: false
  gem 'shoulda-matchers', require: false

This gives me

  * shoulda (2.11.3)
  * shoulda-kept-assign-to (1.1.0)
  * shoulda-matchers (3.1.1)
Hope this helps!
