### ISSUE TITLE
Does exist a way to test ActiveRecord stores?

### ISSUE THREAD

**Issue by Angelmmiguel** [thoughtbot/shoulda-matchers#768]
Hello all!

I see there are a matcher for `serialize` macro, butI want to test `store` macro from [ActiveRecord::Store](http://api.rubyonrails.org/classes/ActiveRecord/Store.html).

Have the gem a method to test it or it's a planned functionality?

Thanks you!

**Comment by mcmire** [comment]
We don't plan on adding matchers for Store at this time.

What would you want to test? I personally feel like there wouldn't be that much to test. Perhaps the accessors, but I feel like you could do that easily manually if you really wanted to:

``` ruby
class User < ActiveRecord::Base
  store :settings, accessors: [ :color, :homepage ], coder: JSON
end

describe User do
  it "stores color settings" do
    user = User.new
    user.settings[:color] = "red"
    user.save!
    user.reload
    expect(user.color).to eq "red"
  end

  it "stores color settings" do
    user = User.new
    user.settings[:homepage] = "http://foo.com"
    user.save!
    user.reload
    expect(user.homepage).to eq "http://foo.com"
  end
end
```

Even so, I feel like these tests are bordering on testing Rails, and are probably not necessary, unless there was something custom going on.

**Comment by Angelmmiguel** [comment]
Yes, you are right, I test accessors as you said. But the thing I want to test is `coder`. Thanks for your response!

**Comment by mcmire** [comment]
If the thing you want to test is the coder, and you have a custom coder, then I feel like you should test that on its own. If coder works as `store` expects it to work, then `store` should work too.
