### ISSUE TITLE
How to set the class name of the intermediate association in has_many through?

### ISSUE THREAD

**Issue by AlexVPopov** [thoughtbot/shoulda-matchers#770]
I need something like this:
```ruby
RSpec.describe Expense, type: :model do
  it do
    should have_many(:tags).class_name('ActsAsTaggableOn::Tag')
                           .through(:taggings)
                           .class_name('ActsAsTaggableOn::Tagging')
  end
end
```

however I get:

> Expected Expense to have a has_many association called tags (, Expected tags to have tags through taggings, but got it through tag_taggings

How can I specify the class names for both classes?

**Comment by mcmire** [comment]
@AlexVPopov Hey sorry for not getting back to you sooner.

What does the association look like in your model?

**Comment by AlexVPopov** [comment]
Hey, no problem, it's Sunday, after all :smile: Thank you for getting back at all. 

So that's the thing - the association is made through a macro. I am using [acts-as-taggable-on](https://github.com/mbleigh/acts-as-taggable-on). In my `Expense` model I have included the line:

    acts_as_ordered_taggable

This gives the following associations:
```ruby
Expense has_many Taggings
Expense has_many Tags through Taggings

Tagging belongs_to Expense
Tagging belongs_to Tag

Tag has_many Taggings
Tag has_many Expenses through Taggings
```

However, the model definitions of `Tag` and `Tagging` are in the gem and not in my app. So this leads to the following more general question - does one need to test model behavior acquired through the inclusion of a gem. I've [asked this on StackOverflow](http://stackoverflow.com/questions/32035993/do-i-need-to-add-model-tests-related-to-acts-as-taggable-on), but haven't gotten any answers yet.

**Comment by mcmire** [comment]
@AlexVPopov Gotcha. In my opinion, you shouldn't *have* to test model behavior acquired through a gem if that gem is already tested. I realize that you have to test somehow that these associations exist, but I would think that this would be covered by a higher-level test somewhere. 

But if you really want to test that the associations exist, it looks like the failure message that your'e getting is correct -- Expense has many `tags` through `tag_taggings` and not `taggings`: https://github.com/mbleigh/acts-as-taggable-on/blob/5fc745165a3eb6ddbd0505d75c80e8fb7b1afd09/lib/acts_as_taggable_on/taggable/core.rb#L17

**Comment by AlexVPopov** [comment]
Thanks a lot, this really helped me, now my tests pass. :+1: I must have misinterpreted what the `class_name` option stands for. I thought that when the name of a model class cannot be inferred from the association name, one must specify the class explicitly. So in my case the name of the `taggings` class is `ActsAsTaggableOn::Tagging`. However, the following passes:
```ruby
it { should have_many(:taggings) }
```
Logically, this now also passes:
```ruby
it { should have_many(:tags).through(:tag_taggings) }
```
I guess in my case there is no point testing the model associations, as they are already covered in the gem tests. Thanks a lot for your great help.
