### ISSUE TITLE
Permit fails for :update on 3.0.rc1

### ISSUE THREAD

**Issue by AlexVPopov** [thoughtbot/shoulda-matchers#771]
Hello, my setup is `shoulda-matchers` 3.0 rc1 and `rspec-rails` 3.3.3. The following test fails for me:
```ruby
it do
  expense = Fabricate :expense
  should permit(:amount, :date).for(
    :update,
    params:
      {
        id: expense.to_param,
        expense: {tag_list: FFaker::Lorem.words(rand(1..3)).join(',')}
      }
  ).on(:expense)
end
```
with
> Expected PATCH #update to restrict parameters  for :expenseto :amount and :date, but it did not restrict any parameters.

Here are the relevant controller methods:
```ruby

def create
  @expense = Expense.new(expense_params)
  @expense.user = current_user
  current_user.tag(@expense, with: params[:expense][:tag_list], on: :tags)

  if @expense.save
    redirect_to expenses_path, notice: 'Expense was successfully created.'
  else
    flash[:error] = @expense.errors.full_messages.first
    render :new
  end
end

def update
  current_user.tag(@expense, with: params[:expense][:tag_list], on: :tags)

  if @expense.update(expense_params)
    redirect_to @expense, notice: 'Expense was successfully updated.'
  else
    render :edit
  end
end

def expense_params
  params.require(:expense).permit(:amount, :date)
end
```

Two things:

* a similar spec for the `create` action passes
```ruby
it do
  should permit(:amount, :date).for(
    :create,
    params: {expense: {tag_list: FFaker::Lorem.words(rand(1..3)).join(',')}}
  )
end
```
* through `puts` statements in `update` and `expense_params` I determined, that in the failing spec the `update` action never gets called.

Could this be a bug?

**Comment by maurogeorge** [comment]
> I determined, that in the failing spec the update action never gets called.

What is the verb you are using on your update action? This update action has a before filter like a authentication required that maybe will be doing a redirect before the matcher reaches the action?

I send a PR with the updated docs to the 3.0 rc1 as you can see [here](https://github.com/thoughtbot/shoulda-matchers/pull/731/files#diff-9f1dcc7f5f00eb2ddda8e5344714083aL140) we can pass a explicity verb if it is needed. I hope this helps you.

**Comment by AlexVPopov** [comment]
I am not sure exactly which verb it uses, but at least the error message reports, that it uses `PATCH`. Howevet, even if I set the verb to `PUT` the problem persists. I am using devise, but I have set it up correctly to log in a user before all the tests and this is the only test that fails, so I doubt that it is because of an authentication/redirection issue.

**Comment by mcmire** [comment]
@AlexVPopov It doesn't look like you're hitting the action for this test. There are contexts inside of the describe block for this action that do hit the action, but you have the test outside of those contexts.

**Comment by AlexVPopov** [comment]
@mcmire I may be misinterpreting how the `permit` matcher works, but doesn't it make a separate call to `:update` on its own? I mean in this:
```ruby
describe 'PUT #update' do
  let(:expense) { create_expense }

  let(:new_attributes) do
    Fabricate.attributes_for(:expense, user: subject.current_user, tag_list: tags)
  end

  it do
    should permit(:amount, :date).for(
      :update,
      params: {id: expense.to_param, expense: new_attributes}
    ).on(:expense)
  end
end
```
isnt' the part within `for` responsible for making the request? I shouldn't be needing to make a separate request before the test like so:
```ruby
put :update, {id: expense.to_param, expense: new_attributes}
```
Anyways, I tried this exact describe block that I posted and now I hit the `:update` action (when I put `binding.pry` within it, it stops). I also hit the `expense_params` method (which is responsible for permitting the params), but I still get the same error message. And once again  - I have almost exactly the same setup for `:create`, which passes.

**Comment by mcmire** [comment]
@AlexVPopov You're right, sorry. I forgot that the `permit` matcher does actually hit the action in question.

What happens if you run the test on its own? I'm wondering now if perhaps there's an issue where previous tests involving `permit` affect future tests -- we've had that issue before.

**Comment by AlexVPopov** [comment]
@mcmire <https://github.com/mcmire> The test fails also when I run it on
its own - take a look at the snippet I posted. In this describe block it is
the only test and I run only the describe block without the other tests.

**Comment by mcmire** [comment]
Lol okay, sorry. I'll take a closer look at your repo when I get a chance and see if I can track this down.

**Comment by AlexVPopov** [comment]
Super, thanks a lot :)

**Comment by mcmire** [comment]
@AlexVPopov So it turns out that using the permit matcher along with the `on` qualifier didn't actually work, and wasn't being properly tested. This should now be fixed in 0d43835b615f379f069c7d2c2264a80332510778. Can you bump your project to use shoulda-matchers master and try running your test again?

**Comment by rickyc** [comment]
Updated to the latest and previously failed permit specs work for me now :+1:

**Comment by mcmire** [comment]
Awesome, glad to hear!

**Comment by AlexVPopov** [comment]
@mcmire sorry for responding so late. I can confirm, that the test now works. Thanks a lot! :+1:

**Comment by Petercopter** [comment]
Hello from the future! Thanks for the hint about logging in before using the permit matcher. I was switching to request specs, and wanted to leave the strong params spec. I couldn't figure out why it wasn't working, and it was because I still need to login the user before testing.
