### ISSUE TITLE
Feature request: allow_format matcher for controllers

### ISSUE THREAD

**Issue by fabn** [thoughtbot/shoulda-matchers#775]
I've a lot of actions which uses `respond_to/respond_with` and every time I need to spec it in controller specs I have to do something like this:

``` ruby
it 'should not respond to json' do
  expect { get :whatever }.to raise_error ActionController::UnknownFormat
end
```

I was looking to write a custom matcher for this behavior when I found out that current `permit` matcher can be adapted to handle this. Here's a quick and dirty matcher based on latest stable to implement that:

``` ruby
  # Main matcher interface, simple usage:
  # it { should accept_format(:json).for(:show, params: {locale: :en}, verb: :get) }
  def accept_format(params)
    FormatMatcher.new(params).in_context(self)
  end

  # Allow format matcher, based on shoulda-matchers's permit matcher
  class FormatMatcher < Shoulda::Matchers::ActionController::StrongParametersMatcher
    def matches?(controller)
      @controller = controller
      !!make_request
    end

    alias_method :format, :expected_permitted_params

    def description
      "accept format #{format} for #{verb.upcase} ##{action}"
    end

    def failure_message
      "Expected controller to accept format #{format}, but it did not."
    end

    def failure_message_when_negated
      "Expected controller not to accept #{format}, but it did."
    end

    def request_params
      # Actually pass format as request param
      super.merge(format: format)
    end

    private

    def default_verb
      case action
        when :index, :show, :new, :edit
          :get
        when :create
          :post
        when :update
          Shoulda::Matchers::RailsShim.verb_for_update
        when :destroy
          :delete
      end
    end

    # Make the controller request and return a truthy value iff controller accepts the format
    def make_request
      ensure_action_and_verb_present!
      Shoulda::Matchers::Doublespeak.with_doubles_activated do
        # When request passes ActionController::TestResponse is returned which is truthy
        context.__send__(verb, action, request_params)
      end
    rescue ActionView::MissingTemplate
      # When this is raised it's because controller accepted the format and
      # implicit render by action name didn't found a matching template
      true
    rescue ActionController::UnknownFormat
      false
    end

  end
```

Would this be useful in shoulda matchers? Obviously it needs a lot of cleanup and to extract a common base class for both `FormatMatcher` and `PermitMatcher`, this is just a question to see if the idea can be interesting.

What do you think?

**Comment by mcmire** [comment]
As to a question of whether this would be necessary, I personally haven't found that testing that a controller only accepts certain formats and rejects other ones is necessary. Are you thinking that you'd want this from a security perspective?

As to the matcher you've made, the issue with that is that it's different from the manual test that you have at the top of your comment, although I understand why you used PermitMatcher, as one of the things it does is make the request for you. This is a rough cut of what I think the matcher could look like:

``` ruby
def only_respond_to(*formats)
  if formats.empty?
    raise ArgumentError, "Must pass formats"
  end

  OnlyRespondToMatcher.new(formats, self)
end

class OnlyRespondToMatcher
  def initialize(expected_formats, context)
    @expected_formats = expected_formats
    @context = context
  end

  def description
    expectation
  end

  def for(action_name, options = {})
    request_options = options.merge(context: context, action_name: action_name))
    @request = Request.new(request_options)
  end

  def matches?(controller)
    unless defined?(@request)
      raise ArgumentError, "#responds_to must be qualified with #for"
    end

    allows_valid_formats? && disallows_invalid_format?
  end

  def failure_message
    "Expected #{expectation}, but it did not (#{failure_reason})"
  end

  protected

  attr_reader :expected_formats, :context, :request, :failure_reason

  private

  def expectation
    "have restricted formats for #{controller.class_name}#{request.action} to #{expected_formats}"
  end

  def allows_valid_formats?
    valid_formats.each do |format|
      unless request_performed_successfully?(format: format)
        @failure_reason = "did not allow :#{format}"
        return false
      end
    end

    true
  end

  def disallows_invalid_format?
    if request_performed_successfully?(format: :invalid_format)
      @failure_reason = "allowed formats other than those"
      return false
    end

    true
  end

  def request_performed_successfully?(format:)
    request.perform(format: format)
    true
  rescue ActionController::UnknownFormat
    false
  end
end

class Request
  VERBS = {
    index: :get,
    show: :get,
    new: :get,
    edit: :get,
    create: :post,
    update: :patch,
    destroy: :delete
  }

  def initialize(context:, action_name:, verb: default_verb, params: {})
    @context = context
    @action_name = action_name
    @verb = verb
    @params = params
  end

  def perform(other_params = {})
    context.__send__(verb, action_name, params.merge(other_params))
  end

  private

  def default_verb
    VERBS.fetch(action) do
      raise ArgumentError, "No default verb could be determined for '#{action}'"
    end
  end
end
```

This way you can say:

``` ruby
it { should only_respond_to(:json).for(:show, params: { locale: :en }, verb: :get) }
```

**Comment by fabn** [comment]
> As to a question of whether this would be necessary, I personally haven't found that testing that a controller only accepts certain formats and rejects other ones is necessary. Are you thinking that you'd want this from a security perspective?

As you probably know rails routes and controllers by default accept all formats so when you have any routes like this `resource :posts` you can access `posts/1`, `posts/1.json` and so on. Then if you use implicit render only and go live in the wild web you'll start to get lot of `ActionView::MissingTemplate` in your error reporting service caused by bots and other strange code that will access your site. For this reason I always try to limit acceptable formats using [responders gem](https://github.com/plataformatec/responders) or [respond_to](http://apidock.com/rails/ActionController/MimeResponds/InstanceMethods/respond_to) blocks.

About security the only thing I can think to is a potential information disclosure if `respond_with(@post)` is used, in that case you get a full json(|xml) dump of resource and it might include sensitive informations, thus a spec that prevent that could be welcome in some cases.

I might understand that this won't be the most ever used matcher in shoulda but since it's implementation is relatively cheap why not to make it available for every shoulda user.

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
