### ISSUE TITLE
validate_uniqueness_of matcher failed for integer

### ISSUE THREAD

**Issue by JuanitoFatas** [thoughtbot/shoulda-matchers#776]
Hello!

I have a model,

```ruby
class User
  # github_id is an integer.
  validates_uniqueness_of :github_id, allow_blank: true
end
```

In `spec/models/user_spec`:

```ruby
describe User do
  context "validations" do
    it { should validate_uniqueness_of(:github_id).allow_blank }
  end
end
```

This test failed because from [active_record/validate_uniqueness_of_matcher.rb#L298-L300](https://github.com/thoughtbot/shoulda-matchers/blob/v2.8.0/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb#L298-L300):

```ruby
def existing_record_is_blank?
  @existing_record.present? && existing_value.strip == ''
end
```

it is calling `strip` on the integer, and integer does not have `strip` method:

```
Failure/Error: it { should validate_uniqueness_of(:github_id).allow_blank }
NoMethodError:
  undefined method `strip' for 0:Fixnum
```

Should this `#existing_record_is_blank?` check `existing_value` by Rails's `blank?` method?

Thanks. I'm using shoulda-matchers v2.8.0.

**Comment by mcmire** [comment]
Yeah, I think that definitely makes sense.

**Comment by mcmire** [comment]
Closing this issue in favor of #781.
