### ISSUE TITLE
 spec involving validate_inclusion_of fails after upgrading to shoulda-matchers 3.0

### ISSUE THREAD

**Issue by jasnow** [thoughtbot/shoulda-matchers#783]
* Given you start with my https://github.com/jasnow/24pullrequests repo
 * And you run "rake" before changes and you see all pass
 * Then you upgrade to "3.0" by removing this string **", '2.8.0' # 3.0.0 BREAK TEST RUN"** from my Gemfile
 * And you rebuild Gemfile.lock file using "bundle"
 * And you add a few (6) lines to spec/rails_helper.rb file
 * And run "unset GITHUB_KEY ; rake"
 * Travis Log: https://travis-ci.org/jasnow/24pullrequests/builds/83220541

**Comment by jasnow** [comment]
Travis log: https://travis-ci.org/jasnow/24pullrequests/builds/83204027

**Comment by mcmire** [comment]
* The failure involving `validate_inclusion_of` looks like a legitimate bug, can you file an issue?
* The failure involving `validate_uniqueness_of` is due to the fact that the uniqueness matcher didn't properly default to case-sensitive. See 57a19228b6a85f12ba7a79a26dae5869c1499c6d.

**Comment by greysteil** [comment]
If the first of those spec failures is a bug then it looks like it's affecting other matchers, too. We're seeing all of our `validate_numericality_of` spec fail because Rails casts string like `"abcd"` to `0.0` for numeric fields, and `ValidateNumericalityOfMatcher` delegates to `DisallowValueMatcher`, which in turn delegates to `AllowValueMatcher`. :cry:

**Comment by firedev** [comment]
Same here but in another way added both to `rails_helper.rb`:
```ruby
require 'shoulda/matchers'
```
and
```ruby
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.library :rails
  end
end
```
Yet passing test fails now:

```
     Failure/Error: it { is_expected.to validate_presence_of :name }
     NoMethodError:
       undefined method `validate_presence_of'
```

**Comment by mcmire** [comment]
@firedev You're missing this line within the configuration block:

``` ruby
with.test_framework :rspec
```

Also technically you no longer need the `require 'shoulda/matchers'` line.

**Comment by mcmire** [comment]
> If the first of those spec failures is a bug then it looks like it's affecting other matchers, too. We're seeing all of our `validate_numericality_of` spec fail because Rails casts string like `"abcd"` to `0.0` for numeric fields

@greysteil Do you need to add a numericality validation for a numeric attribute, though? If the attribute is always typecast to a number, then it will never be a string, so the validation will never fail. Right?

**Comment by greysteil** [comment]
@mcmire - I do if I want to use `validate_numericality_of(:amount).is_greater_than(0)` etc.

**Comment by mcmire** [comment]
@greysteil Gotcha, that's a good point. I'll think about a good solution for this.

**Comment by jasnow** [comment]
**Note that Gift.giftable_dates is expanded, but not :date** given the input is
```
it { is_expected.to validate_inclusion_of(:date).in_array(Gift.giftable_dates) }
```
you get this:
```
  1) Gift should ensure inclusion of date in [Mon, 01 Dec 2014, Tue, 02 Dec 2014, Wed, 03 Dec 2014, 
Thu, 04 Dec 2014, Fri, 05 Dec 2014, Sat, 06 Dec 2014, Sun, 07 Dec 2014, Mon, 08 Dec 2014, Tue, 09 De
c 2014, Wed, 10 Dec 2014, Thu, 11 Dec 2014, Fri, 12 Dec 2014, Sat, 13 Dec 2014, Sun, 14 Dec 2014, Mo
n, 15 Dec 2014, Tue, 16 Dec 2014, Wed, 17 Dec 2014, Thu, 18 Dec 2014, Fri, 19 Dec 2014, Sat, 20 Dec 
2014, Sun, 21 Dec 2014, Mon, 22 Dec 2014, Tue, 23 Dec 2014, Wed, 24 Dec 2014]
```

**Comment by jasnow** [comment]
FYI: This spec broke between release 2.8.0 and release 3.0.0.rc1.

**Comment by mcmire** [comment]
The issue with `validate_inclusion_of` is now fixed in 8fa97b4ff33b57ce16dfb96be1ec892502f2aa9e.

**Comment by jasnow** [comment]
THANKS.

When is your plan to release this to rubygem.org?

**Comment by jasnow** [comment]
Verified that 8fa97b4 does fix my issue when I use the edge version of shoulda-matchers gem.

**Comment by mcmire** [comment]
Cool, thanks for confirming.

I plan on releasing a 3.0.1 version after fixing the issue with the uniqueness matcher which is happening in #789. There may be other issues that arise while that PR is ongoing so if that happens I'll include fixes for those too.

**Comment by mcmire** [comment]
I'll close this since all of the issues mentioned in this issue are fixed on master.

**Comment by jasnow** [comment]
When is 3.1.0 release date? I see that the milestone was changed 4 days ago.

**Comment by mcmire** [comment]
Originally 3.1.0 was the next version, but given these bug fixes, 3.0.1 is coming out next. There's no release date for 3.1.0 (as I need to work out what to put in it exactly) but I'm shooting for two months.

**Comment by jasnow** [comment]
Looking forward for 3.0.1 then. Thanks.

**Comment by mcmire** [comment]
@jasnow 3.0.1 is now released with this particular fix included.

**Comment by jasnow** [comment]
Thanks for the new gem version.

Our example App: https://travis-ci.org/24pullrequests/24pullrequests/builds/87257312 is green and waiting for PR https://github.com/24pullrequests/24pullrequests/pull/942 to be accepted.
