### ISSUE TITLE
Possible documentation error in NEWS.md

### ISSUE THREAD

**Issue by tovodeverett** [thoughtbot/shoulda-matchers#790]
In [NEWS.md#L153-L155](https://github.com/thoughtbot/shoulda-matchers/blame/master/NEWS.md#L153-L155), it reads "`validate_uniqueness_of` is now properly case-insensitive by default . . ."  I'm confused by this line - as far as I can tell, the new behavior is to be case-sensitive by default, and one must call `case_insensitive` to get case-insensitive behavior.  Am I confused or is this a mistake in [NEWS.md](https://github.com/thoughtbot/shoulda-matchers/blob/master/NEWS.md)?

**Comment by mcmire** [comment]
Yup, you're right, that should have read "case-sensitive by default". This is now fixed.
