### ISSUE TITLE
Undefined method respond_with for namespaced controller spec 

### ISSUE THREAD

**Issue by CharlesJQuarra** [thoughtbot/shoulda-matchers#795]
I have a namespaced controller for an Api, and when i use the should `respond_with` matcher in the spec for the same , i get the message undefined method `respond_with` for `#<RSpec::ExampleGroups::ApiV1UsersController::GETShow:0x007fd30e4a5c20>`

The spec i have is as follows :

``` ruby
describe Api::V1::UsersController, type: :controller do
  describe "GET #show" do
    before(:each) do
      @user = create(:user)
      get :show, id: @user.id, format: :json
    end

   it {  should respond_with 200 }
  end
end
```

I have added the rspec-rails gem before the shoulda-matchers gem in my Gemfile. Also, my users controller is located in app/controllers/api/v1/users_controller.rb and the spec in spec/controllers/api/v1/users_controller_spec.rb .

This is a duplicate of https://github.com/thoughtbot/shoulda-matchers/issues/684 but I can't reopen an issue that is not mine, so I'm opening a new one

**Comment by mcmire** [comment]
@CharlesJQuarra Which version are you using?

**Comment by erikjenks** [comment]
I am receiving the same issue actually. I am using Rspec-rails 3.0 and shoulda-matchers 3.0 same error and everything.

**Comment by mcmire** [comment]
This may be due to this change: af98a23091551fb40aded5a8d4f9e5be926f53a9

Are any of the other controller matchers available to you?

**Comment by mcmire** [comment]
I'm closing this since there hasn't been a response in a long while. Feel free to respond if you are still having this issue.
