### ISSUE TITLE
undefined method `validate_presence_of'

### ISSUE THREAD

**Issue by edwardloveall** [thoughtbot/shoulda-matchers#802]
In the process of upgrading to 3.0, I'm getting an error with the `validate_presence_of` matcher. As far as I can tell I've set up everything correctly:

* The test_framework is set
* The library is set
* The tests are in the standard `spec/models` folder

But these two tests fail:

https://github.com/jneen/rouge.jneen.net/blob/20aaf0edcd2b671d75e6f3345ffa3033439aa41e/spec/models/paste_spec.rb#L5-L6

What am I missing?

**Comment by edwardloveall** [comment]
Turns out, my [configuration](https://github.com/thoughtbot/shoulda-matchers#configuration) was wrong. I was just using the `:active_record` library instead of `:rails`.

**Comment by mcmire** [comment]
Gotcha. Glad you got it working.
