### ISSUE TITLE
3.0 Bug? when use validate_numericality_of 

### ISSUE THREAD

**Issue by ZhangHanDong** [thoughtbot/shoulda-matchers#804]
model:

```ruby
validates :points, numericality: { greater_than_or_equal_to: 0}, presence: true
```

rspec : 

```ruby
it {should validate_numericality_of(:points).is_greater_than_or_equal_to(0)}
```

rspec output ( gem "shoulda-matchers", '~> 3.0') : 

```ruby
Failure/Error: it {should validate_numericality_of(:points).is_greater_than_or_equal_to(0)}
     Shoulda::Matchers::ActiveModel::AllowValueMatcher::CouldNotSetAttributeError:
       Expected Class to be able to set points to "abcd", but got 0 instead.

```

but shoulda-matchers 3.0.0.rc1  is ok. 

is it a bug?

**Comment by mcmire** [comment]
Yup, it's a bug and it was fixed in this commit: 18b2859d2522a4866c398b9a32ebc3de4ec79389. This will be included in the next version (coming out soon).

**Comment by ZhangHanDong** [comment]
good job!

**Comment by durhamka** [comment]
Is there a work around for this until the next version is released? Thanks, Elliot!

**Comment by mcmire** [comment]
There isn't... I'm trying to throw another change in before I release but now I'm thinking I should release something now. Okay... I'll see if I can do that.

**Comment by mcmire** [comment]
@durhamka I just released 3.0.1. Not every issue with 3.0.0 is fixed, so just be aware of that, but this particular issue should be fixed.

**Comment by ZhangHanDong** [comment]
@macmire  thanks

**Comment by durhamka** [comment]
Thanks @mcmire!
