### ISSUE TITLE
validate_presence_of says "Failure message is nil" when attribute is serialized

### ISSUE THREAD

**Issue by wgc-as** [thoughtbot/shoulda-matchers#805]
This is my model:

``` ruby
class User < ActiveRecord::Base
  serialize :settings, Hash
end
```

This is the spec:

``` ruby
require 'rails_helper'

RSpec.describe User, type: :model do
  it { is_expected.to     serialize(:settings) }
  it { is_expected.to_not validate_presence_of :settings }
end
```

It throws this error:

```
  1) User should not require settings to be set
     Failure/Error: it { is_expected.to_not validate_presence_of :settings }
     ArgumentError:
       Failure message is nil. Does your matcher define the appropriate
failure_message[_when_negated] method to return a string?
     # ./spec/models/user_spec.rb:5:in `block (2 levels) in <top (required)>'
```

In my opinion this should pass as I don't have to assign any value to `settings` to produce a valid entity. But even if it fails, it should give a better error message.

This worked before I upgraded to shoulda 3.0.0.

rails (4.2.4)
rspec-core (3.3.2)
rspec-expectations (3.3.1)
rspec-mocks (3.3.2)
rspec-rails (3.3.3)
rspec-support (3.3.0)
shoulda-matchers (3.0.0)

Mac OS X 10.9.5, Ruby 2.2.2

**Comment by mcmire** [comment]
I don't know why you'd be getting this, but have you tried putting parentheses around `:settings`?

**Comment by wgc-as** [comment]
It does not help. I created a repository which reproduces the issue:
https://github.com/wgc-as/shoulda_validate_presence_of

I forgot to commit the initial state after rails new separately, but the only addition is the "rspec-rails" and "shoulda-matchers" gems in the Gemfile, the migration file and the User model.

**Comment by mcmire** [comment]
Thanks, I'll take a closer look at it.

**Comment by wgc-as** [comment]
After some debugging, it turns out that an error is swallowed in `ValidatePresenceOfMatcher#disallows_original_or_typecast_value?` method:
```
#<Shoulda::Matchers::ActiveModel::AllowValueMatcher::CouldNotSetAttributeError:
The allow_value matcher attempted to set :settings on User to nil, but
when the attribute was read back, it had stored [] instead.

This creates a problem because it means that the model is behaving in a
way that is interfering with the test -- there's a mismatch between the
test that was written and test that was actually run.

There are a couple of reasons why this could be happening:

* The writer method for :settings has been overridden and contains
  custom logic to prevent certain values from being set or change which
  values are stored.
* ActiveRecord is typecasting the incoming value.

Regardless, the fact you're seeing this message usually indicates a
larger problem. Please file an issue on the GitHub repo for
shoulda-matchers, including details about your model and the test
you've written, and we can point you in the right direction:

https://github.com/thoughtbot/shoulda-matchers/issues>
```

So the root of the problem is that the `ValidatePresenceOfMatcher#blank_value` thinks that the empty value for a serialised Hash attribute is `nil`. If I modify `blank_value` to return `{}` instead of `nil` then the test passes. Here is the modified `blank_value` method:
```ruby
        def blank_value
          if collection?
            []
          elsif attribute_is_serialized?
            if serialization_class == Array
              []
            elsif serialization_class == Hash
              {}
            else
              nil
            end
          else
            nil
          end
        end

        def attribute_is_serialized?
          serialized_attributes.include?(@attribute.to_s)
        end

        def serialization_class
          klass = serialized_attributes[@attribute.to_s]
          if klass.respond_to?(:object_class)
            klass = klass.object_class
          end
        end

        def serialized_attributes
          Shoulda::Matchers::RailsShim.serialized_attributes_for(model)
        end

        def model
          @subject.class
        end
```

**Comment by mcmire** [comment]
Cool, thanks for tracking this down. 

It's interesting that 1) the failure message wasn't properly reported before and 2) the test didn't pass, since `[]` is an acceptable value that is "blank". So I'll have to look into this further.

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
