### ISSUE TITLE
Undefined methods from shoulda-matchers on Rails upgrade

### ISSUE THREAD

**Issue by andreydeineko** [thoughtbot/shoulda-matchers#816]
I hav upgraded Rails from 4.0.x to Rails 4.2.4. I was having rspec-rails 2.x.x, and shoulda-matchers 2.x.x. At this point my tests broke, and tons of errors occurred saying 

```ruby
Failure/Error: it { is_expected.to validate_presence_of(:client_has_active_debit_card) }
  NoMethodError:
    undefined method `validate_presence_of' for #<RSpec::ExampleGroups::ApiParticipant::Validations::OnUpdate_2
```
and so on (pointing to methods from shoulda-matchers).

I've updated rspec-rails to 3.3.1 and shoulda-matchers to 3.0.0 to no avail.

I have asked a [question on StackOverflow](http://stackoverflow.com/questions/33280731/shoulda-matchers-are-not-seen-by-rails-rspec?noredirect=1#comment54397680_33280731), but noone yet seem to know the answer.
____
EDIT
Ok, I think the issue is not with shoulda-matchers, but with [active_attr gem](https://github.com/cgriego/active_attr), because tests only fails in `spec/compositions/api` folder, where I use the gem.

**Comment by andreydeineko** [comment]
Ok, I think the issue is not with shoulda-matchers, but with [active_attr gem](https://github.com/cgriego/active_attr), because tests only fails in api/composition folder, where I use the gem.

**Comment by franciscomxs** [comment]
Take a look here: http://matchers.shoulda.io/docs/v3.0.0/#configuration

```
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    # Choose a test framework:
    with.test_framework :rspec
    with.test_framework :minitest
    with.test_framework :minitest_4
    with.test_framework :test_unit

    # Choose one or more libraries:
    with.library :active_record
    with.library :active_model
    with.library :action_controller
    # Or, choose the following (which implies all of the above):
    with.library :rails
  end
end
```

**Comment by andreydeineko** [comment]
@franciscomxs I am grateful for your input, but documentation is the first place I resort when experiencing errors. In my SO question I've added in the issue description you can see that this config is added to ```rails_helper.rb```.

Nonetheless thanks a lot for the reply!

**Comment by franciscomxs** [comment]
Sorry if it was not usefull. It did solve the problem to me.

**Comment by cgriego** [comment]
shoulda-matchers 3.0 selectively makes its matchers available. You're using ActiveModel matchers which are only mixed into model specs. https://github.com/thoughtbot/shoulda-matchers/commit/af98a23091551fb40aded5a8d4f9e5be926f53a9

You can either place your model specs in spec/models or try adding `:type => :model` to the top-level `describe` block for each class.

**Comment by mcmire** [comment]
What @cgriego said is likely the problem here. I'm closing this, but feel free to ask for more help if you need it.

**Comment by andreydeineko** [comment]
@cgriego Adding ```type: :model``` did the trick, thanks so much!
