### ISSUE TITLE
`should define_enum_for` should validate column is an integer

### ISSUE THREAD

**Issue by geoffharcourt** [thoughtbot/shoulda-matchers#827]
While converting a column from being a string to an enum, I found that the enum matcher spec for my model passed, but every time I assigned a value to the field it came back as `nil`.

**Comment by mcmire** [comment]
Okay -- I'm not sure I understand exactly what's happening here, can you provide an example?

**Comment by geoffharcourt** [comment]
I'm working on a spec and test now. If your column for the enum isn't an
integer (mine was a string), ActiveRecord will save your model, but
checking the attribute later will return `nil` rather than the mapped
value.

**Comment by geoffharcourt** [comment]
cc: @mcmire

**Comment by geoffharcourt** [comment]
Here's what happened:

```ruby
class Example < ActiveRecord::Base
   enum status: { active: 0, inactive: 1 }
end

create_table :examples do |t|
  t.string :status
end

RSpec.describe Example do
  it { should define_enum_for(:status).with(active: 0, inactive: 1) }
end
```

The matcher passes, but this enum is actually broken in a subtle but very bad way:

```ruby
example = Example.new(status: :active)

# => #<Example:0x007f9f811169f8 status: "0">

example.status
# => nil
```

When the column is a string, AR will allow you to save values, but after save, the strings don't get recast as integers, and any lookup against enum values fails.

What I'm struggling with is that right now the specs for the most part don't rely on a database table being created, so adding a criteria for the matcher that checks for the column breaks almost all the specs for `define_enum_for`.

**Comment by mcmire** [comment]
Okay, I'll keep an eye on that issue.

**Comment by mcmire** [comment]
I'm going to close this issue in favor of the PR (#829).
