### ISSUE TITLE
numericality matcher should not raise an IneffectiveTestError

### ISSUE THREAD

**Issue by ineu** [thoughtbot/shoulda-matchers#832]
`validates_numericality` matchers was changed with assumption that validations are there for data consistency only. But for data consistency one uses proper database column types and DB-level constraints. Validations are perfect for users.

For example, I use validates_numericality on all my columns that can be updated from forms. I want my users to see 'not a number' when they type non-number in form input. Following code recommends to remove validation which is definitely not something I want to do: https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb#L522

Also, behavior described in https://github.com/thoughtbot/shoulda-matchers/issues/784#issuecomment-145155888 is not really a case. Please see following snippet:
```
[25] pry(main)> a = Payment.new
=> #<Payment:0x00562d6b28fcf0 id: nil, account_id: nil, packet_id: nil, payment_type_id: nil, deposit: nil, amount: nil, operator_id: nil, created_at: nil>
[26] pry(main)> a.amount = 'foo'
=> "foo"
[27] pry(main)> a.amount
=> #<BigDecimal:562d6a0cb9d8,'0.0',9(18)>
[28] pry(main)> a.valid?
=> false
[29] pry(main)> a.errors
=> #<ActiveModel::Errors:0x00562d69e84530
 @base=
  #<Payment:0x00562d6b28fcf0
   id: nil,
   account_id: nil,
   packet_id: nil,
   payment_type_id: nil,
   deposit: nil,
   amount: #<BigDecimal:562d6a0cb9d8,'0.0',9(18)>,
   operator_id: nil,
   created_at: nil>,
 @messages={:account=>["can't be blank"], :packet=>["can't be blank"], :payment_type=>["can't be blank"], :deposit=>["can't be blank"], :amount=>["is not a number"]}>
```

As you can see, numeric validation does add 'not a number' error, despite 'amount' is decimal column. So it matters and should neither be removed nor should raise IneffectiveTestError exception.

I think there should be some kind of configuration option to disable IneffectiveTestError exception. Using validations to get nice error messages is valid and, I think, frequent use case.

**Comment by mcmire** [comment]
Thanks for the feedback.

A simple fix for this might be to revert [this change](18b2859d2522a4866c398b9a32ebc3de4ec79389), and so instead of raising an IneffectiveTestError, tack `ignoring_interference_by_writer` on the end of the DisallowValueMatcher [here](https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb#L447). If we're checking that an attribute rejects a non-number, it doesn't really matter whether that non-number ends up getting typecast, as long as the record is placed in an invalid state.

**Comment by axlekb** [comment]
I just tried upgrading and came across this message as well.  Completely agree with @ineu as this makes v3.0 unusable for my projects (want the nice validation messages).

btw, your `this change` link above is broken (issue vs commit directory).

**Comment by axlekb** [comment]
Should also point out that other case that I encountered is setting a decimal value to an integer database column, which the validation successfully enforces and messages.  Looks like that is also included in the [commit](https://github.com/thoughtbot/shoulda-matchers/commit/18b2859d2522a4866c398b9a32ebc3de4ec79389) you mentioned above.

**Comment by rilian** [comment]
also getting this issue for

```ruby
class Modelname < ActiveRecord::Base
  validates :fieldname, numericality: { only_integer: true, greater_than: 0 }
end
```

```ruby
    it { is_expected.to validate_numericality_of(:fieldname).only_integer.is_greater_than(0) }
```

and getting

```
1) Modelname Validations should only allow integers for fieldname which are greater than 0
     Failure/Error: it { is_expected.to validate_numericality_of(:fieldname).only_integer.is_greater_than(0) }

     Shoulda::Matchers::ActiveModel::AllowValueMatcher::CouldNotSetAttributeError:
       The allow_value matcher attempted to set :fieldname on Modelname to
       0.1, but when the attribute was read back, it had stored 0 instead.

       This creates a problem because it means that the model is behaving in a
       way that is interfering with the test -- there's a mismatch between the
       test that was written and test that was actually run.

       There are a couple of reasons why this could be happening:

       * The writer method for :fieldname has been overridden and contains
         custom logic to prevent certain values from being set or change which
         values are stored.
       * ActiveRecord is typecasting the incoming value.

       Regardless, the fact you're seeing this message usually indicates a
       larger problem. Please file an issue on the GitHub repo for
       shoulda-matchers, including details about your model and the test
       you've written, and we can point you in the right direction:

       https://github.com/thoughtbot/shoulda-matchers/issues
```

**Comment by mcmire** [comment]
@rilian That's a CouldNotSetAttributeError, which has already been mentioned in past issues and isn't directly related to this issue, but thank you for the report.

**Comment by rilian** [comment]
@mcmire thank you! I've already subscribed to this thread https://github.com/thoughtbot/shoulda-matchers/pull/800 which is devoted to solving the issue.

**Comment by KeirSurvival** [comment]
+1. I'm also using the numericality matches for form error messages.

**Comment by mcmire** [comment]
This has now been removed in 5ed03624197314865ff5463e473e5e84bb91d9ea. Cheers.

**Comment by ineu** [comment]
Awesome, thank you!
