### ISSUE TITLE
It's not mentioned anywhere that the matchers are only included based on meta-tags

### ISSUE THREAD

**Issue by Draiken** [thoughtbot/shoulda-matchers#833]
I use shoulda on a gem that uses active_record and active_model. After upgrading from 2.8 and adding the configuration for those libraries and framework on the spec helper, I still got undefined method errors.

Only after digging through the source code I found that the matchers were only included based on the meta tags, like `model: true`.

I thought about just adding this information in the README but I'm not sure if that's the ideal place for it, or if it needs to be added somewhere else too.

**Comment by mcmire** [comment]
You're right, it's not -- I'm trying to keep the README slim and I didn't want to over-complicate the instructions lest new users think that the gem is difficult to use. I'm working on adding a Getting Started guide that explains this in more detail. Someone else actually made an issue about that in #807, mind if I close this one?

**Comment by ClayShentrup** [comment]
Why isn't there awareness of `infer_spec_type_from_file_location!`?

**Comment by ClayShentrup** [comment]
> I didn't want to over-complicate the instructions lest new users think that the gem is difficult to use

Not adding those instructions..made the gem more difficult to use.

**Comment by mcmire** [comment]
Sorry, I misunderstood the issue being raised here.

The gem does honor `infer_spec_type_from_file_location!`, but if you look at [how RSpec implements that option](https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/configuration.rb#L84), it does so via tags. In other words, an example group defined in a file located in `spec/models` will be automatically tagged with `type: :model`. So there are two ways that shoulda-matchers will mix itself into an example group:

* If that example group is located in a directory that rspec-rails knows about, such as `spec/models`, `spec/controllers`, or `spec/routing`.
* If that example group is explicitly tagged with `type: :model`, `type: :controller`, or `type: :routing`.

**Comment by ClayShentrup** [comment]
Since our ActiveRecord specs don't load Rails (because tests should be fast), we just do this:

```ruby
# active_record_helper.rb
RSpec.configure do |config|
  config.include(Shoulda::Matchers::ActiveRecord, type: :model)
  config.include(Shoulda::Matchers::ActiveModel, type: :model)
end
```

Then just manually specify the type in the model class. E.g.

```ruby
RSpec.describe(Thang, type: :model) do
```

**Comment by mcmire** [comment]
@ClayShentrup Ah I see. Since it's `rspec-rails` that automatically tags example groups, if you're not using that, then the logic that shoulda-matchers follows doesn't work so well, I guess. I apologize -- that was an oversight on my part.

Do [these instructions](https://github.com/thoughtbot/shoulda-matchers/tree/ew-document-availability-of-matchers#availability-of-matchers-in-various-example-groups) suffice to clarify what to do in this situation, at least?

**Comment by Draiken** [comment]
For me that is more than enough.

The whole trouble I had was just because I am not using the standard rails setup, so I had to discover the hard way why the matchers were not being included.

If I'm not mistaken, the gem already includes itself based on those tags @ClayShentrup as long as you configure it with the proper libraries, all that was missing was the information that the tags are needed when not using `infer_spec_type_from_file_location!`

For me this issue can be closed

**Comment by Draiken** [comment]
Just to clarify, if you use the shoulda configuration for libraries like

```
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :active_record
    with.library :active_model
  end
end
```

You won't need to manually include the matchers, since the [integrations will do that for you](https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/integrations/libraries/active_record.rb#L13), with the proper tags.

**Comment by ClayShentrup** [comment]
Yes, @mcmire, those instructions are good. I actually just ended up unconditionally including them, since I'm not using anything else that will conflict with your method definitions.

**Comment by mcmire** [comment]
:star2:
