### ISSUE TITLE
have_many matcher may not give the reason for failure

### ISSUE THREAD

**Issue by mcmire** [thoughtbot/shoulda-matchers#834]
Scenario:

``` ruby
# Model
class GuideItemGroup < ActiveRecord::Base
  has_many :items, class_name: "GuideItem"
end

# Test
describe GuideItemGroup do
  it { should have_many(:items).class_name("GuideItem").with_foreign_key(:group_id) }
end
```

Expected failure message:

```
Expected GuideItemGroup to have a has_many association called items (association is not qualified with foreign_key: :group_id)
```

Actual failure message:

```
Expected GuideItemGroup to have a has_many association called items ()
```

**Comment by gmmcal** [comment]
+1

**Comment by Uysim** [comment]
+1

**Comment by mcmire** [comment]
I plan on rewriting the messaging for the association matchers so I can tackle this as a part of that.

**Comment by mcmire** [comment]
Unfortunately I haven't touched the work I was attempting to finish since when I left that comment and this feels like a lower priority thing in comparison to the other issues/PRs open right now so I'm just gonna call this one. Maybe somebody else will pick it up 😅
