### ISSUE TITLE
`validate_numericality_of` doesn't work with PG `money` column type

### ISSUE THREAD

**Issue by agrobbin** [thoughtbot/shoulda-matchers#841]
From the looks of it, the fix implemented in 3.0.1 (via 18b2859d2522a4866c398b9a32ebc3de4ec79389 and a0f12216fd12627c2545b082f5e463a712ba75e5) did not resolve the issue for the PG `money` column type.

**Comment by mcmire** [comment]
Ah. It doesn't seem like there was an issue open for the `money` type, so I neglected to add support for that, it seems.

While we're at it, are there any other Postgres types you use that we should be supporting as well?

**Comment by agrobbin** [comment]
There's a [variety of them](http://api.rubyonrails.org/v4.2.5/classes/ActiveRecord/ConnectionAdapters/PostgreSQL/ColumnMethods.html) available in ActiveRecord, but the only one I've personally run into issues testing is the `money` type. I think that's one of the only additional ones that really makes sense when using the `NumericallyValidator`.

**Comment by mcmire** [comment]
Alright. We haven't ever explicitly supported more than the ones that we test against currently, so I'll just add a fix for `money` now and if there bugs with other columns later we can cross those bridges then.

**Comment by mareczek** [comment]
Does array of ints count as type?

**Comment by mcmire** [comment]
Does the numericality validation make sense with an array of integer?

**Comment by mcmire** [comment]
Since [`allow_value` no longer raises a CouldNotSetAttributeError](5532f4359aa332b10de7d46f876eaffd4a95b5b6), this issue is basically resolved. However, I added an explicit test [here](a559713f96303414551c0bc1767fb11eb19bcc5d), so this issue is *really* resolved.
