### ISSUE TITLE
Using Shoulda Matchers with Minitest

### ISSUE THREAD

**Issue by bakku** [thoughtbot/shoulda-matchers#844]
I'm trying to make shoulda-matchers work with minitest for a while now.

I added

`gem 'shoulda', '~> 3.5'`

to my Gemfile and configured my test_helper.rb like this:

`Shoulda::Matchers.configure do |config|`
    `config.integrate do |with|`
     `with.test_framework :minitest`
      `with.library :rails`
    `end`
`end`

But this way I get the following error when starting a test:

`undefined method 'configure' for Shoulda::Matchers:Module (NoMethodError)`

I already tried using only shoulda-matchers directly, but this way I get a NoMethodError for

`should`

in my tests.
Anybody knows how to solve this?

**Comment by bakku** [comment]
I made it work by

`require 'shoulda'`

in `test_helper.rb`

and removing all

`Shoulda::Matchers.configure` 

stuff

**Comment by tobiasfeistmantl** [comment]
Thanks this works! Maybe the shoulda-matchers version should be updated in the shoulda.gemspec. It's still version 2.8.0. Or else a correct documentation.
