### ISSUE TITLE
Add a caveat for inclusion matcher?

### ISSUE THREAD

**Issue by backus** [thoughtbot/shoulda-matchers#846]
We ran into a subtle case where a field with an inclusion validator, along with a length validator, led to us almost not realizing that shoulda isn't *really* testing the inclusion validator.  Here is the simplified example:

```ruby
require 'active_model'

class Example
  STATES = %w[AK AL AR AS AZ CA CO].freeze # truncated for brevity

  include ActiveModel::Model

  attr_accessor :subdivision

  validates :subdivision, length: { is: 2 }, inclusion: STATES
end

RSpec.describe Example do
  include Shoulda::Matchers::ActiveModel

  subject { described_class.new }

  let(:codes) { described_class::STATES }

  it { should validate_inclusion_of(:subdivision).in_array(codes) }
end
```

Looking at the `ValidateInclusionOfMatcher` it is pretty clear that all values will be rejected by the length validator:

```ruby
class ValidateInclusionOfMatcher < ValidationMatcher
  ARBITRARY_OUTSIDE_STRING = 'shoulda-matchers test string'
  ARBITRARY_OUTSIDE_FIXNUM = 123456789
  ARBITRARY_OUTSIDE_DECIMAL = BigDecimal.new('0.123456789')
  ARBITRARY_OUTSIDE_DATE = Date.jd(9999999)
  ARBITRARY_OUTSIDE_DATETIME = DateTime.jd(9999999)
  ARBITRARY_OUTSIDE_TIME = Time.at(9999999999)
```

I do not think this is a bug in shoulda-matcher. With that said, it should probably be documented as a caveat. In this case our inclusion test gives us false confidence when in reality we could completely remove the inclusion validator and the tests would still pass.

**Comment by mcmire** [comment]
That's not true -- if you look at [what the inclusion matcher is doing](https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb#L366), you'll see that it performs two tests:

1. that the attribute allows all of the given values
2. that the attribute does not allow a value that is not any of the values

**Comment by mcmire** [comment]
I see what you're saying though -- in this case, the length validation is probably failing first before the inclusion validation is even getting run.

The caveat you named applies to any of the matchers -- a matcher designed to test a particular validation has no knowledge of any other validations and therefore any usage of that matcher is really an integration test in the context of your model's entire set of validations.

I'm not really sure what to do about this -- it would apply (and does apply) if you wrote tests yourself, too. It's just a general fact of model tests, I would think.

**Comment by backus** [comment]
Sorry, what isn't true? In this case I'm not saying there is a bug with the matcher or anything.  I'm just saying that it would be helpful to document that, in this case, the `values_outside_of_array` ends up being `[ARBITRARY_OUTSIDE_STRING]` which the length validator will add an error message for.

This means I can remove `inclusion: STATES` from above and the test should still pass.

**Comment by mcmire** [comment]
If you want to document this on the wiki that's fine, but it seems like a minor detail that wouldn't provide that much value if an extra section were created for this in the documentation. I agree about the redundancy, but it doesn't seem like something that would trip someone up. Was there any confusion when you ran that test, or was it just something you noticed?

**Comment by backus** [comment]
We run our tests through [mutant](https://github.com/mbj/mutant) which showed that it could completely remove our model validations without breaking tests.

**Comment by backus** [comment]
Just thinking out loud here: if shoulda could instead do something like this for the validation specific matchers then it could avoid this issue:

```ruby
require 'active_model'

class Model
  include ActiveModel::Model

  attr_accessor :foo

  validates :foo, numericality: true, inclusion: { in: [1,2] }
end

instance = Model.new(foo: 'three')

validators = instance._validators.fetch(:foo, []).grep(ActiveModel::Validations::InclusionValidator)

validators.each { |validator| validator.validate(instance) }

instance.errors.to_h # => {:foo=>"is not included in the list"}
```

I'm not saying this is better but in this case at least you are only running validations relevant to the test in question.

**Comment by mcmire** [comment]
Hmm, I see. I think the only problem with this approach is that it isn't indicative of how models are used in Real Code™ -- when you save a model you're running *all* the validations, not just a select few. 

Sorry for closing the issue so quickly by the way -- I realize that came off as a rejection, it's really more an attempt to stay at inbox zero... or inbox closer-to-zero :)

If there's a way that we could somehow detect that the inclusion matcher never got run, then that would be interesting...

**Comment by backus** [comment]
> Sorry for closing the issue so quickly by the way -- I realize that came off as a rejection, it's really more an attempt to stay at inbox zero... or inbox closer-to-zero :)

Not offended by the issue closing don't worry about it.

> If there's a way that we could somehow detect that the inclusion matcher never got run, then that would be interesting...

Well I don't think activemodel ever short circuits validations.  For example, using the same instance as before:

```ruby
instance = Model.new(foo: 'three')
instance.valid?
instance.errors.to_a # => ["Foo is not a number", "Foo is not included in the list"]
```

With that said you might know more than me here so correct me if I'm wrong.
