### ISSUE TITLE
  Failure/Error: it { is_expected.not_to allow_value("110.708.744-94").for(:cpf) }

### ISSUE THREAD

**Issue by vinisdl** [thoughtbot/shoulda-matchers#848]
Hi,
I have a problem when upgrading to version 2.8.0 of the gem to 3.0.1 on my app , this error appears when I try to run the tests after upgrade

 Failure/Error: it { is_expected.not_to allow_value("110.708.744-94").for(:cpf) }

test
it { is_expected.to allow_value('110.708.744-93').for(:cpf)  }

**Comment by mcmire** [comment]
What error message are you getting?

**Comment by vinisdl** [comment]
Failure/Error: it { is_expected.to allow_value("110.708.744-93").for(:cpf)  }
      Shoulda::Matchers::ActiveModel::AllowValueMatcher::CouldNotSetAttributeError:
        The allow_value matcher attempted to set :cpf on Deployer to
        "110.708.744-93", but when the attribute was read back, it had stored
        "11070874493" instead.
        
        This creates a problem because it means that the model is behaving in a
        way that is interfering with the test -- there's a mismatch between the
        test that was written and test that was actually run.
        
        There are a couple of reasons why this could be happening:
        
        * The writer method for :cpf has been overridden and contains custom
          logic to prevent certain values from being set or change which values
          are stored.
        * ActiveRecord is typecasting the incoming value.
        
        Regardless, the fact you're seeing this message usually indicates a
        larger problem. Please file an issue on the GitHub repo for
        shoulda-matchers, including details about your model and the test
        you've written, and we can point you in the right direction:
        
        https://github.com/thoughtbot/shoulda-matchers/issues

**Comment by mcmire** [comment]
Judging by the error message, I'm guessing that you've overridden the attribute to strip away any non-numeric characters upon being set.

Since this seems harmless, I would use `ignoring_inteference_by_writer` in this case to tell `allow_value` that it's okay that the value is getting changed. That should make the test pass.

**Comment by mcmire** [comment]
I'm going to close this issue since there's a built-in way to get around this one case.
