### ISSUE TITLE
Undefined method `has_many' for #<RSpec::ExampleGroups

### ISSUE THREAD

**Issue by BrunoQuaresma** [thoughtbot/shoulda-matchers#850]
Something strange is going on. The belongs_to and has_one methods work well but has_many not.

This error is displayed when I run the tests.
```
 Failure/Error: it {is_expected.to has_many(:page)}
     NoMethodError:
       undefined method `has_many' for #<RSpec::ExampleGroups::KlickpagesUser:0x00000007816ee0>
```

```
require 'rails_helper'

RSpec.describe Klickpages::User, type: :model do

  it {is_expected.to has_many(:page)}

end
```

Config
```
Shoulda::Matchers.configure do |config|
    config.integrate do |with|
      with.test_framework :rspec
      with.library :rails
    end
  end
```

**Comment by mcmire** [comment]
This is because it's `have_many`, not `has_many` :)

**Comment by mcmire** [comment]
And just FYI, you probably should call the association `pages` (plural) and not `page` (singular). So grammatically, a user has many pages, and it should have many pages. Does that make sense?

**Comment by BrunoQuaresma** [comment]
I agree. Sorry for the stupid question :P and thanks for the anwser
