### ISSUE TITLE
[Question] Working with belongs_to :relation, required: true

### ISSUE THREAD

**Issue by rennanoliveira** [thoughtbot/shoulda-matchers#861]
If you have something like

``` ruby
class Group < ActiveRecord::Base
  belongs_to :manager, required: true
end
```

Currently, what I can do on my specs is:

``` ruby
it { is_expected.to belong_to(:manager) }
it { is_expected.to validate_presence_of(:manager) }
```

Which does cover it for me, but I'm curious as to ideas on having something in the likes of:

``` ruby
it { is_expected.to belong_to(:manager).with_required(true) }
```

If it's in the docs, I apologize, I couldn't find it

**Comment by mcmire** [comment]
I believe this may be a newer option that we haven't added yet (I haven't heard of it).

That would be a good idea to add (although I'd have the qualifier be `required(true)` instead of `with_required(true)`).

**Comment by ojab** [comment]
In rails 5 `required: true` will be default option for `belongs_to`, so it makes sense to make it default in shoulda-matchers too.
See also #870.

**Comment by zavan** [comment]
I'm using Rals 5.0.0.beta3 with RSpec 3.5.0.beta1 and shoulda-matchers 3.1.1

Consider:

```ruby
class User < ApplicationRecord
  has_many :changesets, inverse_of: :user, dependent: :restrict_with_error
end

class Changeset < ApplicationRecord
  belongs_to :user, inverse_of: :changesets
end

RSpec.describe Changeset, type: :model do
  subject { create :changeset }

  it { is_expected.to belong_to(:user).inverse_of(:changesets) }
  it { is_expected.to validate_presence_of :user }
end
```

Rails changed the "required" balongs_to validation message.
The ` it { is_expected.to validate_presence_of :user }` assertion fails:

```
  1) Changeset should validate that :user cannot be empty/falsy
     Failure/Error: it { is_expected.to validate_presence_of :user }
     
       Changeset did not properly validate that :user cannot be empty/falsy.
         After setting :user to ‹nil›, the matcher expected the Changeset to be
         invalid and to produce the validation error "can't be blank" on :user.
         The record was indeed invalid, but it produced these validation errors
         instead:
     
         * user: ["must exist"]
```

**Comment by murbanski** [comment]
Just FYI, try `.with_message(:required)` to shorten it a little bit:)

**Comment by robbl-as** [comment]
@mcmire @stephanngamedev Isn't that issue resolved by now?

**Comment by mcmire** [comment]
@robbl-as Yup! Sorry. Not sure why this issue wasn't closed automatically. This will be in the next release, or if you're feeling adventurous, you can point to master.
