### ISSUE TITLE
belong_to doesn't work in 3.x

### ISSUE THREAD

**Issue by kimegede** [thoughtbot/shoulda-matchers#862]
`belong_to` doesn't work for me, with the newest version of `shoulda-matchers` (3.0.0 / 3.0.1).
Downgraded to `2.8.0` and it works.

## Script
```ruby
require 'rails_helper'

RSpec.describe Tag, type: :model do
  it { should belong_to(:post) }
end
```

## Error
```bash
Failures:

  1) Tag
     Failure/Error: it { should belong_to(:post) }
     NoMethodError:
       undefined method `belong_to' for #<RSpec::ExampleGroups::Tag:0x00000004ddd138>
     # ./spec/models/tag_spec.rb:6:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:53:in `block (3 levels) in <top (required)>'
     # /var/lib/gems/2.2.0/gems/database_cleaner-1.5.0/lib/database_cleaner/generic/base.rb:16:in `cleaning'
     # /var/lib/gems/2.2.0/gems/database_cleaner-1.5.0/lib/database_cleaner/base.rb:92:in `cleaning'
     # /var/lib/gems/2.2.0/gems/database_cleaner-1.5.0/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # /var/lib/gems/2.2.0/gems/database_cleaner-1.5.0/lib/database_cleaner/configuration.rb:87:in `call'
     # /var/lib/gems/2.2.0/gems/database_cleaner-1.5.0/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/rails_helper.rb:52:in `block (2 levels) in <top (required)>'

Finished in 0.13166 seconds (files took 2.3 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/models/tag_spec.rb:6 # Tag
```

**Comment by mcmire** [comment]
Did you add a `Shoulda::Matchers.configure` block to your rails_helper?

**Comment by kchandrasekera** [comment]
Thanks, adding this to `rails_helper.rb` worked for me:

Shoulda::Matchers.configure do |config|
 config.integrate do |with|
   with.test_framework :rspec
   with.library :rails
 end
end

**Comment by kimegede** [comment]
@kchandrasekera I will need to test that out! :)

**Comment by lucianosousa** [comment]
also, add: `require 'shoulda/matchers'` on `rails_helper.rb`

**Comment by mcmire** [comment]
Yup, although, it isn't necessary to require shoulda-matchers manually anymore, just fyi.

**Comment by Uysim** [comment]
Get the same problem

**Comment by olliebennett** [comment]
For any others with this problem, it's worth linking to the [changelog entry](https://github.com/thoughtbot/shoulda-matchers/blob/master/NEWS.md#300) about the backwards-incompatible change at `v3.0.0`; we need to update the way we configure Shoulda, as described in the [Getting Started Guide](https://github.com/thoughtbot/shoulda-matchers#getting-started).

**Comment by richard1986** [comment]
> Thanks, adding this to `rails_helper.rb` worked for me:
> 
> ```
> Shoulda::Matchers.configure do |config|
>  config.integrate do |with|
>    with.test_framework :rspec
>    with.library :rails
>  end
> end
> ```

It works for me, it is necessary to add 'required: true' in the Model.rb file and that's it
