### ISSUE TITLE
CouldNotSetAttributeError for decimal attribute with non-standard precision

### ISSUE THREAD

**Issue by BitPuncher** [thoughtbot/shoulda-matchers#864]
```
Failure/Error: it { is_expected.to validate_inclusion_of(:rate).in_array([0.0]) }
     Shoulda::Matchers::ActiveModel::AllowValueMatcher::CouldNotSetAttributeError:
       The allow_value matcher attempted to set :rate on
       ComplimentaryAccountType to
       #<BigDecimal:7fb8114d9718,'0.123456789E0',9(27)>, but when the
       attribute was read back, it had stored
       #<BigDecimal:7fb81ebb1a38,'0.12E0',9(18)> instead.
       
       This creates a problem because it means that the model is behaving in a
       way that is interfering with the test -- there's a mismatch between the
       test that was written and test that was actually run.
       
       There are a couple of reasons why this could be happening:
       
       * The writer method for :rate has been overridden and contains custom
         logic to prevent certain values from being set or change which values
         are stored.
       * ActiveRecord is typecasting the incoming value.
       
       Regardless, the fact you're seeing this message usually indicates a
       larger problem. Please file an issue on the GitHub repo for
       shoulda-matchers, including details about your model and the test
       you've written, and we can point you in the right direction:
       
       https://github.com/thoughtbot/shoulda-matchers/issues
```

Rate is a column created with the sql: `'rate' decimal(8,2) NOT NULL,` which gives it a precision of just 2 decimal places.

The error looks like its attempting to set the value to 0.123456789 but then complains when it gets back 0.12. There's no application code intercepting this its just ActiveRecord truncating the value based on the table definition (I presume).

The test its failing in is written as follows:
```
describe ComplimentaryAccountType do
  describe '.valid' do
    it { is_expected.to validate_inclusion_of(:rate).in_array([0]) }
  end
end
```

The model code:
```
class ComplimentaryAccountType < AccountType
  validates :rate, inclusion: { in: [0] }
end
```

**Comment by mcmire** [comment]
Cool, thanks for the report. It sounds like what we need to do is change the inclusion matcher to use a value that's equal to the length of the decimal column. There are a number of issues that are related to this exception that I am working my way through right now but hopefully I can get to this relatively soon.

**Comment by mcmire** [comment]
@BitPuncher I believe with some of the new changes I have been making, this issue is effectively resolved -- would you be willing to bump to the shoulda-matchers github repo in your Gemfile and re-run the test that was failing for you?

**Comment by mcmire** [comment]
3.1.0 is now released and it should fix this.

**Comment by BitPuncher** [comment]
Indeed it does, thank you very much.
