### ISSUE TITLE
`validate_numericality_of.only_integer` fails with `only_integer` option and integer DB type

### ISSUE THREAD

**Issue by angela4713** [thoughtbot/shoulda-matchers#873]
Hello! I'm using Ruby 2.2.3 and Rails 4.2.5 and I've got the following problem:

Migration:

```t.integer :estimated_hours, null: false```

Model:

```validates :estimated_hours, numericality: { only_integer: true }```

Spec:

```it { should validate_numericality_of(:estimated_hours).only_integer }```

Failure:

```
1) Task ActiveModel validations should only allow integers for estimated_hours
     Failure/Error: it { should validate_numericality_of(:estimated_hours).only_integer } 
    
     Shoulda::Matchers::ActiveModel::AllowValueMatcher::CouldNotSetAttributeError:
       The allow_value matcher attempted to set :estimated_hours on Task to
       0.1, but when the attribute was read back, it had stored 0 instead.
     
       This creates a problem because it means that the model is behaving in a
       way that is interfering with the test -- there's a mismatch between the
       test that was written and test that was actually run.
     
       There are a couple of reasons why this could be happening:
     
       * The writer method for :estimated_hours has been overridden and
         contains custom logic to prevent certain values from being set or
         change which values are stored.
       * ActiveRecord is typecasting the incoming value.
     
       Regardless, the fact you're seeing this message usually indicates a
       larger problem. Please file an issue on the GitHub repo for
       shoulda-matchers, including details about your model and the test
       you've written, and we can point you in the right direction:
     
       https://github.com/thoughtbot/shoulda-matchers/issues
```

I wonder if this behaviour is intended or a bug

**Comment by mareczek** [comment]
@angela4713 just yesterday I submitted #872 :-)

**Comment by mcmire** [comment]
Yup, as I indicated in that PR, this isn't really intentional, and I'm working on a way to fix it.

**Comment by mcmire** [comment]
@angela4713 This should now be fixed. Would you be willing to point to master in your app's Gemfile and see if that fixes the tests that were failing for you?

**Comment by rilian** [comment]
for me v 3.0.1 is also failing and
```ruby
gem 'shoulda-matchers', github: 'thoughtbot/shoulda-matchers', ref: '12e788f1d01be23a08237fe45eafe94313fa6214'
```

takes forever to do `bundle install`

are there any faster ways to download this commit ?

**Comment by rilian** [comment]
update: for today it worked with `gem 'shoulda-matchers', github: 'thoughtbot/shoulda-matchers'`

for me issue is resolved :tada:

**Comment by mcmire** [comment]
@rilian Good to hear! Just to make sure, was your test pretty similar to what @angela4713 posted up above?

**Comment by rilian** [comment]
yes, i had the same test with one more validation (greater than 0). i can try to run the spec without it but it feels that it will run well

**Comment by mcmire** [comment]
Okay, great! I'll consider this fixed, then, and close this.

**Comment by rilian** [comment]
thanks! do you plan to release 3.0.2 soon?

**Comment by mcmire** [comment]
@rilian Just released a new version. It's 3.1.0, since we added a new feature, but there you go!

**Comment by rilian** [comment]
:sparkles:

**Comment by angela4713** [comment]
Hi @mcmire sorry for the delay but is confirmed. It works, thanks.

**Comment by mcmire** [comment]
Cool, good to hear, thanks for getting back to me.
