### ISSUE TITLE
Use "rails_helper" in README, not "spec_helper"

### ISSUE THREAD

**Issue by cfsbsi** [thoughtbot/shoulda-matchers#875]
Hi, on this the github.com/thoughtbot/shoulda-matchers the configuration said: 

Place the following in your test or spec helper:

but it can't work, I had to put it on rails helper, if it was correct would be better, because I am new on rails and I lost a lot of time with that, thanks, sorry about something.

**Comment by cfsbsi** [comment]
sorry, I had a problem with configuration and I don't know the correct place. I am looking for a solution yet.

**Comment by mcmire** [comment]
Really sorry that this was confusing for you. I still colloquially refer to the `rails_helper` file as the "spec helper" (I should have said "whatever helper file is appropriate to your test framework" but that's too long to say). I'll correct this soon.

**Comment by cfsbsi** [comment]
Thanks about the feedback.

**Comment by TurtleShip** [comment]
I was on the same boat with @cfsbsi ...
I kept getting ```spec_helper.rb:94:in `<top (required)>': uninitialized constant Shoulda (NameError)``` when I put on the configuration to ```spec_helper.rb```

Moving the configuration to ```rails_helper.rb``` solved it though.

**Comment by mcmire** [comment]
This is now fixed in 80b791d34b7af186493cb6ecc6717cfb6b46083c.
