### ISSUE TITLE
validate_uniqueness_of fail when it should pass

### ISSUE THREAD

**Issue by psantos10** [thoughtbot/shoulda-matchers#884]
I have this model:

```ruby
# app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name, :email
  validates_uniqueness_of :email, case_sensitive: false
end
```

And this spec:

```ruby
# spec/models/user_spec.rb
require 'rails_helper'

RSpec.describe User, type: :model do
  describe "validations" do
    subject { User.new(name: 'John', email: 'john@example.com') }
    it { should validate_uniqueness_of(:email).case_insensitive }
  end
end
```

I expected this test to pass, but it still falling with following error:

`
1) User validations should validate that :email is case-insensitively unique
     Failure/Error: it { should validate_uniqueness_of(:email).case_insensitive }

       User did not properly validate that :email is case-insensitively unique.
         The record you provided could not be created, as it failed with the
         following validation errors:

         * name: ["can't be blank"]
     # ./spec/models/user_spec.rb:6:in `block (3 levels) in <top (required)>'
`
This is a bug? or I am doing something wrong?

My Environment:

Ruby 2.3.0
Rails 4.2.5
rspec-core 3.4.1
rspec-rails 3.4.0
shoulda-matchers 3.1.0

**Comment by mcmire** [comment]
It's a bug, yes. This is the same issue as #880 (so I'll close this). I'll have a fix out for this very soon.
