### ISSUE TITLE
shoulda-matchers fails with private attributes

### ISSUE THREAD

**Issue by jeremyf** [thoughtbot/shoulda-matchers#887]
From version 3.0.1 to version 3.1.0 private attribute setting can no longer be validated via Should::Matchers. Consider the following PORO.

```ruby
class ModelWithPrivateAttribute
  include ActiveModel::Validations
  validates :name, presence: true
  def initialize(name:)
    self.name = name
  end
  attr_reader :name
  private
  attr_writer :name
end
```

The following commit broke the validation, https://github.com/thoughtbot/shoulda-matchers/commit/296211211497e624dde87adae68b385ad4cdae3a, changed the attribute tests from `__send__` to `public_send`

I believe if the following changes will resolve the issue:

* Change from `#public_send ` to `#send` on [line 83](https://github.com/thoughtbot/shoulda-matchers/blob/a4b18fcc3830d4b461ee1318e70aca20fa05a1db/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb#L83)
* Change `object.respond_to?("#{attribute_name}=")` to `object.respond_to?("#{attribute_name}=", true)` on [line 157](https://github.com/thoughtbot/shoulda-matchers/blob/a4b18fcc3830d4b461ee1318e70aca20fa05a1db/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb#L157)

**Comment by mcmire** [comment]
I'm going to close this since you made a PR for this and all the information is there too.

P.S. see my comment there about this.

**Comment by jeremyf** [comment]
:+1:
