### ISSUE TITLE
delegate_method to instance variable raising error

### ISSUE THREAD

**Issue by stevenspiel** [thoughtbot/shoulda-matchers#889]
I have a test:

```rb
it { is_expected.to delegate_method(:revision).to(:@directive) }
```

which is throwing the error:

```
Failure/Error: it { is_expected.to delegate_method(:revision).to(:@directive) }
       Expected Template to delegate #revision to #@directive object
       Method calls sent to Template#@directive: (none)
```

This is what my class looks like:

```rb
class Template
    def initialize(directive)
      @directive = directive
    end

    delegate :revision, to: :@directive
end
```

If I add an `attr_reader` for `@directive` and test with `delegate_method(:revision).to(:directive)`, it works fine. Is there something I'm missing?

The full spec file is below:

```rb
describe Template do
  subject { described_class.new(double 'Directive') }

  it { is_expected.to delegate_method(:revision).to(:directive) }
end
```

**Comment by mcmire** [comment]
The `delegate_method` matcher doesn't support using an instance variable as the target -- it only supports using a method right now, unfortunately. A PR to add this is welcome, though.
