### ISSUE TITLE
Basic validates_uniqueness_of test fails

### ISSUE THREAD

**Issue by coneybeare** [thoughtbot/shoulda-matchers#893]
Using a `User` model with `case_sensitive` validation on username:

````ruby
validates :username,    presence: true, uniqueness: { case_sensitive: false }, format: {
  with: /\A[a-zA-Z0-9\-\_\.]+\z/,
  message: :malformed
}
````

...and a `user_spec` with the following shoulda-matcher:

````ruby
subject(:user) { build(:user) }
...
it { is_expected.to validate_uniqueness_of(:username).case_insensitive }
````

...the test fails complaining about username uniqueness problems. I cannot recreate the issue using the console, all validations work properly.

````bash
Failures:

  1) User validations should validate that :slug is case-insensitively unique
     Failure/Error: it { is_expected.to validate_uniqueness_of(:slug).case_insensitive }

       User did not properly validate that :slug is case-insensitively unique.
         Given an existing User whose :slug is ‹"coneybeare"›, after making a
         new User and setting its :slug to ‹"coneybeare"› as well, the matcher
         expected the new User to be invalid, but it was valid instead.
     # ./spec/models/user_spec.rb:59:in `block (3 levels) in <top (required)>'
````

I see that you have changed the way this matcher works in recent weeks... so I ask is this a bug, or am I doing something wrong here with syntax?

**Comment by leesmith** [comment]
Your error is referencing `slug`...is that a copy/paste mistake?

**Comment by coneybeare** [comment]
Yes, copy paste error sorry. I also validate uniqueness of `:slug`

**Comment by coneybeare** [comment]
I'm going to close this... sorry. It's stemming from an issue with my `friendly_id` setup changing the slug and username to something different before validation if conflict is detected.
