### ISSUE TITLE
Shoulda matcher does not work with attr_reader

### ISSUE THREAD

**Issue by RyanNaughton** [thoughtbot/shoulda-matchers#895]
I think this issue should be re-opened: https://github.com/thoughtbot/shoulda-matchers/issues/764

A presence check should not rely upon the ability to use a setter method. There are many legitimate cases where you don't want to expose a setter, but you still need to ensure that the attribute is present.

My suggestion is that shoulda should stub the attribute getter method to return nil to check that the validation fails and stub it to return a non-nil value to ensure the validation passes.

Part of the reason is that in reality the attributes being checked don't even have to be simple getters. The presence check could be for a virtual attribute. Since the validation is really just calling that method, the best way to test it in my view is to stub the method.

**Comment by eccyan** [comment]
I have the same problem. I use this workaround:

```ruby
  describe 'properties' do
    subject { FactoryGirl.create :user }
    before do
      subject.singleton_class.class_eval do
        attr_accessor :some_virtual_attribute
      end
    end
    it { should validate_presence_of(:some_virtual_attribute) }
  end
```

Rails can use validations for virtual attributes, so I think I want a method does not use the Setter as @RyanNaughton  says.

**Comment by mcmire** [comment]
@RyanNaughton @eccyan Sorry for the late reply on this, I've been out. Can you give me an example of a read-only attribute that you want to check for the presence of?

**Comment by mcmire** [comment]
I've reopened the issue you mentioned, so I'm closing this one.
