### ISSUE TITLE
Missing dependency for `test-unit` with Ruby 2.3/Rails 3.x

### ISSUE THREAD

**Issue by chrisccerami** [thoughtbot/shoulda-matchers#896]
Our app is on Rails `3.2.22` and we recently looked into upgrading our Ruby version to `2.3.0`. Because `test-unit` is no longer included with Ruby in `2.3.0`, we can no longer use `shoulda-matchers` without separately adding `test-unit` to our Gemfile. I was wondering if there's any interest in still patching older versions, like creating a `2.8.1` of `shoulda-matchers` that includes `test-unit`, to keep its dependencies internal to the gem.

**Comment by mcmire** [comment]
I don't think having to add `test-unit` to your Gemfile is unexpected. `shoulda-matchers` doesn't use or tie into any part of Test::Unit -- in fact, it's designed specifically for RSpec (although there is some bridge code in `shoulda-context` so you can use RSpec matchers there, but that's different). So it wouldn't make sense for us to include `test-unit` in the gemspec. Sorry.
