### ISSUE TITLE
Two conflicting shoulda matchers allow_value expressions are both passing

### ISSUE THREAD

**Issue by mutant-city** [thoughtbot/shoulda-matchers#905]
`:speed`is simply a numeric model attribute.

Both of these are passing:     

```
    it { is_expected.to allow_value( '1').for(:speed) }
    it { is_expected.not_to allow_value( '1', 'fff' ).for(:speed) }
```

With a minor change, the second one is not passing:    

```
    it { is_expected.to allow_value( '1').for(:speed) }
    it { is_expected.not_to allow_value( '1' ).for(:speed) }
```

Apparently, if there's a single passing value in the `not_to allow_value` expression the whole list of values passes.  

I'm not quite understanding if it's working as intended and I'm doing it wrong, or if it's a bug.

It seems like it's a bug according to how the documentation explains it.

Also, I'm on Sinatra.  And additionally,  the allow_values matcher doesn't exist for me.
I updated my gems to no avail and there's no version lock on Shoulda matchers in my gem file.

**Comment by nkiermaier** [comment]
It almost seems like the boolean logic is such that it reverses the entire statement instead of just the return value.
So that while ```expected.to allow_value``` FAILS if one value in the list fails.... ```expected.not_to allow_value``` PASSES as long as one value passes.

**Comment by nkiermaier** [comment]
Also, I'm on Sinatra.

**Comment by eliaszica** [comment]
+1

**Comment by mcmire** [comment]
@nkiermaier @eliaszica We changed this behavior in 3.0 -- it used to be reversed, now it follows the logic as listed in the docs:

> In the positive sense, this makes an assertion that none of the values cause the record to be invalid. In the negative sense, this makes an assertion that none of the values cause the record to be valid.

Which version of shoulda-matchers are you using?

**Comment by eliaszica** [comment]
@mcmire I'm using minitest, so, according to documentation, I can't use  3.0. Any hint?

 >$ gem list | grep shoulda
 >shoulda (3.5.0)
 >shoulda-context (1.2.2)
 >shoulda-matchers (2.8.0)

Thanks,

Elias

**Comment by mcmire** [comment]
@eliaszica Ahh... ok. Yeah... shoulda (and really at this point shoulda-context) isn't quite compatible with 3.0 just yet. There's an issue tracking this here: https://github.com/thoughtbot/shoulda-context/issues/53. Hopefully I can get some time to work on this soon, although help is certainly appreciated.

**Comment by mcmire** [comment]
Closing this since it doesn't seem like there is a bug here, only a misunderstanding.
