### ISSUE TITLE
NoMethodError: undefined method negative_failure_message for Shoulda::Matchers::ActiveModel::AllowValueMatcher

### ISSUE THREAD

**Issue by ajvondrak** [thoughtbot/shoulda-matchers#906]
Using Minitest 5.8.4, shoulda-context 1.2.1, and shoulda-matchers 3.1.1 with an assertion like

```ruby
class FooTest < ActiveSupport::TestCase
  should_not allow_values(:a, :b, :c).for(:bar)
end
```

When there's a logical failure in the test, we try to show a negated failure message. However, it seems like shoulda-context and/or shoulda-matchers winds up trying to call `negative_failure_message`, which raises ```NoMethodError: undefined method `negative_failure_message' for #<Shoulda::Matchers::ActiveModel::AllowValueMatcher:0x007fbe9701e980>```

Poking around the code bases, it looks like the shoulda-matchers method names were updated to be RSpec 3.0 compliant, like `failure_message_when_negated`, but not all of them define an alias back to the old-style `failure_message_for_should_not`. Ergo, this bit of code in shoulda-context tries to call `negative_failure_message` (not sure where this name comes from):

```
~/.rvm/gems/ruby-2.3.0/gems/shoulda-context-1.2.1$ ack --ruby negative_failure_message
lib/shoulda/context/assertions.rb
57:            message = matcher.respond_to?(:failure_message_for_should_not) ? matcher.failure_message_for_should_not : matcher.negative_failure_message
82:          message = matcher.respond_to?(:failure_message_for_should_not) ? matcher.failure_message_for_should_not : matcher.negative_failure_message

test/shoulda/helpers_test.rb
144:                                 :negative_failure_message => 'bad failure message')
```

This can be fixed by either (a) updating shoulda-context (possibly a better solution, I'm not sure) or (b) setting up the `alias` in the `AllowValueMatcher`, which I've monkey-patched into my test_helper.rb like so:

```ruby
Shoulda::Matchers::ActiveModel::AllowValueMatcher.class_eval do
  alias :failure_message_for_should_not :failure_message_when_negated
end
```

Not sure what other matchers are missing this alias as well. Probably worth investigating.

**Comment by mcmire** [comment]
Yeah, I think a better place for the fix would be in shoulda-context. I'll file a bug over there, and close this.
