### ISSUE TITLE
undefined method `scoped_to' for :login:Symbol

### ISSUE THREAD

**Issue by otavioschwanck** [thoughtbot/shoulda-matchers#908]
When i try to validate uniqueness i get the error:

undefined method `scoped_to' for :login:Symbol

I have the follow code:
`      it { is_expected.to validate_uniqueness_of (:name).scoped_to(:login)}
      it { is_expected.to validate_uniqueness_of (:login).scoped_to(:login)}`

in model class:

	validates_uniqueness_of :login, :name, scope: :login

Shoulda Matcher version: 2.8.0

**Comment by mcmire** [comment]
Sorry for the late reply on this, but you have an unnecessary space after `validate_uniqueness_of`, and Ruby is interpreting the code you've written differently. Instead of saying:

```
it { is_expected.to validate_uniqueness_of (:login).scoped_to(:login)}
```

you need to say:

```
it { is_expected.to validate_uniqueness_of(:login).scoped_to(:login)}
```
