### ISSUE TITLE
undefined method 'belong_to'

### ISSUE THREAD

**Issue by ArielAleksandrus** [thoughtbot/shoulda-matchers#930]
When I use "belong_to", it gives me this error:

> 1) App 
>      Failure/Error: it { should belong_to(:enterprise) }
>      
>      NoMethodError:
>        undefined method `belong_to' for #<RSpec::ExampleGroups::App:0x00000006e85688>
>      # ./spec/models/app_spec.rb:4:in `block (2 levels) in <top (required)>

If I use have_many, have_one, etc, it works (of course, I'm getting an error as this relationship does not exist in my model, but at least it does not give me "undefined method" error):

>   1) App should have one :enterprise
>      Failure/Error: it { should have_one(:enterprise) }
>        expected #<App:0x000000071e63b8> to respond to `has_one?`
>      # ./spec/models/app_spec.rb:4:in `block (2 levels) in <top (required)>'

And in my **rails_helper.rb** file, just before `Rspec.configure do |config` line, I have

```
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    # Choose a test framework:
    with.test_framework :rspec
  end
end
```

What could be the problem? Might be that I didn't include the `with.library ...` line? I'm using mongoid. I can't set library to "active_record" nor "rails"

**Comment by mcmire** [comment]
shoulda-matchers isn't compatible with Mongoid, sorry. We welcome PRs to add support, but in the meantime, you might try using [mongoid-rspec](https://github.com/mongoid-rspec/mongoid-rspec).

**Comment by jasonperrone** [comment]
So why am I getting this same error with just rails ActiveSupport:TestCase:
/home/jason/Workspace/actioncue/test/models/accused_test.rb:5:in `<class:AccusedTest>': undefined method `belong_to' for AccusedTest:Class (NoMethodError)

class AccusedTest < ActiveSupport::TestCase

  should belong_to :event

.
..

**Comment by jasonperrone** [comment]
Interesting. This config block seemed to fix it:
houlda::Matchers.configure do |config|
  config.integrate do |with|
    # Choose a test framework:
    with.test_framework :rspec
    with.test_framework :minitest
    with.test_framework :minitest_4
    with.test_framework :test_unit

    # Choose one or more libraries:
    with.library :active_record
    with.library :active_model
    with.library :action_controller
    # Or, choose all of the above:
    with.library :rails
  end
end

When did this start?

**Comment by mcmire** [comment]
@jasonperrone This was introduced in 3.0.0: https://github.com/thoughtbot/shoulda-matchers/blob/master/NEWS.md#300

**Comment by jasonperrone** [comment]
Thank you!! How the heck did I miss this page?! :/

**Comment by bmuhamood** [comment]
Hi, Instead of using "**belong_to**", Just use "**belongs_to**" i was forgetting to add **'s'** and was getting this error.

**Comment by mcmire** [comment]
@bmuhamood Sorry but I'm not sure how that would work. `belongs_to` is the name of the macro, but `belong_to` is the name of the matcher. Which version of shoulda-matchers are you using?
