### ISSUE TITLE
Help needed with using matchers manually

### ISSUE THREAD

**Issue by samstickland** [thoughtbot/shoulda-matchers#931]
Hi,

I'm trying to call the ActiveModel matchers manually*, but I get a weird error on the `failure_message_when_negated` method.

This is attempting a manual invoking of `.to_not validate_presence_of(:name)` when name's presence is actually validated on the model.

```
> matcher = Shoulda::Matchers::ActiveModel::ValidatePresenceOfMatcher.new(:name)
> matcher.matches?(Company.new)
=> true
> matcher.failure_message_when_negated
NoMethodError: undefined method `attribute_setter' for nil:NilClass
```

If I simulate the alternative situation, i.e. checking for the presence of :bank_name (who's presence isn't validated), then it works OK:

```
> matcher = Shoulda::Matchers::ActiveModel::ValidatePresenceOfMatcher.new(:name)
> matcher.matches?(Company.new)
=> true
> matcher.failure_message
=> "Company did not properly validate that :bank_name cannot be empty/falsy.\n  After setting :bank_name to ‹nil›, the matcher expected the Company to\n  be invalid, but it was valid instead."
```

Any idea when I can't retrieve the value of `failure_message_when_negated`? 

The simple answer is that `result` is nil inside `AllowValueMatcher#failure_message_when_negated` but not `AllowValueMatcher#failure_message`, but I don't understand why.

_\* long story, but basically I'm trying to create matchers for a Trailblazer enabled project. These matchers will alter the subject to be the Reform contract_

**Comment by mcmire** [comment]
Can you paste the backtrace you're getting?

**Comment by misham** [comment]
This looks like it's related to #904 

Any progress on this?

**Comment by mcmire** [comment]
It is related to #904, yes. I'm going to close this issue in favor of that one. I'll have a fix for this soon.

**Comment by mcmire** [comment]
Actually, I'll leave this open in the meantime, sorry - want to make sure I catch all instances of these.

**Comment by samstickland** [comment]
Thanks for looking into this!
