### ISSUE TITLE
ActiveModel matchers on Ruby objects don't work with inferred spec type

### ISSUE THREAD

**Issue by Drenmi** [thoughtbot/shoulda-matchers#936]
We're using `ActiveModel::Model` and `ActiveModel::Validation` to create some basic form objects in our applications. In order to add matchers to these objects, we use the following configuration (taken from the `README`):

```
config.include(Shoulda::Matchers::ActiveModel, type: :form)
```

This works well as long as you use an explicit `type: :form` in your spec file, e.g.:

```
RSpec.describe SignInForm, type: :form do
  it { is_expected.to validate_presence_of(:email) }
  it { is_expected.to validate_presence_of(:password) }
end
```

but together with `#infer_spec_type_from_file_location!`, this spec will fail.

Environment:

- `rspec-rails: 3.4.2`
- `shoulda-matchers: 3.1.1`

**Comment by mcmire** [comment]
Unfortunately, using `#infer_spec_type_from_file_location!` doesn't mean that you can put your tests in any arbitrary directory underneath `spec`. There are only [certain directories]((https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/configuration.rb#L27)) that RSpec knows about, and `spec/forms` isn't one of them.

**Comment by Drenmi** [comment]
Thanks for the pointer @mcmire. I just found [this](https://github.com/rspec/rspec-rails/blob/5612e0d45ac4994fa72db41e611b4c6cbc2a33b6/lib/rspec/rails/configuration.rb#L27).

I guess not much to do here, then, as this is more of a potential feature request to `rspec-rails`. 😀
