### ISSUE TITLE
permit do not restrict parameters

### ISSUE THREAD

**Issue by jameslafa** [thoughtbot/shoulda-matchers#938]
I'm using the following gems:
````
 - shoulda-matchers (3.1.1)
 - rails (4.2.6)
 - rspec (3.4.0)
````
I have the following controller

````ruby
class BookmarksController < ApplicationController

  def create
    @bookmark = Bookmark.new(bookmark_params)
    ...
  end

private
  def bookmark_params
    params.require(:bookmark).permit(:title, :description, :url, :user_id)
  end
end
````

I added `:user_id` on purpose to generate an error. This params shouldn't be permitted.

I have the following test:
````ruby
   it do
      params = {bookmark: {title: 'title', description:'description', url: 'url', user_id: 1)}
      should permit(:title, :description, :url).
      for(:create, params: params).on(:bookmark)
    end
````

The test pass:
````
BookmarksController
  with a signed_in user
    should (for POST #create) restrict parameters on :bookmark to :title, :description, and :url
````

My understand was that it should trigger an error because it also permits `:user_id`.
Am I misunderstanding this matcher or is there an issue here?

**Comment by mcmire** [comment]
Well, you can view this two ways. The goal of strong parameters is to let you establish a whitelist of parameters, not a strict list of required parameters. In your case `:user_id` isn't a required parameter. If the controller does not receive this parameter, then nothing bad will happen. Now if it receives something different than `:title`, `:description`, `:url`, or `:user_id`, _then_ something bad will happen. But omitting any of those parameters is okay.

The `permit` matcher acts the same way -- you give it a list of parameters that the controller should permit, and if the controller permits all of them, then you're okay. In this case, you're making an expectation that the controller permits `:title`, `:description`, and `:url`. This is perfectly fine -- the controller will have no issues with these parameters. So the test passes.

Now, I can understand why you would think that the matcher should fail here -- the whitelist that you're using isn't exactly the same as the whitelist that the controller is using. However, it isn't really a bug in my opinion, so it would require a backward-incompatible change to the matcher to make this happen. I'm not so sure that's worth it right now.

Does that make sense?

**Comment by jameslafa** [comment]
Thanks for your answer. It does make sense and I actually found a simple way to do exactly what I wanted:

````ruby
    it do
      params = attributes_for(:bookmark, user_id: 1)

      should permit(:title, :description, :url).
      for(:create, params: {bookmark: params}).on(:bookmark)

      should_not permit(:user_id).
      for(:create, params: {bookmark: params}).on(:bookmark)
    end
````

This test that the right params are allowed and also test that no one, by mistake, add later :user_id, which could lead to a security problem.

So everything is perfect. Thanks again for this great gem!
