### ISSUE TITLE
Weird error message on should_not validate_inclusion_of(:attribute)

### ISSUE THREAD

**Issue by gmmcal** [thoughtbot/shoulda-matchers#939]
Scenario

> Model
> - validates :attribute, inclusion: { in: 1940..Date.today.year, allow_nil: true}, on: :update

And on test file

> model_spec.rb
> it { should_not validate_inclusion_of(:birth_year).on(:create) }

After I run the test, it passes, but I get a weird output on console using doc format

> example at ./spec/models/model_spec.rb:<a line number> (Got an error when generating description from matcher: NoMethodError: undefined method `many?' for nil:NilClass -- <path to gems on rvm>/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:365:in`simple_description')

For me, looks like a simple fix, but I couldn't find the proper place for the fix. If you could guide me to it, I can send a PR for this too.

**Comment by mcmire** [comment]
You might be simply missing the `in_range` qualifier:

```
it { should_not validate_inclusion_of(:birth_year).in_range(1940..Date.today.year).on(:create) }
```

[Here's](https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb#L375) the relevant code for the `validate_inclusion_of` matcher. There should probably be something in `#matches?` that confirms that either `@array` or `@range` is set, and asks the user to use `in_array` or `in_range` if it's not.

**Comment by gmmcal** [comment]
@mcmire do you think that making the test fail for my case with an else on L389 would be a good solution?

**Comment by mcmire** [comment]
Yup, that makes sense to me.

Don't worry about the tests, I can fill that in. Thanks!

**Comment by gmmcal** [comment]
@mcmire I think this issue is fixed. tecnically, PR was merged. Haven't tested, tbh.

**Comment by mcmire** [comment]
Closing this — if this comes up again, we can open another issue.
