### ISSUE TITLE
doc formatter not to use should with rspec 3+

### ISSUE THREAD

**Issue by tejasbubane** [thoughtbot/shoulda-matchers#942]
With `rspec 3` and using the new `expect` syntax:

```
    it { is_expected.to have_many(:admin_roles) }
    it { is_expected.to have_many(:roles) }
```

Results in the following output for `rspec -f doc`:

```
    should have many admin_roles
    should have many roles
```

I expect the messages to not use `should` and be something like this instead:

```
    has many admin_roles
    has many roles
```

We can provide a config option for those who prefer this style of documentation.

**Comment by mcmire** [comment]
RSpec uses a matcher's #description method to print out those lines for the `documentation` formatter. [We don't put "should" in the string that #description returns](https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_record/association_matcher.rb#L955), so my assumption was that this comes from RSpec, although I'm not able to find that code at the moment.

**Comment by mcmire** [comment]
Okay, I believe this has to do with the one-liner syntax specifically. [Here's the Relish docs](https://relishapp.com/rspec/rspec-core/v/3-4/docs/subject/one-liner-syntax) that talk about that; it shows that the lines which the documentation formatter prints out start with `should` or `should not`. It looks like that is coming from [here](https://github.com/rspec/rspec-expectations/blob/master/lib/rspec/expectations/handler.rb#L55) (which travels up the chain to [here](https://github.com/rspec/rspec-expectations/blob/master/lib/rspec/matchers/generated_descriptions.rb#L21)).

**Comment by mcmire** [comment]
Does that make sense?

**Comment by mcmire** [comment]
(I'm going to close this issue just to keep things tidy.)
