### ISSUE TITLE
Rails 5 has_secure_token matcher

### ISSUE THREAD

**Issue by brielov** [thoughtbot/shoulda-matchers#950]
It would be nice to have a similar behaviour like has_secure_password, but for token (has_secure_token).

**Comment by mcmire** [comment]
Unfortunately I don't have much time these days to add any new features but if this is something that you personally want then feel free to submit a PR and we will certainly merge it in.

I'm going to close this since we don't tend to keep feature requests open (to keep the list clean).

**Comment by Techbrunch** [comment]
Implemented in #1025
