### ISSUE TITLE
Support env named parameter to import SERVER_PORT header.

### ISSUE THREAD

**Issue by zw963** [thoughtbot/shoulda-matchers#954]
Rails 5 could not get @request object in ActionDispatch::IntegrationTest,
But it support a env name args to support import SERVER_PORT header.

``` cl
get api_v1_test_hello_url,
      params: { name: 'new_name' },
      env: { 'SERVER_PORT' => '8629' }
```

How to do this in should-matcher ? 

Thanks.

**Comment by zw963** [comment]
I have test like this, it told me no should method exist.

```rb
class RoutesTest < ActionController::TestCase
  include Shoulda::Matchers::ActionController
  setup { request.env['SERVER_PORT'] = '8629' }
  test 'test case' do
    should route(:get, 'v1/test/hello').to('api/v1/test#hello')
  end
end
```

If change to this:
```rb
class RoutesTest < ActionController::TestCase
  include Shoulda::Matchers::ActionController
  setup { request.env['SERVER_PORT'] = '8629' }
  should route(:get, 'v1/test/hello').to('api/v1/test#hello')
end
```

should exist, but `request.env` is not valid.

**Comment by mcmire** [comment]
It looks like the `env` argument that `get`, `post`, etc. takes refers to the Rack environment hash. Setting `SERVER_PORT` doesn't actually change the Rack env, however -- [it gets used to build the URL](https://github.com/rails/rails/blob/3e45dd988cad539fe2cbc79b505fde99a44472e8/actionpack/lib/action_dispatch/testing/integration.rb#L396).

That said -- `route` doesn't actually hit a URL, it only checks to make sure that a combination of request method and corresponds to a controller/action pair. So I don't see why you need to set `SERVER_PORT` here.

**Comment by zw963** [comment]
because i need test route which use constraint to limit only special port can be access。

**Comment by mcmire** [comment]
Oh, interesting. I didn't know you could do that.

[Under the hood]](https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/action_controller/route_matcher.rb#L131) the `route` matcher actually uses Rails' [`assert_routing`](http://api.rubyonrails.org/classes/ActionDispatch/Assertions/RoutingAssertions.html#method-i-assert_routing) test helper under the hood. There doesn't seem to be a way to specify a port with that, either. One would think it would be possible to specify a full URL (`assert_routing("http://foo.com:1234/my/path", ...)`), but I'm not sure if that works or not.

If you can figure out a way to get `assert_routing` to do this then perhaps we can get `route` to do this, too.

**Comment by zw963** [comment]
I just tried it. It worked!

```rb
class RoutesTest < ActionDispatch::IntegrationTest
  test 'route' do
   # asdfasdf can be replace to any char.
    assert_routing('http://asdfasdf.com:8629/v1/test/hello', controller: 'api/v1/test', action: 'hello')
  end
end
```

**Comment by zw963** [comment]
And, following is worked too. 

```rb
class RoutesTest < ActionController::TestCase
  should route(:get, 'http://example.com:8629/v1/test/hello').to('api/v1/test#hello')
end
```

Thanks.

**Comment by zw963** [comment]
Maybe should close by you.

Rails 5 current exist `headers: {...}` and `env: {...}` named argument
which I don't know support by shoulda-matcher.

Anywhy, port problem is resolved.

**Comment by mcmire** [comment]
Glad you got it working!

I'm not sure what all of the possible values of `env` can be, so perhaps it's worth it to only support `SERVER_PORT`. Then again, the `route` matcher isn't intended to completely emulate `get`, `post`, etc., so perhaps we just add a `port` option, such as:

``` ruby
should route(:get, '/v1/test/hello', port: 8629).to('api/v1/test#hello')
```

We'll have to come to some kind of decision on this.

**Comment by zw963** [comment]
Cool, maybe `format` and `port` is the most useful arguments for route test.

for me, I only occur those two case in recent project.

Thanks.

**Comment by mcmire** [comment]
Okay, this has been added like so:

```
it { should route(:get, '/my/path', port: 1234).to('controller#action')
```

**Comment by zw963** [comment]
Cool, will try it later. 

Thanks
