### ISSUE TITLE
validate_numericality_of().is_greater_than fails for integers

### ISSUE THREAD

**Issue by odedmagger** [thoughtbot/shoulda-matchers#966]
Model code:

```
#  payment_n               :integer
validates :payment_n, numericality: {greater_than: 0, only_integer: true}
```

RSpec code:

Tried both:
`it { should validate_numericality_of(:payment_n).is_greater_than(0) }`
and
`it { should validate_numericality_of(:payment_n).is_greater_than(0).only_integer }`

In both cases, running the test yields the following error:

> ArgumentError: comparison of Fixnum with nil failed

I am using version **3.1.1**

Note: when payment_n is decimal and not integer, the test passes.

It sounds somewhat similar to https://github.com/thoughtbot/shoulda-matchers/issues/481, but with a different error (and a later version, of course).

If this isn't an issue and I'm just using the wrong syntax/methods , please let me know. Thanks!

**Comment by mcmire** [comment]
@odedmagger That's interesting. Can you a provide a backtrace for this?

**Comment by marceloperini** [comment]
Same problem with me. But I realized that it happens when I added the presence validation to attribute:

``` ruby
validates :slots, presence: true
validates :enrolled, numericality: { only_integer: true, greater_than_or_equal_to: 0,
                               less_than_or_equal_to: :slots }
```

tests cases:

``` ruby
subject(:offer) { build(:offer) }

it { is_expected.to validate_presence_of(:slots) }
it do
  expect(offer)
    .to validate_numericality_of(:enrolled).is_greater_than_or_equal_to(0)
                                                                .is_less_than_or_equal_to(offer.slots)
                                                                .only_integer
    end
```

this returns:

```
1) Offer validations should validate that :slots cannot be empty/falsy
     Failure/Error: it { is_expected.to validate_presence_of(:slots) }
     
     ArgumentError:
       comparison of Integer with nil failed
```

### System
**ruby version:** ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
**rails version:** 5.1.6.2
**shoulda-matcher version:** 4.0.1

**Comment by mcmire** [comment]
@marceloperini Try adding an `allow_nil: true` option to your numericality validation in your model. That will instruct Rails to not run that validation if `slots` is nil.

**Comment by marceloperini** [comment]
> @marceloperini Try adding an `allow_nil: true` option to your numericality validation in your model. That will instruct Rails to not run that validation if `slots` is nil.

It's not worked. But if I add `if: ->(object_model) { object_model.slots.present? }` on numericality validation works.

``` ruby
validates :enrolled, numericality: { less_than_or_equal_to: :slots },
                       if: ->(offer) { offer.slots.present? }
```

**Comment by marceloperini** [comment]
@mcmire I think this is not an issue from Shouda Matchers, this is an issue from ActiveModel. Because if I run this on console, using the same validation explained from my first commentary:

```
offer = FactoryBot.build(:offer, slots: nil)
offer.valid?
```

raises the same error: `ArgumentError: comparison of Integer with nil failed`

**Comment by mcmire** [comment]
@marceloperini Yup, exactly! ActiveModel is attempting to run your numericality validation by calling `slots` and making use of its return value. But if `slots` is nil, it can't do that. Hence the `if` or `allow_nil` / `allow_blank`, so that if `slots` is nil, then it will skip that validation.

**Comment by marceloperini** [comment]
> @marceloperini Yup, exactly! ActiveModel is attempting to run your numericality validation by calling `slots` and making use of its return value. But if `slots` is nil, it can't do that. Hence the `if` or `allow_nil` / `allow_blank`, so that if `slots` is nil, then it will skip that validation.

yep, you're right! Thanks.

**Comment by mcmire** [comment]
Closing this, since there hasn't been much activity in a while. If this is still a problem let me know and I'll reopen.
