### ISSUE TITLE
Improve ExistingRecordInvalid message

### ISSUE THREAD

**Issue by mcmire** [thoughtbot/shoulda-matchers#967]
The ExistingRecordInvalid exception (Shoulda::Matchers::ActiveRecord::ValidateUniquenessOfMatcher::ExistingRecordInvalid is the full name) is really awesome! However, we can do better than this. It says this...

> The best way to fix this is to provide the matcher with a record where any required attributes are filled in with valid values beforehand.

...but doesn't give an example of how to do this. We should either give such an example, or link to an explicit doc page on http://matchers.shoulda.io/docs/.

**Comment by djones** [comment]
I was getting this error. You might have an example like this:

```ruby
RSpec.describe OperatingSystem, type: :model do
  describe 'validations' do
    it { is_expected.to validate_uniqueness_of :name }
  end
end
```

If you have `null: false` and no default value set on the name attribute, you will see an error like this:

```
Shoulda::Matchers::ActiveRecord::ValidateUniquenessOfMatcher::ExistingRecordInvalid:
 validate_uniqueness_of works by matching a new record against an
 existing record. If there is no existing record, it will create one
 using the record you provide.

 While doing this, the following error was raised:

   Mysql2::Error: Field 'name' doesn't have a default value: INSERT INTO `operating_systems` (`created_at`, `updated_at`) VALUES ('2017-07-31 22:29:08', '2017-07-31 22:29:08')

 The best way to fix this is to provide the matcher with a record where
 any required attributes are filled in with valid values beforehand.
```

To fix this, you would install FactoryGirl and make the following changes:

```ruby
RSpec.describe OperatingSystem, type: :model do
  describe 'validations' do
    subject { create(:operating_system) }
    it { is_expected.to validate_uniqueness_of :name }
  end
end

FactoryGirl.define do
  factory :operating_system do
    name "Windows"
  end
end
```

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
