### ISSUE TITLE
Validating uniqueness fails with Rails helper present

### ISSUE THREAD

**Issue by grammakov** [thoughtbot/shoulda-matchers#969]
Getting the validation test fail on Rails 5 with shoulda 3.1.1:

```
class Obj < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  ...
```

```
require 'rails_helper'

RSpec.describe Obj, type: :model do
  before(:each) { @obj = Obj.new(name: 'Test name', description: 'Test description') }

  subject { @obj }

  it { should validate_uniqueness_of(:slug) }
end
```

`Algorithm did not properly validate that :slug is case-sensitively unique.`

**Comment by mcmire** [comment]
Unless the code you gave above was just an example, you have a uniqueness validation on `:name`, but you're testing that the validation is on `:slug`.
