### ISSUE TITLE
set_flash and redirect_to do not work as expected

### ISSUE THREAD

**Issue by edwardmp** [thoughtbot/shoulda-matchers#974]
Thanks for publishing this, its very convenient.

However, I am stumbling upon two issues:
```
class CompaniesControllerTest < ActionDispatch::IntegrationTest
 context "an user with role company admin" do
    setup {
      sign_in(users(:user_company_admin))
      get new_company_url
    }

    should redirect_to { root_path } # leads to redirect_to_matcher.rb:38:in `redirect_to': wrong number of arguments (given 0, expected 1)
    should set_flash.now[:alert].to(/not authorized/) # leads to Module::DelegationError: ActionController::Base#flash delegated to request.flash, but request is nil
  end
end
```

Am I doing something wrong? I use it with minitest 5

**Comment by mcmire** [comment]
Hey there. Two things:

* When passing a block to `redirect_to`, the matcher still requires a non-block argument. This is a string and describes the path you're redirecting to. It's used to print something meaningful to stdout when the tests are being run (and you're using a formatter that prints names of tests). So in your case, you could use `should redirect_to("/") { root_path }`.
* The error you're seeing with `set_flash` may be a bug. Can you post a backtrace (redacting anything that's personal information)?

**Comment by edwardmp** [comment]
Thanks for the quick response, awesome.

Regarding redirect_to that makes sense. The documentation is not correct in this regard. I'll submit a pull request to fix this.

Here's a full stack trace for the `set_flash` issue:

Module::DelegationError: ActionController::Base#flash delegated to request.flash, but request is nil: ```
#<CompaniesController:0x00556d1192b778 @_action_has_layout=true, @_routes=nil, @_request=nil, @_response=nil>
    /usr/local/bundle/gems/actionpack-5.0.0.1/lib/action_controller/metal/flash.rb:9:in `rescue in flash'
    /usr/local/bundle/gems/actionpack-5.0.0.1/lib/action_controller/metal/flash.rb:9:in `flash'
    /usr/local/bundle/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/action_controller/flash_store.rb:54:in `copy_of_flash_from_controller'
    /usr/local/bundle/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/action_controller/flash_store.rb:50:in `flash'
    /usr/local/bundle/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/action_controller/flash_store.rb:39:in `empty?'
    /usr/local/bundle/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/action_controller/set_session_or_flash_matcher.rb:41:in `matches?'
    /usr/local/bundle/gems/shoulda-context-1.2.1/lib/shoulda/context/assertions.rb:54:in `assert_accepts'
    /usr/local/bundle/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:344:in `block in should'
    /usr/local/bundle/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `instance_exec'
    /usr/local/bundle/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `block in create_test_from_should_hash'
```

**Comment by edwardmp** [comment]
I've opened a pull request to tackle the documentation issue: https://github.com/thoughtbot/shoulda-matchers/pull/975

Not sure if this extra parameter is also required in the RSpec case?

**Comment by mcmire** [comment]
@edwardmp Yup, as it turns out, it is required in the RSpec case too.

**Comment by edwardmp** [comment]
@mcmire cool, added a commit for that as well. I do have to say, wouldn't it be better to derive this description from the passed path directly so there is no need for such an extra parameter?

**Comment by vasudhar** [comment]
How to fix that set_flash issue? any resolutions ?

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
