### ISSUE TITLE
Numericality matcher does not work correctly with decimals.

### ISSUE THREAD

**Issue by jonnyjava** [thoughtbot/shoulda-matchers#976]
Issue created after this https://github.com/thoughtbot/shoulda-matchers/issues/970#issuecomment-259208361
Actually found using shoulda-matchers-3.1.1, rspec-3.4.0 and rails-4.2.5 
How to reproduce it
```
create_table "stuffs", force: :cascade do |t|
  t.decimal  "amount", precision: 8, scale: 2
en

class Stuff < ActiveRecord::Base
  validates :amount, numericality: true
end

it { expect(stuff).to validate_numericality_of(:amount) }
```
Raised error
```
Stuff did not properly validate that :amount looks like a number.
         After setting :amount to ‹"abcd"› -- which was read back as
         ‹#<BigDecimal:63174b8,'0.0',9(18)>› -- the matcher expected the
         Stuff to be invalid, but it was valid instead.
```
It seems that the matcher doesn't know that if I do `'a'.to_i` it can never give an error as 'is not a number' because is converted to `0.0`

**Comment by tjjjwxzq** [comment]
Similar error encountered with shoulda-matchers-3.1.1 when trying to run numericality validations on a monetized field (money-rails 1.7.0)

My form object, which accesses the monetized fields on the model it's wrapping, has the following validations
```
  validates :club_income_fund, numericality: { greater_than_or_equal_to: 0 }
  validates :club_seed_fund, numericality: { greater_than_or_equal_to: 0 }
  validates :donation_or_sponsorship, numericality: { greater_than_or_equal_to: 0 }
```
The errors raised:

```
EventProposal::ProjectFinancesForm did not properly validate that
       :club_income_fund looks like a number greater than or equal to 0.
         After setting :club_income_fund to ‹"abcd"› -- which was read back as
         ‹#<Money fractional:0 currency:SGD>› -- the matcher expected the
         EventProposal::ProjectFinancesForm to be invalid, but it was valid
         instead.

         As indicated in the message above, :club_income_fund seems to be
         changing certain values as they are set, and this could have something
         to do with why this test is failing. If you've overridden the writer
         method for this attribute, then you may need to change it to make this
         test pass, or do something else entirely.
```

and likewise for the other two validated attributes. 

Not sure why it's trying to set the attributes to string values, when I'm running a `greater_than_or_equal_to` validation.

**Comment by troyanryller** [comment]
made temporary fix which disable assigning 'abcd' string if type is decimal
https://github.com/thoughtbot/shoulda-matchers/pull/996/commits/d1367a51a6586ce874b2a0ca63ef1947ae67b5b8

**Comment by mcmire** [comment]
I've tried to replicate this in a fresh Rails app (4.2, 5.0 and 5.1) using shoulda-matchers 3.1.2 and I can't seem to do this.

I'm going to close this for now, but if you would, please fork https://github.com/mcmire/shoulda-matchers-test-apps, replicate this in a fresh Rails app there, and send me a link to your fork so I can take a closer look.
