### ISSUE TITLE
`have_one` doesn't do a full check on `through` associations

### ISSUE THREAD

**Issue by mcmire** [thoughtbot/shoulda-matchers#977]
Setup:

``` ruby
# Model
class User < ApplicationRecord
  has_one :active_subscription, class_name: Subscription
  has_one :active_service_package,
    through: :active_subscription,
    class_name: ServicePackage
end

# Test
describe User do
  it do
    should have_one(:active_service_package).
      through(:active_subscription).
      class_name(ServicePackage)
  end
end
```

Even if the Subscription model does not have an `:active_service_package` association, this test will pass; only if you actually use the association will you get: 

> ActiveRecord::HasManyThroughSourceAssociationNotFoundError: Could not find the source association(s) "active_service_package" or :active_service_package in model Subscription.

The `have_one` matcher should exercise the association somehow and rescue this exception, causing the test to fail.

**Comment by oliverklee** [comment]
have_many also is affected.

```ruby
    it do
      is_expected.to have_many(:dislikers)
        .class_name('Registration::Attendee')
        .through(:dislikes)
      tag.dislikers
    end
```
  ActiveRecord::HasManyThroughSourceAssociationNotFoundError: Could not find the source association(s) "disliker" or :dislikers in model Registration::Dislike. Try 'has_many :dislikers, :through => :dislikes, :source => <name>'. Is it one of attendee or tag?

**Comment by mcmire** [comment]
A related issue is that `has_one` doesn't raise an error if you attempt to test a has_one through a has_many:

``` ruby
# Model
class User < ApplicationRecord
  has_many :account_memberships
  has_one :account, through: :account_memberships
end

# Test
describe User do
  it { should have_one(:account).through(:account_memberships) }
end
```

I believe this should raise an error, because if you actually attempt to exercise the association, á la:

``` ruby
describe User do
  describe "#account" do
    it "returns the first account through account_memberships" do
      user = create(:user)
      account = create(:account)
      create(:account_membership, account: account, user: user)
      expect(user.account).to eq(account)
    end
end
```

then you get this error:

```
ActiveRecord::HasOneThroughCantAssociateThroughCollection:
  Cannot have a has_one :through association 'User#account' where the :through association 'User#account_memberships' is a collection. Specify a has_one or belongs_to association in the :through option instead.
```

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
