### ISSUE TITLE
Globalize compatibility ?

### ISSUE THREAD

**Issue by anthony-robin** [thoughtbot/shoulda-matchers#978]
I am using `Globalize` gem to my project and can't figured out how to test presence of translated attributes. Is there a way to do it or is it a bug from this gem ?

Here is what I tried:

```ruby
  # Model
  class Post < ApplicationRecord
    translates :title # Globalize translation

    active_admin_translates :title do
      validates :title, presence: true # Globalize validation rule
    end
  end

  # Test
  should validate_presence_of(:'translations.title') # NoMethodError: undefined method `translations.title=' for ...
```

- Rails 5.0.0.1
- ActiveAdmin 1.0.0pre4
- Minitest 5.9.1
- Shoulda-matchers 2.8.0

**Comment by mcmire** [comment]
@anthony-robin I didn't know what Globalize was, so I just looked it up. If I understand correctly, it can be used to translate values of attributes in your model, is that correct? If that's true, it seems to me that validations would work exactly the same way as they do without Globalize. Does this work?

``` ruby
it { should validate_presence_of(:title) }
```

**Comment by anthony-robin** [comment]
@mcmire Thanks !  Yes, Globalize is used to translate columns from a model: it stores translations in a second table for each model (not the original model) but the things is that `title` column is **only** set in the `translations table`.

I tried your code and it give me the following error:
```bash
Expected errors to include **MY ERROR MESSAGE** when title is set to nil,
got no errors
```

Usually Globalize use `translations.title` key to store values so I'm surprised that my first try didn't work.

**Comment by mcmire** [comment]
Ah, I gotcha.

shoulda-matchers doesn't know about Globalize. If you give the `validate_presence_of` matcher an argument, it'll assume that you're referring to an attribute. That's why you're getting the `undefined method `translations.title='` error above.

However, if you translate that attribute first, then it should know what you mean:

``` ruby
it { should validate_presence_of(I18n.t("translations.title")) }
```
