### ISSUE TITLE
Testing validates_uniqueness_of with scopes and conditional 'if' clause

### ISSUE THREAD

**Issue by milmih** [thoughtbot/shoulda-matchers#982]
How to test this with shoulda-matchers?

```
  validates_uniqueness_of :kind_default, scope: [:kind, :kind_default],
                                         if: :kind_default?
```

How should I change this test in order for it to verify the above validation?

```
  it do
    should validate_uniqueness_of(:kind_default).scoped_to([:kind, :kind_default])
  end
```

Thanks!

EDIT: Is [this](http://stackoverflow.com/questions/13812717/shoulda-rspec-matchers-conditional-validation) the best solution?

**Comment by mcmire** [comment]
@milmih Good find, but unfortunately that solution won't work for `validate_uniqueness_of`. See #640 for more information and a possible solution. (I'm going to close this since it's a duplicate.)
