### ISSUE TITLE
render_template requires rails-controller-testing gem

### ISSUE THREAD

**Issue by mcmire** [thoughtbot/shoulda-matchers#998]
For RSpec projects, we don't need to do anything since rspec-rails automatically requires this gem.

But for Minitest projects, that doesn't happen, so right now people will have to manually add rails-controller-testing to their Gemfile if they want to use this matcher. We should probably just add it to the gemspec.

**Comment by guialbuk** [comment]
We should not add rails-controller-testing to gemspec until Rails 4.2 support is dropped because rails-controller-testing requires Rails ~> 5.x

Source code: https://github.com/rails/rails-controller-testing/blob/37cb8e33fe55a30bac4f99232e83144ba19f4152/rails-controller-testing.gemspec#L21-L25

**Comment by mcmire** [comment]
Ah, I didn't realize this issue was here. I ended up adding some instructions to the README for RSpec here: 43f4d05a18a2c2c0f57bc4b231fc2ed59590bc6b. But I didn't add anything for Minitest. I think we'll want to do that too.

**Comment by mcmire** [comment]
I just came across this issue and did not realize that RSpec automatically adds this gem. Once we get Shoulda upgraded to shoulda-matchers 4, we should move the `gem 'rails-controller-testing'` line to the Minitest section.

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!
